### ISSUE TITLE
Could not delete group

### ISSUE THREAD

**Issue by JaspervanKol** [andrei-tatar/node-red-contrib-smartnora#10]
Hello @andrei-tatar,

I added two lights in two groups, the "Woonkamer" group and the "Jasper" group. After a few days I deleted the lights and then deleted the config nodes in Node-RED so I can use the new version with a new group. But still after a new sync I still saw the lights in the Google app. So I went to the nora-firebase website to delete the groups there but unfortunately I can not delete the groups. Now I am stuck with 4 lights in the Google app with no use. Is this a bug or did I something wrong?

![image](https://user-images.githubusercontent.com/58696667/115140057-977a0800-a035-11eb-904b-6b96a9c9611e.png)

**Comment by andrei-tatar** [comment]
Hey, most probably a bug.
Can you try again after logging out and back in? I suspect that might fix it.

**Comment by JaspervanKol** [comment]
I tried logging back in but that did not solve the problem. I also used a different browser with no luck. I also tried reconnecting Smart NORA in the google app with no luck.

**Comment by andrei-tatar** [comment]
@JaspervanKol can you try again now?

**Comment by JaspervanKol** [comment]
@andrei-tatar yes it works. I deleted the groups and the lights disappeared in the Google app! Thank you
