### ISSUE TITLE
Node-RED failing to update Smart-Nora with devices

### ISSUE THREAD

**Issue by sumnerboy12** [andrei-tatar/node-red-contrib-smartnora#102]
User ID: BLaxAy5UbNOUhze71xYHedP96D62
Smart-Nora Version: 1.5.0
Node-RED Version: 2.0.6

I recently migrated my Node-RED instance from a docker container to a dedicated LXC container - so that I would get local execution working.

When I exported/imported all the Smart Nora flows I started seeing the error messages below, and https://smart-nora.eu/my-nora is showing zero devices.

I have tried deleting the default group but it keeps coming back with zero devices. I tried deleting the `nora-config` in Node-RED 
and recreating, but no luck.

I tried adding a group name, since the error mentions a missing query param `group` - but that didn't help either.

Any idea what is going wrong here?

```
Sep 21 22:02:03 app01 Node-RED[790]: 21 Sep 22:02:03 - [warn] nora: <default> - unhandled error (trying again in 78 sec): HTTP response (400 {"description":"\"group\" query param missing"})
Sep 21 22:02:03 app01 Node-RED[790]: Error: HTTP response (400 {"description":"\"group\" query param missing"})
Sep 21 22:02:03 app01 Node-RED[790]:     at FirebaseSync.doHttpCall (/home/nodered/.node-red/node_modules/node-red-contrib-smartnora/build/nora/sync.js:221:27)
Sep 21 22:02:03 app01 Node-RED[790]:     at runMicrotasks (<anonymous>)
Sep 21 22:02:03 app01 Node-RED[790]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
Sep 21 22:02:03 app01 Node-RED[790]:     at async FirebaseSync.handleJob (/home/nodered/.node-red/node_modules/node-red-contrib-smartnora/build/nora/sync.js:169:21)
```

**Comment by sumnerboy12** [comment]
After moving some of my nodes back to the docker based Node-RED instance, everything started working again. The Node-RED instance in the LXC container has no TLS certification - is that possibly causing a problem?

**Comment by andrei-tatar** [comment]
@sumnerboy12 can you check the group name if it has a value and make sure it's empty (no whitespaces)
![image](https://user-images.githubusercontent.com/6473183/134157277-9801dc99-07b3-40f0-ab4f-5c9e98fe9736.png)

> The Node-RED instance in the LXC container has no TLS certification - is that possibly causing a problem?

Shouldn't be the case

**Comment by andrei-tatar** [comment]
Most probably related to a bug in `node-fetch`: https://github.com/node-fetch/node-fetch/issues/1300
Seems the latest version of node-fetch has a bug sending the query params... As a quick fix, you can manually install node-fetch version 2.6.1 

```
cd ~/.node-red (or where your installation is)
npm install node-fetch@2.6.1
```

**Comment by sumnerboy12** [comment]
That seems to have fixed it - thanks so much!!

So once node-fetch is patched I should be able to upgrade again?

**Comment by andrei-tatar** [comment]
Yes! Will probably be fixed with the next release of `node-fetch` (2.6.4)

**Comment by LinusU** [comment]
So sorry for the breakage! This was fixed in version `node-fetch` version `2.6.4` so if you try to upgrade again it should work...

**Comment by andrei-tatar** [comment]
Actually, leaving the issue open in case other users installed the plugin yesterday.

**Comment by andrei-tatar** [comment]
Haven't seen this error in the logs, so I will close it
