### ISSUE TITLE
Can't install smartnora in node-red

### ISSUE THREAD

**Issue by mharst** [andrei-tatar/node-red-contrib-smartnora#104]
Hi all,

I'm completely new to this and I was trying to add smartnora to my Node-red installation (on Windows 10 64bit).
But when installing I'm getting this error:

2021-10-03T17:40:21.374Z npm.cmd install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-contrib-smartnora@1.5.1
2021-10-03T17:40:21.376Z [err] Error: spawn npm.cmd ENOENT
2021-10-03T17:40:21.376Z rc=-4058

Can anyone help me solving this issue?
Kind regards,

Martin.

**Comment by andrei-tatar** [comment]
Hi, what node.js/npm version are you running?
What if you try to install it manually inside your node-red folder (`npm install node-red-contrib-smartnora`)?

**Comment by mharst** [comment]
I'm running node-red 2.0.6
Tried to install manually. But in powershell, got this: \Common was unexpected at this time.
When I look in Node-red in the palette, looks like smartnora is installed, but actually can't see the according nodes on the left side.
So something still goes wrong.

**Comment by andrei-tatar** [comment]
What version of `node.js` and `npm` are you running?

```
node -v
npm -v
```

**Comment by mharst** [comment]
node version: 16.10.0
npm version: 7.24.1

**Comment by andrei-tatar** [comment]
How did you install `node-red`? Is it a global installation? Maybe it needs elevated rights to be able to install it...

If you create a local installation, does it work?

```
mkdir test
cd test
npm install node-red node-red-contrib-smartnora
.\node_modules\.bin\node-red.cmd
```

**Comment by mharst** [comment]
Could it be that I'm using it as user HARN on this computer and that I started Powershell as ADMIN?
Got an error:
complete debug log can be found here: [2021-10-04T10_38_38_240Z-debug.log](https://github.com/andrei-tatar/node-red-contrib-smartnora/files/7277459/2021-10-04T10_38_38_240Z-debug.log)
g

**Comment by andrei-tatar** [comment]
> Could it be that I'm using it as user HARN on this computer and that I started Powershell as ADMIN?

I don't think so... Have you tried a local installation with the commands I sent you? Does it still fail?

**Comment by mharst** [comment]
I managed to install it locally with the commands. Thank you. The problem is solved.
No I have to find a way to program it with SmartNora so I can use my google assistant to raise the temperature on my TOON thermostat ...

**Comment by andrei-tatar** [comment]
If you can already control your thermostat from node-red, adding Smart NORA for google integration should be fairly easy.
Good luck!
