### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by JN-CLS** [andrei-tatar/node-red-contrib-smartnora#11]
Hi,
I'm new to node-red and just starting to use the system with Nora to connect my old S7 plc to the new home automation world.

I tried some nodes out. For the moment the light is the only one that responds to a visual status on Google home app.
I also have blinds and the generic open/close. Both seem to respond in node-red to the status I inject, but on Google home App they stay unchanged with the gear icon indication. I can command only by voice. 
Is there a list of what nodes do update the status on Google Home and can be activated via the app screen ?
When will those other nodes then have this feature ?

Thank you,
Jan

**Comment by andrei-tatar** [comment]
Hi,
Unfortunately that is not under my control. The widgets that show up in Google Home and developed and maintained by the team at Google.
Not sure where you can find a list of the device types that have "dynamic" widgets. 
So far Switch/Outlet/Light/Thermostat can be controlled from the Android app.

**Comment by andrei-tatar** [comment]
Added an entry to the FAQ:
https://github.com/andrei-tatar/node-red-contrib-smartnora/blob/master/doc/faq/README.md#some-devices-show-no-status-in-google-home-app-and-can-only-be-controlled-using-voice

Will close this issue.

**Comment by JN-CLS** [comment]
Thank you for the feedback Andrei.

Great work !
Thx
