### ISSUE TITLE
Nodes (e.g. Switch) do not completely connect and are flagged offline in Google home app

### ISSUE THREAD

**Issue by apfffr** [andrei-tatar/node-red-contrib-smartnora#117]
Hi,

I installed/setup Smart-Nora according to the install guide. I had NORA installed previously but deinstalled, restarted Node-Red etc.
I use the example Flow for the Switch-Node. Configured for a home and room, using nora config, no firebird.
I can turn the switch, which I called "Desktop", on/off/online/offline according to the sample flow...
On the Google Home app I see the Switch but mostly it is not connected. When I click it, it says no connection. When I open the switch though, I see a glow in the background when it is on in Node-Red and no glow when it is off in Node-Red, so somehow it is connected and reflects the state.
I can sometimes switch it in the Google Home app, but the state is not replicated to Node-Red

So somehow the switch is poorly connected, but not usable.
I already waited a day, resetted the whole setup, but nothing works. Also it seems to not use the local connection.
What is the issue?

My User ID is xEJOZlQJJOc7M6MYYGN6w3KRZww2.

**Comment by andrei-tatar** [comment]
@apfffr That is a sign that the node-red instance loses connection to the cloud service. 
How are you running node-red? On what machine? How is it connected to the internet? Any logs from node-red?

**Comment by apfffr** [comment]
Hi,
Node-Red is running on a Windows Server 2016 which is in a local domain and connected to the internet.
There are no infos in the log, I guess. See below

Node-RED version: 2.1.3: Maintenance Release
NodeJS version: v16.13.0
Device running Node-RED: HP ProLiant MicroServer Gen8 G1610T

`15 Nov 17:38:50 - [info] Server now running at http://127.0.0.1:88/
15 Nov 17:38:50 - [info] Starting flows
15 Nov 17:38:51 - [info] Started flows
15 Nov 17:38:51 - [info] [aedes broker:e5421aeb.f1bab8] Binding aedes mqtt server on port: 1883
15 Nov 17:38:51 - [info] [zigbee2mqtt-server:6a4a8154.e670b] MQTT Connected
15 Nov 17:38:51 - [info] [zigbee2mqtt-server:6a4a8154.e670b] Refreshing devices
15 Nov 17:38:51 - [info] [mqtt-broker:20894250.f9e8fe] Connected to broker: mqtt://localhost:1883
15 Nov 17:38:53 - [info] nora: authenticated, uid: xEJOZlQJJOc7M6MYYGN6w3KRZww2
15 Nov 17:38:53 - [info] nora: <default> - disconnected
15 Nov 17:38:57 - [info] nora: <default> - connected
15 Nov 17:38:57 - [info] [zigbee2mqtt-server:6a4a8154.e670b] MQTT Subscribed to: "zigbee2mqtt/#
15 Nov 17:38:57 - [info] [zigbee2mqtt-server:6a4a8154.e670b] Refreshing devices
15 Nov 17:39:03 - [info] nora: <default> - synced 1 device(s)`

**Comment by andrei-tatar** [comment]
@apfffr but any long-time logs (more then a day)? Are you still experiencing the issue?
Can you run a ping from that machine to an internet server? What is the average response time?

**Comment by apfffr** [comment]
Hi,
I will keep a log and post it tomorrow or a day later.
I just restarted and got no nora log entry so far
> 16 Nov 12:42:46 - [info] Node-RED version: v2.1.3
> 16 Nov 12:42:46 - [info] Node.js  version: v16.13.0
> 16 Nov 12:42:46 - [info] Windows_NT 10.0.14393 x64 LE
> 16 Nov 12:42:48 - [info] Loading palette nodes
> 16 Nov 12:42:53 - [info] Settings file  : C:\node-red-user\settings.js
> 16 Nov 12:42:53 - [info] Context store  : 'default' [module=localfilesystem]
> 16 Nov 12:42:53 - [info] User directory : C:\node-red-user\userfolder
> 16 Nov 12:42:53 - [warn] Projects disabled : editorTheme.projects.enabled=false
> 16 Nov 12:42:53 - [info] Flows file     : C:\node-red-user\userfolder\flows_main.json
> 16 Nov 12:42:53 - [info] Server now running at http://127.0.0.1:88/
> 16 Nov 12:42:53 - [info] Starting flows
> 16 Nov 12:42:54 - [info] Started flows
> 16 Nov 12:42:54 - [info] [aedes broker:e5421aeb.f1bab8] Binding aedes mqtt server on port: 1883
> 16 Nov 12:42:54 - [info] [zigbee2mqtt-server:6a4a8154.e670b] MQTT Connected
> 16 Nov 12:42:54 - [info] [zigbee2mqtt-server:6a4a8154.e670b] Refreshing devices
> 16 Nov 12:42:54 - [info] [mqtt-broker:20894250.f9e8fe] Connected to broker: mqtt://localhost:1883
> 16 Nov 12:43:00 - [info] [zigbee2mqtt-server:6a4a8154.e670b] MQTT Subscribed to: "zigbee2mqtt/#
> 16 Nov 12:43:00 - [info] [zigbee2mqtt-server:6a4a8154.e670b] Refreshing devices
> 16 Nov 12:43:43 - [info] Stopping modified nodes
> 16 Nov 12:43:43 - [info] Stopped modified nodes
> 16 Nov 12:43:43 - [info] Starting modified nodes
> 16 Nov 12:43:43 - [info] Started modified nodes
> 16 Nov 12:44:44 - [info] [zigbee2mqtt-server:6a4a8154.e670b] Using cached devices

Also here is the ping from the node-red machine
> C:\>ping www.google.de
> 
> Ping wird ausgeführt für www.google.de [216.58.213.195] mit 32 Bytes Daten:
> Antwort von 216.58.213.195: Bytes=32 Zeit=14ms TTL=116
> Antwort von 216.58.213.195: Bytes=32 Zeit=17ms TTL=116
> Antwort von 216.58.213.195: Bytes=32 Zeit=15ms TTL=116
> Antwort von 216.58.213.195: Bytes=32 Zeit=19ms TTL=116
> 
> Ping-Statistik für 216.58.213.195:
>     Pakete: Gesendet = 4, Empfangen = 4, Verloren = 0
>     (0% Verlust),
> Ca. Zeitangaben in Millisek.:
>     Minimum = 14ms, Maximum = 19ms, Mittelwert = 16ms

**Comment by andrei-tatar** [comment]
> on/off/online/offline according to the sample flow...

@apfffr by the way, did you happen to set the device offline and not move it back to online? When you mark a device `offline`, Google Home shows it `Offline` and it doesn't accept commands.

**Comment by apfffr** [comment]
I did switch it to offline, it got a hollow red status indicator then.
I always switched it back to online (green indicator) and then I could switch between on/off.

Also the switch still did not conenct so far (no indicator at all, and no entry in the log).
So I added a second, new switch. Same, no indicator at all and not even shown on smart-nora.eu

Some currently it is even worse than before.
Do I have to open specific ports or something?

**Comment by andrei-tatar** [comment]
After you add a new switch and deploy, it takes a few seconds for the devices to sync and show the green bar.
Do you have any errors now in the node-red log?

> Do I have to open specific ports or something?

No, only if you want local execution.

**Comment by apfffr** [comment]
So there was no connection because the config node was empty (don't know how that happened).
After I entered the config again now it suddenly works perfectly fine and fast.
Working with Google Home App and Voice Commands very good.
Thank you.
