### ISSUE TITLE
Most of my Nora commands have periods of time when they stop working

### ISSUE THREAD

**Issue by Heisenberg2980** [andrei-tatar/node-red-contrib-smartnora#118]
I have multiple Nora nodes to turn on/off different devices (lights, laptops, TV) and sometimes most of them stop working. They still appear as connected in node-red but google always reply with either "sorry, I don´t understand" or "sorry, it looks like that device hasn´t been set up yet. You can do that in Assistant settings".

This is an example, one command failing at 17:20:
![image](https://user-images.githubusercontent.com/58039006/141832397-c438776e-3dfa-4395-a54f-b16b74aab208.png)

And then the same command working at 18:06:
![image](https://user-images.githubusercontent.com/58039006/141832327-29bcfb46-e076-4ceb-902b-0a5a4cb108ca.png)

Once one of the devices works, all the devices work as well, so it looks like a general issue.

**Comment by andrei-tatar** [comment]
I also notice this sometimes when using voice control. I just retry the command and it works the 2nd time.
Unfortunately, it's not related to NORA. 

https://www.androidpolice.com/2021/02/02/youre-not-alone-google-home-outage-leaving-some-users-with-device-not-yet-set-up-error/

All I can suggest is open an issue on Google Assistant. Or you can ask google to send feedback: 
>  "Hey Google, send feedback," and then stating, "I can't control home automation device via voice."
