### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by ma261065** [andrei-tatar/node-red-contrib-smartnora#12]
I received the following errors when trying to install SmartNora:

19 Apr 15:11:51 - [info] Installing module: node-red-contrib-smartnora, version: 1.0.2
19 Apr 15:13:02 - [info] Installed module: node-red-contrib-smartnora
19 Apr 15:13:02 - [info] Added node types:
19 Apr 15:13:02 - [info]  - node-red-contrib-smartnora:noraf-blinds : Error: Cannot find module '/home/pi/.node-red/node_modules/ajv/lib/ajv.js'. Please verify that the package.json has a valid "main" entry
19 Apr 15:13:02 - [info]  - node-red-contrib-smartnora:noraf-config
19 Apr 15:13:02 - [info]  - node-red-contrib-smartnora:noraf-scene : Error: Cannot find module '/home/pi/.node-red/node_modules/ajv/lib/ajv.js'. Please verify that the package.json has a valid "main" entry
19 Apr 15:13:02 - [info]  - node-red-contrib-smartnora:noraf-speaker : Error: Cannot find module '/home/pi/.node-red/node_modules/ajv/lib/ajv.js'. Please verify that the package.json has a valid "main" entry
19 Apr 15:13:02 - [info]  - node-red-contrib-smartnora:noraf-switch : Error: Cannot find module '/home/pi/.node-red/node_modules/ajv/lib/ajv.js'. Please verify that the package.json has a valid "main" entry
19 Apr 15:13:02 - [info]  - node-red-contrib-smartnora:noraf-thermostat : Error: Cannot find module '/home/pi/.node-red/node_modules/ajv/lib/ajv.js'. Please verify that the package.json has a valid "main" entry
19 Apr 15:13:02 - [info]  - node-red-contrib-smartnora:noraf-outlet : Error: Cannot find module '/home/pi/.node-red/node_modules/ajv/lib/ajv.js'. Please verify that the package.json has a valid "main" entry
19 Apr 15:13:02 - [info]  - node-red-contrib-smartnora:noraf-light : Error: Cannot find module '/home/pi/.node-red/node_modules/ajv/lib/ajv.js'. Please verify that the package.json has a valid "main" entry
19 Apr 15:13:02 - [info]  - node-red-contrib-smartnora:noraf-garage : Error: Cannot find module '/home/pi/.node-red/node_modules/ajv/lib/ajv.js'. Please verify that the package.json has a valid "main" entry
19 Apr 15:13:02 - [info]  - node-red-contrib-smartnora:noraf-lock : Error: Cannot find module '/home/pi/.node-red/node_modules/ajv/lib/ajv.js'. Please verify that the package.json has a valid "main" entry
19 Apr 15:13:02 - [info]  - node-red-contrib-smartnora:noraf-notify : Error: Cannot find module '/home/pi/.node-red/node_modules/ajv/lib/ajv.js'. Please verify that the package.json has a valid "main" entry
19 Apr 15:13:02 - [info]  - node-red-contrib-smartnora:noraf-openclose : Error: Cannot find module '/home/pi/.node-red/node_modules/ajv/lib/ajv.js'. Please verify that the package.json has a valid "main" entry

**Comment by andrei-tatar** [comment]
Hmm, that's a weird one. Can you provide a bit more info?
node version, node-red version?

**Comment by ma261065** [comment]
Sure - Node Red version is v1.3.1
How do I find the Node version?

**Comment by andrei-tatar** [comment]
just run `node --version` in a terminal

**Comment by ma261065** [comment]
Node version is v12.21.0

**Comment by andrei-tatar** [comment]
I think the package installation went wrong. `ajv` is a package from the dependency tree and it should've been installed.

I would try stopping node-red and executing the following:
```
cd ~/.node-red
npm install
```

**Comment by ma261065** [comment]
Looks good now. Thanks for the assistance!!

pi@raspberrypi:~ $ node-red-stop

Stop Node-RED

Use   node-red-start   to start Node-RED again

pi@raspberrypi:~ $ cd ~/.node-red
pi@raspberrypi:~/.node-red $ npm install
audited 214 packages in 6.035s

19 packages are looking for funding
  run `npm fund` for details

found 2 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
pi@raspberrypi:~/.node-red $ node-red-start

Start Node-RED

Once Node-RED has started, point a browser at http://192.168.1.25:1880
On Pi Node-RED works better with the Firefox or Chrome browser

Use   node-red-stop                          to stop Node-RED
Use   node-red-start                         to start Node-RED again
Use   node-red-log                           to view the recent log output
Use   sudo systemctl enable nodered.service  to autostart Node-RED at every boot
Use   sudo systemctl disable nodered.service to disable autostart on boot

To find more nodes and example flows - go to http://flows.nodered.org

Starting as a systemd service.
19 Apr 16:39:02 - [info]
Welcome to Node-RED
===================
19 Apr 16:39:02 - [info] Node-RED version: v1.3.1
19 Apr 16:39:02 - [info] Node.js  version: v12.21.0
19 Apr 16:39:02 - [info] Linux 5.10.11-v7+ arm LE
19 Apr 16:39:03 - [info] Loading palette nodes
19 Apr 16:39:08 - [info] Dashboard version 2.28.2 started at /ui
19 Apr 16:39:09 - [info] Settings file  : /home/pi/.node-red/settings.js
19 Apr 16:39:09 - [info] Context store  : 'default' [module=memory]
19 Apr 16:39:09 - [info] User directory : /home/pi/.node-red
19 Apr 16:39:09 - [warn] Projects disabled : editorTheme.projects.enabled=false
19 Apr 16:39:09 - [info] Flows file     : /home/pi/.node-red/flows_raspberrypi.json
19 Apr 16:39:09 - [info] Server now running at http://127.0.0.1:1880/
19 Apr 16:39:09 - [warn]
---------------------------------------------------------------------
Your flow credentials file is encrypted using a system-generated key.
If the system-generated key is lost for any reason, your credentials
file will not be recoverable, you will have to delete it and re-enter
your credentials.
You should set your own key using the 'credentialSecret' option in
your settings file. Node-RED will then re-encrypt your credentials
file using your chosen key the next time you deploy a change.
---------------------------------------------------------------------
19 Apr 16:39:09 - [info] Starting flows
19 Apr 16:39:09 - [info] Started flows
19 Apr 16:39:09 - [info] [aedes broker:MQTTBroker] Binding aedes mqtt server on port: 1883
19 Apr 16:39:10 - [info] [mqtt-broker:960cfec5.4104e] Connected to broker: mqtt://localhost:1883
19 Apr 16:39:24 - [info] Installing module: node-red-contrib-smartnora, version: 1.0.2
19 Apr 16:40:19 - [info] Installed module: node-red-contrib-smartnora
19 Apr 16:40:21 - [info] Added node types:
19 Apr 16:40:21 - [info]  - node-red-contrib-smartnora:noraf-blinds
19 Apr 16:40:21 - [info]  - node-red-contrib-smartnora:noraf-config
19 Apr 16:40:21 - [info]  - node-red-contrib-smartnora:noraf-scene
19 Apr 16:40:21 - [info]  - node-red-contrib-smartnora:noraf-speaker
19 Apr 16:40:21 - [info]  - node-red-contrib-smartnora:noraf-switch
19 Apr 16:40:21 - [info]  - node-red-contrib-smartnora:noraf-thermostat
19 Apr 16:40:21 - [info]  - node-red-contrib-smartnora:noraf-outlet
19 Apr 16:40:21 - [info]  - node-red-contrib-smartnora:noraf-light
19 Apr 16:40:21 - [info]  - node-red-contrib-smartnora:noraf-garage
19 Apr 16:40:21 - [info]  - node-red-contrib-smartnora:noraf-lock
19 Apr 16:40:21 - [info]  - node-red-contrib-smartnora:noraf-notify
19 Apr 16:40:21 - [info]  - node-red-contrib-smartnora:noraf-openclose
