### ISSUE TITLE
FirebaseError: Firebase: Error (auth/network-request-failed)

### ISSUE THREAD

**Issue by franciscomorais** [andrei-tatar/node-red-contrib-smartnora#123]
I have an error today with authentication in NodeRED. I can login in web application but with nodered plugin, I've receive this error.

![image](https://user-images.githubusercontent.com/35690067/144686980-645ab7aa-6ca3-4805-af72-cae4200f3a06.png)

Also, I suggest to put a link in web application to call support for paid subscriptions.

**Comment by andrei-tatar** [comment]
Hey,

- What is the user id? 
- Are you sure you used the correct credentials email/password? 
- What version of node-red/nora are you using?
- Does your instance of node-red have internet access?
- Did it work before? Is this a new issue?
- Was this a transient issue?

> Also, I suggest to put a link in web application to call support for paid subscriptions.

There is no phone support yet and I don't expect to have one in the near future.

**Comment by franciscomorais** [comment]
Hi,

> What is the user id?
kPbCxvXNpoY1b35HN8rW96zrlsM2
> Are you sure you used the correct credentials email/password?
Yes
> What version of node-red/nora are you using?
v2.1.4
> Does your instance of node-red have internet access?
Yes, I have.
<img src="https://user-images.githubusercontent.com/35690067/144709748-26c89a5f-ae6d-4178-8b6c-7febf628a60b.png" width="480px" />
> Did it work before? Is this a new issue?
No. I already managed to get the plugin working ... yesterday it broke.
> Was this a transient issue?
No.. It still not working today..
> There is no phone support yet and I don't expect to have one in the near future.
I mean that the webapp should be have a short text to explain how the user could contact the support. Maybe a button to redirect to github issues page.

**Comment by franciscomorais** [comment]
Well, I realize that I have an internet connection issue. I connect the HA to internet via wire and now I have other problem:

![image](https://user-images.githubusercontent.com/35690067/144710964-abedc583-9a48-4d22-a933-1727da4e4d27.png)


How I can reset my password?

**Comment by franciscomorais** [comment]
Problem solved. This issue provides from the Wifi connection with static ip. For some reason, with Wifi connection and static IP, the DNS doesn't work. I plug a wire and the problem solved. 

But, I suggest to improve the error messages.

**Comment by andrei-tatar** [comment]
Great news! I'm glad you managed to find the issue

> I mean that the webapp should be have a short text to explain how the user could contact the support. Maybe a button to redirect to github issues page.

Good point. I'll add this.
