### ISSUE TITLE
Flows stopped due to missing node types.      noraf-outlet

### ISSUE THREAD

**Issue by marekhalmo** [andrei-tatar/node-red-contrib-smartnora#125]
Hello..

after installing smartnora - if i place any smartnora node to a flow i get this error:
Flows stopped due to missing node types.

    noraf-outlet

Is the same for all smartnora nodes..

Also if i manage palette i can see this under smartnora
    [object Object]
    [object Object]
    [object Object]
    [object Object]
    [object Object]
    [object Object]
    [object Object]
    [object Object]
    [object Object]
    [object Object]
    [object Object]
    [object Object]
    [object Object]
    [object Object]
    [object Object]
    [object Object]
    [object Object]
    [object Object]
    [object Object]

Can you help?

My user id is wjkBdbmRu4MTAbydmGGUX4Jn2123

**Comment by andrei-tatar** [comment]
```
Flows stopped due to missing node types. noraf-outlet
```
Hi, this error seems to indicate you don't actually have smartnora installed or something went wrong during the installation. Is there anything else in the logs?

**Comment by marekhalmo** [comment]
Install log

2021-12-07T13:45:21.928Z npm.cmd install --no-audit --no-update-notifier --save --save-prefix="~" --production node-red-contrib-smartnora@1.6.2
2021-12-07T13:46:01.625Z [out] 
2021-12-07T13:46:01.625Z [out] > node-aead-crypto@2.2.0 preinstall C:\Users\KakaownikMini\.node-red\node_modules\node-aead-crypto
2021-12-07T13:46:01.625Z [out] > node lib/preinstall.js
2021-12-07T13:46:01.625Z [out] 
2021-12-07T13:46:02.042Z [err] node-aead-crypto not needed on this system, since all ciphers are natively supported
2021-12-07T13:46:02.284Z [out] 
2021-12-07T13:46:02.284Z [out] > core-js@3.6.5 postinstall C:\Users\KakaownikMini\.node-red\node_modules\core-js
2021-12-07T13:46:02.284Z [out] > node -e "try{require('./postinstall')}catch(e){}"
2021-12-07T13:46:02.284Z [out] 
2021-12-07T13:46:02.656Z [out] [96mThank you for using core-js ([94m https://github.com/zloirock/core-js [96m) for polyfilling JavaScript standard library![0m
2021-12-07T13:46:02.656Z [out] 
2021-12-07T13:46:02.656Z [out] [96mThe project needs your help! Please consider supporting of core-js on Open Collective or Patreon: [0m
2021-12-07T13:46:02.656Z [out] [96m>[94m https://opencollective.com/core-js [0m
2021-12-07T13:46:02.656Z [out] [96m>[94m https://www.patreon.com/zloirock [0m
2021-12-07T13:46:02.656Z [out] 
2021-12-07T13:46:02.656Z [out] [96mAlso, the author of core-js ([94m https://github.com/zloirock [96m) is looking for a good job -)[0m
2021-12-07T13:46:02.656Z [out] 
2021-12-07T13:46:02.695Z [out] 
2021-12-07T13:46:02.695Z [out] > protobufjs@6.11.2 postinstall C:\Users\KakaownikMini\.node-red\node_modules\protobufjs
2021-12-07T13:46:02.695Z [out] > node scripts/postinstall
2021-12-07T13:46:02.695Z [out] 
2021-12-07T13:46:04.365Z [err] npm 
2021-12-07T13:46:04.365Z [err] WARN ws@7.5.6 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
2021-12-07T13:46:04.365Z [err] npm WARN ws@7.5.6 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
2021-12-07T13:46:04.365Z [err] npm WARN ws@7.4.1 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
2021-12-07T13:46:04.365Z [err] npm WARN ws@7.4.1 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
2021-12-07T13:46:04.365Z [err] npm
2021-12-07T13:46:04.365Z [err]  WARN ws@7.2.3 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
2021-12-07T13:46:04.365Z [err] npm WARN ws@7.2.3 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
2021-12-07T13:46:04.365Z [err] npm WARN ws@8.3.0 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
2021-12-07T13:46:04.366Z [err] npm WARN ws@8.3.0 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
2021-12-07T13:46:04.367Z [err] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-aead-crypto@2.2.0 (node_modules\node-aead-crypto):
2021-12-07T13:46:04.367Z [err] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-aead-crypto@2.2.0 preinstall: `node lib/preinstall.js`
2021-12-07T13:46:04.367Z [err] npm
2021-12-07T13:46:04.367Z [err]  WARN optional
2021-12-07T13:46:04.367Z [err]  SKIPPING OPTIONAL DEPENDENCY: Exit status 1
2021-12-07T13:46:04.367Z [err] 
2021-12-07T13:46:04.371Z [out] + node-red-contrib-smartnora@1.6.2
2021-12-07T13:46:04.371Z [out] added 103 packages from 103 contributors in 38.62s
2021-12-07T13:46:04.473Z rc=0

**Comment by marekhalmo** [comment]
@andrei-tatar The flows contain the node so it is installled - configuration also works :\

**Comment by andrei-tatar** [comment]
@marekhalmo Have you tried restarting node-red after the install? What node-red version are you using?

**Comment by marekhalmo** [comment]
@andrei-tatar Restart did not help, Using node 1.0.4 (win)

**Comment by andrei-tatar** [comment]
@marekhalmo I just tried on win 10 x64 with `node-red 1.0.4` and latest `node-red-contrib-smartnora`.

**Comment by andrei-tatar** [comment]
@marekhalmo can you try installing node-red-contrib-smartnora again. Maybe something went wrong during the install

**Comment by marekhalmo** [comment]
@andrei-tatar Tried that before.. it did not work.. im trying to upgrade nodejs and node-red to latest version (2.xx and 8.2).. i will report what happend afterwards..

**Comment by andrei-tatar** [comment]
node.js latest LTS version is 16 :)

**Comment by marekhalmo** [comment]
Sorry .. :) 
Nodejs 16.13.1
nodered 2.1.4

**Comment by andrei-tatar** [comment]
@marekhalmo did that solve the issue?

**Comment by marekhalmo** [comment]
@andrei-tatar heh.. the whole win install of node-red failed.. i'm not able to install serial port node which is a major deal breaker .. i'm trying to solve that now..  but no solution yet on the other issue

**Comment by LuisThein** [comment]
Hi I have the same issue. The node-red log output is as follows:
```
Dec 21 07:44:19 raspberrypi Node-RED[377]: 21 Dec 07:44:19 - [info]
Dec 21 07:44:19 raspberrypi Node-RED[377]: Welcome to Node-RED
Dec 21 07:44:19 raspberrypi Node-RED[377]: ===================
Dec 21 07:44:19 raspberrypi Node-RED[377]: 21 Dec 07:44:19 - [info] Node-RED version: v1.3.4
Dec 21 07:44:19 raspberrypi Node-RED[377]: 21 Dec 07:44:19 - [info] Node.js  version: v10.24.0
Dec 21 07:44:19 raspberrypi Node-RED[377]: 21 Dec 07:44:19 - [info] Linux 5.10.63-v7l+ arm LE
Dec 21 07:44:21 raspberrypi Node-RED[377]: 21 Dec 07:44:21 - [info] Loading palette nodes
Dec 21 07:44:25 raspberrypi Node-RED[377]: 21 Dec 07:44:25 - [info] Dashboard version 2.26.2 started at /ui
Dec 21 07:44:27 raspberrypi Node-RED[377]: (node:377) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, scandir '/usr/lib/node_modules/node-red/node_modules/@node-red/nodes/examples'
Dec 21 07:44:27 raspberrypi Node-RED[377]: (node:377) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .
Dec 21 07:44:27 raspberrypi Node-RED[377]: (node:377) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Dec 21 07:44:27 raspberrypi Node-RED[377]: 21 Dec 07:44:27 - [warn] ------------------------------------------------------
Dec 21 07:44:27 raspberrypi Node-RED[377]: 21 Dec 07:44:27 - [warn] [node-red-contrib-smartnora/noraf-ac] ReferenceError: TextDecoder is not defined
Dec 21 07:44:27 raspberrypi Node-RED[377]: 21 Dec 07:44:27 - [warn] [node-red-contrib-smartnora/noraf-airpurifier] ReferenceError: TextDecoder is not defined
Dec 21 07:44:27 raspberrypi Node-RED[377]: 21 Dec 07:44:27 - [warn] [node-red-contrib-smartnora/noraf-blinds] ReferenceError: TextDecoder is not defined
Dec 21 07:44:27 raspberrypi Node-RED[377]: 21 Dec 07:44:27 - [warn] [node-red-contrib-smartnora/noraf-camera] ReferenceError: TextDecoder is not defined
Dec 21 07:44:27 raspberrypi Node-RED[377]: 21 Dec 07:44:27 - [warn] [node-red-contrib-smartnora/noraf-fan] ReferenceError: TextDecoder is not defined
Dec 21 07:44:27 raspberrypi Node-RED[377]: 21 Dec 07:44:27 - [warn] [node-red-contrib-smartnora/noraf-garage] ReferenceError: TextDecoder is not defined
Dec 21 07:44:27 raspberrypi Node-RED[377]: 21 Dec 07:44:27 - [warn] [node-red-contrib-smartnora/noraf-light] ReferenceError: TextDecoder is not defined
Dec 21 07:44:27 raspberrypi Node-RED[377]: 21 Dec 07:44:27 - [warn] [node-red-contrib-smartnora/noraf-lock] ReferenceError: TextDecoder is not defined
Dec 21 07:44:27 raspberrypi Node-RED[377]: 21 Dec 07:44:27 - [warn] [node-red-contrib-smartnora/noraf-media] ReferenceError: TextDecoder is not defined
Dec 21 07:44:27 raspberrypi Node-RED[377]: 21 Dec 07:44:27 - [warn] [node-red-contrib-smartnora/noraf-notify] ReferenceError: TextDecoder is not defined
Dec 21 07:44:27 raspberrypi Node-RED[377]: 21 Dec 07:44:27 - [warn] [node-red-contrib-smartnora/noraf-openclose] ReferenceError: TextDecoder is not defined
Dec 21 07:44:27 raspberrypi Node-RED[377]: 21 Dec 07:44:27 - [warn] [node-red-contrib-smartnora/noraf-outlet] ReferenceError: TextDecoder is not defined
Dec 21 07:44:27 raspberrypi Node-RED[377]: 21 Dec 07:44:27 - [warn] [node-red-contrib-smartnora/noraf-scene] ReferenceError: TextDecoder is not defined
Dec 21 07:44:27 raspberrypi Node-RED[377]: 21 Dec 07:44:27 - [warn] [node-red-contrib-smartnora/noraf-security] ReferenceError: TextDecoder is not defined
Dec 21 07:44:27 raspberrypi Node-RED[377]: 21 Dec 07:44:27 - [warn] [node-red-contrib-smartnora/noraf-sensor] ReferenceError: TextDecoder is not defined
Dec 21 07:44:27 raspberrypi Node-RED[377]: 21 Dec 07:44:27 - [warn] [node-red-contrib-smartnora/noraf-speaker] ReferenceError: TextDecoder is not defined
Dec 21 07:44:27 raspberrypi Node-RED[377]: 21 Dec 07:44:27 - [warn] [node-red-contrib-smartnora/noraf-switch] ReferenceError: TextDecoder is not defined
Dec 21 07:44:27 raspberrypi Node-RED[377]: 21 Dec 07:44:27 - [warn] [node-red-contrib-smartnora/noraf-thermostat] ReferenceError: TextDecoder is not defined
Dec 21 07:44:27 raspberrypi Node-RED[377]: 21 Dec 07:44:27 - [warn] [node-red-contrib-smartnora/noraf-async] ReferenceError: TextDecoder is not defined
Dec 21 07:44:27 raspberrypi Node-RED[377]: 21 Dec 07:44:27 - [warn] [node-red-node-serialport/serialport] Error: The module '/home/pi/.node-red/node_modules/@serialport/bindings/build/Release/bindings.node'
Dec 21 07:44:27 raspberrypi Node-RED[377]: was compiled against a different Node.js version using
Dec 21 07:44:27 raspberrypi Node-RED[377]: NODE_MODULE_VERSION 83. This version of Node.js requires
Dec 21 07:44:27 raspberrypi Node-RED[377]: NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
Dec 21 07:44:27 raspberrypi Node-RED[377]: the module (for instance, using `npm rebuild` or `npm install`).
Dec 21 07:44:27 raspberrypi Node-RED[377]: 21 Dec 07:44:27 - [warn] ------------------------------------------------------
Dec 21 07:44:27 raspberrypi Node-RED[377]: 21 Dec 07:44:27 - [info] Settings file  : /home/pi/.node-red/settings.js
Dec 21 07:44:27 raspberrypi Node-RED[377]: 21 Dec 07:44:27 - [info] Context store  : 'default' [module=memory]
Dec 21 07:44:27 raspberrypi Node-RED[377]: 21 Dec 07:44:27 - [info] User directory : /home/pi/.node-red
Dec 21 07:44:27 raspberrypi Node-RED[377]: 21 Dec 07:44:27 - [warn] Projects disabled : editorTheme.projects.enabled=false
Dec 21 07:44:27 raspberrypi Node-RED[377]: 21 Dec 07:44:27 - [info] Flows file     : /home/pi/.node-red/flows_raspberrypi.json
Dec 21 07:44:27 raspberrypi Node-RED[377]: 21 Dec 07:44:27 - [warn]
Dec 21 07:44:27 raspberrypi Node-RED[377]: ---------------------------------------------------------------------
Dec 21 07:44:27 raspberrypi Node-RED[377]: Your flow credentials file is encrypted using a system-generated key.
Dec 21 07:44:27 raspberrypi Node-RED[377]: If the system-generated key is lost for any reason, your credentials
Dec 21 07:44:27 raspberrypi Node-RED[377]: file will not be recoverable, you will have to delete it and re-enter
Dec 21 07:44:27 raspberrypi Node-RED[377]: your credentials.
Dec 21 07:44:27 raspberrypi Node-RED[377]: You should set your own key using the 'credentialSecret' option in
Dec 21 07:44:27 raspberrypi Node-RED[377]: your settings file. Node-RED will then re-encrypt your credentials
Dec 21 07:44:27 raspberrypi Node-RED[377]: file using your chosen key the next time you deploy a change.
Dec 21 07:44:27 raspberrypi Node-RED[377]: ---------------------------------------------------------------------
Dec 21 07:44:27 raspberrypi Node-RED[377]: 21 Dec 07:44:27 - [info] Waiting for missing types to be registered:
Dec 21 07:44:27 raspberrypi Node-RED[377]: 21 Dec 07:44:27 - [info]  - noraf-light
Dec 21 07:44:27 raspberrypi Node-RED[377]: 21 Dec 07:44:27 - [info]  - noraf-switch
Dec 21 07:44:27 raspberrypi Node-RED[377]: 21 Dec 07:44:27 - [info] Server now running at http://127.0.0.1:1880/
Dec 21 07:48:21 raspberrypi Node-RED[377]: 21 Dec 07:48:21 - [info] Upgrading module: node-red-dashboard to version: 3.1.2
Dec 21 07:48:37 raspberrypi Node-RED[377]: 21 Dec 07:48:37 - [info] Upgraded module: node-red-dashboard. Restart Node-RED to use the new version
Dec 21 07:49:18 raspberrypi systemd[1]: Stopping Node-RED graphical event wiring tool...
Dec 21 07:49:18 raspberrypi Node-RED[377]: 21 Dec 07:49:18 - [info] Stopping flows
Dec 21 07:49:18 raspberrypi Node-RED[377]: 21 Dec 07:49:18 - [info] Stopped flows
Dec 21 07:49:18 raspberrypi systemd[1]: nodered.service: Succeeded.
Dec 21 07:49:18 raspberrypi systemd[1]: Stopped Node-RED graphical event wiring tool.
Dec 21 07:49:18 raspberrypi systemd[1]: Started Node-RED graphical event wiring tool.
Dec 21 07:49:21 raspberrypi Node-RED[2409]: 21 Dec 07:49:21 - [info]
Dec 21 07:49:21 raspberrypi Node-RED[2409]: Welcome to Node-RED
Dec 21 07:49:21 raspberrypi Node-RED[2409]: ===================

```

I tried updating the node-red installation but it's still not working.

**Comment by andrei-tatar** [comment]
@LuisThein your problem seems to be different. You probably have an older version of node.js (pre 12). You should probably upgrade node.js to a more recent LTS (14 or 16).

**Comment by andrei-tatar** [comment]
@LuisThein it seems you also have problems with the `serialport` module:

```
Dec 21 07:44:27 raspberrypi Node-RED[377]: 21 Dec 07:44:27 - [warn] [node-red-node-serialport/serialport] Error: The module '/home/pi/.node-red/node_modules/@serialport/bindings/build/Release/bindings.node'
Dec 21 07:44:27 raspberrypi Node-RED[377]: was compiled against a different Node.js version using
Dec 21 07:44:27 raspberrypi Node-RED[377]: NODE_MODULE_VERSION 83. This version of Node.js requires
Dec 21 07:44:27 raspberrypi Node-RED[377]: NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
Dec 21 07:44:27 raspberrypi Node-RED[377]: the module (for instance, using `npm rebuild` or `npm install`).
```

**Comment by khabowski** [comment]
Hi, I have this same problem. RedNode 1.0.2. My nodes stopped to work so I updated smart nora in the pallette to the newest version. After it I got this in pallette

[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]

Instead of types of nodes. What can I do?
