### ISSUE TITLE
Cosmetic:node.status uses not rounded number

### ISSUE THREAD

**Issue by GravityRZ** [andrei-tatar/node-red-contrib-smartnora#126]
I am translating HUE numbers to HSV numbers to feed into the nora light  nodes which works very well
However the numbers are not rounded when used to display the node.status.

is it possible to use 2 digit rounded numbers for the node.status ?
ofcourse keep on calculating with the max digit numbers otherwise we get color differences when translating back and forth
![image](https://user-images.githubusercontent.com/16853535/145076797-dfae9d8a-7d6a-4f09-87f5-0c19faa281d5.png)

**Comment by andrei-tatar** [comment]
Yup, though I would argue no decimal should be fine for the status display. So a status of `on 65 hue: 62 sat: 85 val: 100` is probably enough. What do you think?

**Comment by GravityRZ** [comment]
yes, i agree very nice as long as the rounded numbers are not used in the payload.

**Comment by andrei-tatar** [comment]
should be fixed in `v1.6.3`

**Comment by GravityRZ** [comment]
tested and seems to be working
i however seem to missing a lot of devices in google home which are present in node-red
did something change?
i completely removed the coupling and added it again but without result

![image](https://user-images.githubusercontent.com/16853535/145266892-2a7cf13e-b33b-4245-bdf6-7d44f8b29a15.png)

**Comment by andrei-tatar** [comment]
Do you have a subscription? The number of devices for the free version has been limited to 5.
https://github.com/andrei-tatar/node-red-contrib-smartnora/discussions/63

**Comment by GravityRZ** [comment]
oh, that is something new. whenever did this happen?

i currently have everything configured in Siri (totally free)
the google part i used for testing/demonstartinig purposes.

well to bad .
so there is not a one time fee for people who helped/tested to get nora where it is today (a very good product)

**Comment by andrei-tatar** [comment]
> oh, that is something new. whenever did this happen?

Well, it was announced since the beginning but it's been required only from the 1st of December: https://github.com/andrei-tatar/node-red-contrib-smartnora#subscription

 > so there is not a one time fee for people who helped/tested to get nora where it is today (a very good product)

No, it's subscription based.

**Comment by GravityRZ** [comment]
ok. clear. i will stop using it since i hardly use it in real life. thought it would be nice to get google on par with siri but since siri is integrated in al my apple devices there is no real need for google

**Comment by andrei-tatar** [comment]
ok. I will close this since the original issue is resolved.
Feel free to leave any feedback related to the subscription here: https://github.com/andrei-tatar/node-red-contrib-smartnora/discussions/63
