### ISSUE TITLE
cant execute a "close all blinds" command

### ISSUE THREAD

**Issue by Dud3z** [andrei-tatar/node-red-contrib-smartnora#135]
Hi, i cant execute a close all command on my blinds.

if i tell my nest hub to close all blinds it shows me all blinds and it seems that it understood my command.

i attached a debug node to all my Blind Nodes but only one reacts. if i tell the nest hub to close them one by one it works.

Any Idea why it does not react as it should?

**Comment by andrei-tatar** [comment]
@Dud3z Interesting, I remember this was fixed a while ago. What version of node-red-contrib-smartnora are you using?
I'll have a look into it.

**Comment by andrei-tatar** [comment]
Just tested both local and cloud execution for 3 blinds with latest `node-red-contrib-smartnora` package and both commands (Open/close all blinds) work as expected.

**Comment by Dud3z** [comment]
@andrei-tatar Hi, sorry for late reply.
im on the latest smartnora version. 

if i say "close all blinds" but in german (Schließe alle Rolladen) it reacts like in the screenshot: 
![image](https://user-images.githubusercontent.com/20781313/147374242-61574102-e944-48bd-9448-f255822e6eba.png)

**Comment by andrei-tatar** [comment]
@Dud3z That's what I was thinking to suggest (turning off the local execution).
Maybe the deployed local execution script is out of date. Will need to check with someone at Google.

**Comment by andrei-tatar** [comment]
@Dud3z btw, can you try rebooting all your Google Home/Nest devices in your local network and try enabling local execution again? I'm curious if it's just a caching issue.
