### ISSUE TITLE
Commands for Remote

### ISSUE THREAD

**Issue by milandzuris** [andrei-tatar/node-red-contrib-smartnora#136]
Hi, whats the command for turn on-off tv remote, im try with inject and dont work.
i need command for volume, power, source, mute, thx so much.
![image](https://user-images.githubusercontent.com/42905545/147486516-efb89dc8-ed14-4e5c-b883-2370cd0f7cb4.png)
![image](https://user-images.githubusercontent.com/42905545/147486548-b8cd3261-9009-48bb-aa3c-97daf2d94e4e.png)

**Comment by andrei-tatar** [comment]
@milandzuris Is this the `media device` node? You can read the doc [here](https://github.com/andrei-tatar/node-red-contrib-smartnora/blob/master/doc/nodes/media/README.md).

> Input/output 1 payload is an object with the following properties:
> - online - boolean: true/false, default: true. Flag that indicates if a device is online.
> - on - boolean: true/false, default: false. (if the On/Off Trait is enabled)
> - volume - number: 0-100, default: 40. (if the Volume Trait is enabled)
> - mute - boolean, default: false. (if the Volume Trait is enabled)
> - activity - enum [INACTIVE, STANDBY, ACTIVE] (if the Media State trait is enabled)
> - playback - enum [PAUSED, PLAYING, FAST_FORWARDING, REWINDING, BUFFERING, STOPPED] (if the Media State trait is enabled)
> - input - string - the value of the current selected input
> - application - string - the value of the current running application

**Comment by andrei-tatar** [comment]
@milandzuris did this work for you?

**Comment by milandzuris** [comment]
> @milandzuris did this work for you?

not working
