### ISSUE TITLE
I have an issue while using NORA

### ISSUE THREAD

**Issue by M48tin** [andrei-tatar/node-red-contrib-smartnora#137]
Hello everybody,

I'm a student in automation and I use Smart NORA with my Raspberry to control my house long time ago. I felicity you because it's THE perfect solution! Well done!

But I have a bug.

New devices didn't work with Google Home Speakers, but with the phone, it's work!
The speaker says she couldn’t establish the communication with Smart NORA.	

Can you find the solution?

Thank you, Martin from Switzerland

My user id is: Ivi1lAK9AvbTxuvPOLx03UUEmaa2

**Comment by andrei-tatar** [comment]
Hi @M48tin 

I think someone reported this issue some while ago and the solution was to reset the Google Home device.
I would first try to make sure you have the correct google and smart nora account is linked in your Google Home speaker and app. If it is the correct one and still not working, I would try to factory reset the Google Home speaker and set it up again.

I found it, this is the old issue: https://github.com/andrei-tatar/node-red-contrib-smartnora/issues/23

**Comment by M48tin** [comment]
Hi,
I already had make a reset of the Google Home device, still not working.
I will answer the other person who are in the House and make what you said.

I tell you if it’s work or not !

Thanks for the support,

Martin

**Comment by andrei-tatar** [comment]
@M48tin did you manage to solve the issue?

**Comment by M48tin** [comment]
Hi,

Sorry for the delay !!

No, it's isn't work. And the Thermostat funtion worked like 3 moths ago but now, that's isn't work.
It's write on Google Home App "disconnected".

Maybe, did you have made a big update ? I'm with the 1.3.0 !!!

Cheers !

**Comment by andrei-tatar** [comment]
@M48tin no breaking change. Any relevant info in the node-red logs? Is the internet connection ok on the device you're using?
Have you tried restarting node-red?

**Comment by M48tin** [comment]
I made this but : With new divices is now work !!!
But with my thermosats, that's still write "disconnected" !

I will update the version on my Raspberry ! Thank you !

**Comment by andrei-tatar** [comment]
Have you checked the logs? It might be that something is misconfigured.
Something like this should bring up the node-red logs:
`journalctl -u nodered.service`
