### ISSUE TITLE
Are curtains and open/close Device still only vocal?

### ISSUE THREAD

**Issue by Barabba11** [andrei-tatar/node-red-contrib-smartnora#14]
Hi! Thanks for SmartNora :) I'm testing it, are them still unavailable for touch operations? (Damn Google is taking more than one year to implement curtains.. ). Any trick for curtains? )

FOr Garage and lock I have "device must have 2FA pin" but I don't know what is about, I don't see them in Google home

**Comment by andrei-tatar** [comment]
Touch interaction for Open/Close devices only work on Smart Displays with Google Assistant (https://developers.google.com/assistant/smarthome/develop/touch-controls)

For Garage, you need to setup a 2FA pin in node-red. You can create a new config node with the same credentials:
![image](https://user-images.githubusercontent.com/6473183/115204944-b940c100-a101-11eb-9a17-363a01b701a2.png)

**Comment by Barabba11** [comment]
thank you, as I undersoon there aren't any chances to have in our Android phones touch commands for some devices yet (like curtains), only if we buy a smart display, do you think we can any way push on Google to introduce them? I think it's the only power we have.

**Comment by andrei-tatar** [comment]
I am not aware of any way to give feedback on the Google Home app, other than the play store page:
https://play.google.com/store/apps/details?id=com.google.android.apps.chromecast.app&hl=en&gl=US

**Comment by Barabba11** [comment]
We may all give them 1 star and sollecit for this, I've just done it. 
I wrote on Facebook to Google Nest, they replied and promised to forward the request to the development team. PLease do it too, thanks:
https://www.facebook.com/googlenest/

PS: may you evaluate to advertise other people (for example on read.me) about the chance to sollecit Facebook introduce these commends, thank you a lot!

**Comment by Barabba11** [comment]
We may write them to apps-help@google.com too
Thank you
