### ISSUE TITLE
Smart-nora Integration done 

### ISSUE THREAD

**Issue by manojgupta89** [andrei-tatar/node-red-contrib-smartnora#140]
Smart-nora integration done with Google Home but all 5 switch are not controling the physical device and all 5 switch is not found in Google assistant.

**Comment by andrei-tatar** [comment]
Can you provide more details? It's not really clear to me what the problem is.
Have you followed the setup guide? Are you using the same google account in both cases (Google Assistant/Google Home/etc.)
Controlling the physical devices falls under your flows responsibility. Nora can't control real devices if you don't configure your flow to do so.

**Comment by JobbeDeluxe** [comment]
Hello, looks like the connection is broken... for me it will not work, too. All was fine the last year. now 1.1.22 the device showen the right status in the nora page, but it will not switch... the google home will not find the switches anymore. error is the device is "offline".

**Comment by andrei-tatar** [comment]
@JobbeDeluxe Can you post the logs from node-red?

**Comment by JobbeDeluxe** [comment]
My user id is: CofNofCBGaPtdIe42jx4rd7WCnO2

node-red-contrib-smartnora
1.0.6

maybe a litte old, but workd for a long time without problem.

nodered do not send any error. the status is fine and right... also the showen status on the smartnora page, but switching is not working.

what logs do you like to have?

**Comment by JobbeDeluxe** [comment]
i upgraded to 
node-red-contrib-smartnora
1.8.1

now it worked :)

**Comment by manojgupta89** [comment]
I follow every process which are need. I use same email ID in Smart-nora and Google home. I repert the process endless time but result is same.

**Comment by andrei-tatar** [comment]
@manojgupta89 Have you tried restarting node-red? I see you're using an old version (1.0.6), can you try updating to latest?
Also please stop creating duplicate issues.

**Comment by andrei-tatar** [comment]
@manojgupta89 did you manage to solve the issue?

**Comment by manojgupta89** [comment]
Yes, I am using the same google account, but now I notice one thing
smart-nora has its own dashboard, when I login through my phone and it's
also controlling the physical device but at the same time google home fall
to perform the same thing.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by andrei-tatar** [comment]
@manojgupta89 In that case it must be something wrong with your Google Home setup. No idea what it could be.

**Comment by andrei-tatar** [comment]
@manojgupta89 Stop creating duplicate issues!
Have you followed the setup guide (https://github.com/andrei-tatar/node-red-contrib-smartnora/blob/master/doc/setup/README.md)?

What is not working for you? Can you provide more details/logs/screenshots?
