### ISSUE TITLE
Dashboard shows multiple Unassigned rooms each with a single device

### ISSUE THREAD

**Issue by normanr** [andrei-tatar/node-red-contrib-smartnora#146]
I have 3 devices without a room hint, and in the new dashboard UI they each show in their own `Unassigned` room.

Looking at the code this is because the default room name is applied _after_ the rooms are searched, so it'll never find the room that it created for other devices without a room hint.

My user id is: UVOhdwwyJDf5YXcMecDNesvd4NA2

**Comment by andrei-tatar** [comment]
Thanks for the investigation!
Should be fixed now.
