### ISSUE TITLE
Local execution in docker

### ISSUE THREAD

**Issue by nicandris** [andrei-tatar/node-red-contrib-smartnora#149]
Hey, I run nodered in a docker container and I can't get local execution to connect.

I opened the udp ports and tried sending the UDP discovery package, in the trace logs it sys it received it, but after a few hours local execution is still not connected.

I changed the network to 'host' so it runs on the same net as the host but still cant get it to connect. 

Ideas?

**Comment by andrei-tatar** [comment]
@nicandris Hey,

So you have enabled all 3 ports to your docker container?
6988 (broadcast by Google Home to discover devices)
6989 (NORA replies on this port to Google Home)
6987 (actual execution happens on this port, Google Home sends HTTP requests to NORA)

I assume you also have a Google Home in the same network. Can you see the UDP broadcasts on 6988 in your network?

**Comment by nicandris** [comment]
yeah i have in my docker compose
ports:
  - 192.168.178.209:1880:1880
  - 192.168.178.209:6987:6987/udp
  - 192.168.178.209:6988:6988/udp
  - 192.168.178.209:6989:6989/udp

and my ufw
[ 6] 1880                       ALLOW IN    Anywhere
[ 7] 6987:6989/udp              ALLOW IN    Anywhere

**Comment by andrei-tatar** [comment]
Maybe this helps:
- 6987 needs to be TCP (it's using HTTP).
- 8989 needs to be out (the response is sent from node-red to Google Home via UDP)

Also, have you tried running without docker? Does it work that way?

**Comment by nicandris** [comment]
I changed the ports to that but i dont see the discovery packages from any google home yet. I'll wait a bit.

btw, if I send the discovery package from another machine in my network, I can see it (I could also see it before)
`17 Jan 15:55:19 - [trace] [nora][local-execution] Received discovery packet, sending reply`

![image](https://user-images.githubusercontent.com/284798/149802340-f8f4867f-5bc2-413e-bae8-ca02a814fc68.png)

**Comment by nicandris** [comment]
yeah... `from` in discovery method thinks the discovery packet is coming from the gateway of the docker network so its replying to that... not really sure if I can do anything about it, will need to ask some docker expert 😂 

[socket.send(responsePacket, DISCOVERY_REPLY_PORT, from);](https://github.com/andrei-tatar/node-red-contrib-smartnora/blob/5d9f3ef10b6914d7afd1a7d0aca82411e02716d9/src/nora/local-execution.ts#L37)

```
[UFW AUDIT] IN=br-081d24b03514 OUT= PHYSIN=veth7a8bf8d MAC=xxxxxxxx SRC=172.10.10.5 DST=172.10.10.1 LEN=69 TOS=0x00 PREC=0x00 TTL=64 ID=32853 DF PROTO=UDP SPT=6988 DPT=6989 LEN=49

[UFW AUDIT] IN= OUT=br-081d24b03514 SRC=172.10.10.1 DST=172.10.10.5 LEN=97 TOS=0x00 PREC=0xC0 TTL=64 ID=16749 PROTO=ICMP TYPE=3 CODE=3 [SRC=172.10.10.5 DST=172.10.10.1 LEN=69 TOS=0x00 PREC=0x00 TTL=64 ID=32853 DF PROTO=UDP SPT=6988 DPT=6989 LEN=49 ]
```

**Comment by nicandris** [comment]
weirdly when i send the discovery package manually from my desktop it recognizes it...
```

17 Jan 17:58:04 - [trace] [nora][local-execution] Received discovery packet from: 172.10.10.1, sending reply
17 Jan 17:58:07 - [trace] [nora][local-execution] Received discovery packet from: 192.168.178.10, sending reply
17 Jan 17:58:31 - [trace] [nora][local-execution] Received discovery packet from: 172.10.10.1, sending reply
```

**Comment by andrei-tatar** [comment]
@nicandris from your desktop which is running docker?
You may need to run the docker network in `host` mode, not in `bridge`.

**Comment by nicandris** [comment]
yeah i couldnt make it work with bridge mode (all of the above msgs 😂) i couldn't get it to work with host either until i disabled userland which doesnt make sense to me... anw if someone stumbles upon this, my solution was:
- allow ports through ufw if you are using it
- use network_mode: host
- add ```{
     "userland-proxy": false
}``` to `/etc/docker/daemon.json`


I'll mark this as solved 🙇 thanks for your help andrei!
