### ISSUE TITLE
Notify node reports error.

### ISSUE THREAD

**Issue by jvdpas** [andrei-tatar/node-red-contrib-smartnora#15]
Version: 1.0.2

I have currently 5 devices in my home app(also visible in MyNora). 
Tried to do a notify with no result. 
I have used the "click here to receive notifications" which reacts with "subscribed succesfuly" .

Node red error below :
`while updating state HTTP response (400 {"description":"user has no device(s) subscribed"}): Error: HTTP response (400 {"description":"user has no device(s) subscribed"})    at FirebaseSync.doHttpCall (/home/pi/.node-red/node_modules/node-red-contrib-smartnora/build/firebase/sync.js:192:27)    at process._tickCallback (internal/process/next_tick.js:68:7)`

**Comment by andrei-tatar** [comment]
You need to go to https://smart-nora.eu/my-nora on the device you want to receive the notifications and click the button:
![image](https://user-images.githubusercontent.com/6473183/115431446-fb572900-a20d-11eb-9547-19d20c24fecf.png)

I will update the node to show the error status when the request fails

**Comment by jvdpas** [comment]
See in above comment 
                      I have used the "click here to receive notifications" which reacts with "subscribed succesfuly" .

**Comment by andrei-tatar** [comment]
What device are you using?
I will need the user id to check the db and the logs but it's not exposed anywhere yet.

**Comment by jvdpas** [comment]
The device i expect to receive the notification is an android smartphone (LG G6).
My id is "jvdpas@tiscali.nl"

**Comment by andrei-tatar** [comment]
I did check the db and there are no tokens. Are you

**Comment by jvdpas** [comment]
Should i use the  "click here to receive notifications"  on the device i want to receive the notification?

**Comment by andrei-tatar** [comment]
> Should i use the  "click here to receive notifications"  on the device i want to receive the notification?
Yes

I did check the db and there are no tokens for your user, unfortunately there is a bug in the code that always says `Subscribed successfully`. Will fix it.
Also make sure you allow the permission for notifications for he site:
![image](https://user-images.githubusercontent.com/6473183/115512592-d1901780-a28a-11eb-9622-798a0fdce97e.png)

**Comment by andrei-tatar** [comment]
@jvdpas I see you have device tokens now in the db. Is this fixed?

**Comment by jvdpas** [comment]
No does not work yet.
The error in node-red is gone but no messages. 
I use Chrome with notifications allowed. 
After click here i get the message "Subscription is succesfull"

Thanx for asking

**Comment by nygma2004** [comment]
I just tested it on my system. I updated to 1.0.3 a few hours ago. I visited the site on my phone an enabled the notifications and it did come through. Did not even had to enable notification on Google.

May I use this issue to ask some related question?
- Can we send notification to Google devices, like a Home or Nest Hub?
- Can I pass setting into the notify tab to change the Title, Body, etc? Or I need to set it all on the node properties page?
- What tag is used for?
- What can I put into the icon field?

**Comment by andrei-tatar** [comment]
> Can we send notification to Google devices, like a Home or Nest Hub?

No. As far as I know, there's no API for this via smarthome actions.

> Can I pass setting into the notify tab to change the Title, Body, etc? Or I need to set it all on the node properties page?

Yes. Most of the properties can be passed via `msg.payload` object. I need to write some doc.

> What tag is used for?

Notifications with a tag will override previous ones with the same tag.

> What can I put into the icon field?

A link to an image. It needs to be hosted publicly and I think it needs to be https (not sure).

**Comment by andrei-tatar** [comment]
> No does not work yet.

Can you post the flow you're using?

**Comment by jvdpas** [comment]
Flow Works when i inject timestamps fast, debug message appears:

`while sending notification too many notifications per sec: Error: too many notifications per sec    at mergeJob (/home/pi/.node-red/node_modules/node-red-contrib-smartnora/build/firebase/sync.js:131:32)    at SafeSubscriber.source.subscribe.event [as _next] (/home/pi/.node-red/node_modules/node-red-contrib-smartnora/build/index.js:51:29)    at SafeSubscriber.__tryOrUnsub (/home/pi/.node-red/node_modules/rxjs/internal/Subscriber.js:205:16)    at SafeSubscriber.next (/home/pi/.node-red/node_modules/rxjs/internal/Subscriber.js:143:22)    at Subscriber._next (/home/pi/.node-red/node_modules/rxjs/internal/Subscriber.js:89:26)    at Subscriber.next (/home/pi/.node-red/node_modules/rxjs/internal/Subscriber.js:66:18)    at Subject.next (/home/pi/.node-red/node_modules/rxjs/internal/Subject.js:60:25)    at GroupBySubscriber._group (/home/pi/.node-red/node_modules/rxjs/internal/operators/groupBy.js:98:19)    at GroupBySubscriber._next (/home/pi/.node-red/node_modules/rxjs/internal/opera...`

**Comment by jvdpas** [comment]
The used flow :
`[{"id":"8ab4def4.c54a4","type":"noraf-notify","z":"ff65e0c4.4d1ff","tag":"","title":"Hello","body":"It works!","icon":"","name":"","nora":"7342540d.39289c","topic":"","actions":[],"x":390,"y":100,"wires":[["84d661fc.d03cd"]]},{"id":"1db51cd1.aa7b33","type":"inject","z":"ff65e0c4.4d1ff","name":"","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":150,"y":100,"wires":[["8ab4def4.c54a4"]]},{"id":"84d661fc.d03cd","type":"debug","z":"ff65e0c4.4d1ff","name":"","active":true,"tosidebar":true,"console":true,"tostatus":true,"complete":"true","targetType":"full","statusVal":"payload","statusType":"auto","x":590,"y":100,"wires":[]},{"id":"7342540d.39289c","type":"noraf-config","name":"nora config","group":"","twofactor":"off","twofactorpin":"","structure":"Thuis"}]`

**Comment by jvdpas** [comment]
I think it has to do with the receiving device.

**Comment by andrei-tatar** [comment]
> Flow Works when i inject timestamps fast, debug message appears(no messages on slow injects):

The error when you want to send too many notifications is by design.

> I think it has to do with the receiving device.

Might be...

**Comment by jvdpas** [comment]
I'm not able to subscribe with my smartphone.

![Capture+_2021-04-22-12-08-03](https://user-images.githubusercontent.com/47483325/115697213-a62d2b80-a363-11eb-9a82-8d7bda08babf.png)

**Comment by andrei-tatar** [comment]
On win 10, the messages are received in the windows notification center sidebar thingie.
On your device, if you click the lock next to the address, what do you see?
![image](https://user-images.githubusercontent.com/6473183/115697752-851d0880-a36c-11eb-8c8b-a74854594876.png)

**Comment by jvdpas** [comment]
![Capture+_2021-04-21-17-06-41](https://user-images.githubusercontent.com/47483325/115697911-5307a880-a364-11eb-9a77-db51aeb7404a.png)

**Comment by jvdpas** [comment]
It is android version 9

**Comment by andrei-tatar** [comment]
I think you have site notifications turned off in your browser. 
If you click the "3 dots" on the right -> Settings and follow: https://photos.app.goo.gl/zMVqJXPFUZ42metm6

Are the notifications turned off anywhere?

**Comment by jvdpas** [comment]
Win 10 works now. The "sidebar thingie" triggered me (had notifications off).
So android device is the problem Can't subscibe
![Capture+_2021-04-22-12-25-40](https://user-images.githubusercontent.com/47483325/115699784-471ce600-a366-11eb-9268-f1b45e140a19.png)

**Comment by jvdpas** [comment]
Needed an other settings tab and indeed now it is 👍 i'm happy.
Thanx for your support it works.
