### ISSUE TITLE
How to get notify works ?

### ISSUE THREAD

**Issue by bugLoverIO** [andrei-tatar/node-red-contrib-smartnora#151]
Hello

I've a working SmartNORA setup with one thermostat, and I'm trying to use the notify node.

On the documentation, it's written _"Node used to send web notifications to the subscribed devices. In order to get notifications on a device, you need to browse to https://smart-nora.eu/my-nora, login and click the button to subscribe to notfications."_
Nevertheless I can't find this feature on my account.

Did I miss something ?

Thanks

My user id is: wIihPowGDAeBH4b3S23vXwOb5Pq2

**Comment by andrei-tatar** [comment]
@bugLoverIO Hi,

The place changed, it's actually under the menu and notifications: https://smart-nora.eu/my-nora/notifications
I need to update the documentation as well:

![image](https://user-images.githubusercontent.com/6473183/149731398-bb8b109e-320e-4b9a-8ef0-883bbafddbaf.png)

**Comment by bugLoverIO** [comment]
Hi

Thanks for your prompt response.
By digging further I've discover my Safari browser does not show this menu, it weird because I though Safari on osX does support web push notification as opposed as Safari on iOS. Nevertheless after a few hick-ups, It works like a charm on Android. But I had to opened Smart Nora web site in Chrome browser and follow the regular process for accepting notification, for a weird reason it didn't work within the regular (latest) samsung Internet browser on my GS10 featuring Android 11. 

Thanks for your support and project.
