### ISSUE TITLE
I have an issue while using NORA

### ISSUE THREAD

**Issue by Armageddit** [andrei-tatar/node-red-contrib-smartnora#153]
Describe the problem here...

i get wrong devices in my google account!
old deleted ones

the devices on the dashbord from smartnora website are correct!

My user id is: KP9pL9rr43dIU0TPHeta4W3viYq1

**Comment by andrei-tatar** [comment]
@Armageddit the devices on the dashboard are the same ones that are sent to Google. Are you sure you are using the same account in node-red as you use on the dashboard?
