### ISSUE TITLE
I have an issue while using NORA

### ISSUE THREAD

**Issue by FoxConsult** [andrei-tatar/node-red-contrib-smartnora#157]
My 5 Node-RED devices all went off-line today. When I try to reconnect using my mobile phone with Google Home -> Settings -> Works with Google -> Smart NORA -> Reconnect account - > Sign in with email I get an error "That e-mail address isn't correct".

- My mistake! I can log in but my 5 Node-RED devices are still off-line. 

However, I just logged in using a web browser to https://smart-nora.eu/my-nora with the same e-mail address and that works fine.

My user id is: tkKbJxjQtGdEEceZzAuBMVQwRcy2

**Comment by andrei-tatar** [comment]
@FoxConsult can you check if you are having any network connectivity issues on your node-red hardware? Do you have any exceptions in the node-red logs? Have you tried restarting node-red?

**Comment by FoxConsult** [comment]
Hi Andrei,

Thank you for your quick reply!
Today all works fine.
