### ISSUE TITLE
Local execution check (from faq).

### ISSUE THREAD

**Issue by jvdpas** [andrei-tatar/node-red-contrib-smartnora#16]
I see my home devices but i do not see 
"under each there will be the Local Execution NORA script."
![image](https://user-images.githubusercontent.com/47483325/115424290-dc04cf80-a1fe-11eb-9c8f-d83f081a39a5.png)

**Comment by andrei-tatar** [comment]
I think none of your devices support local execution:
https://developers.google.com/assistant/smarthome/concepts/local#supported-devices

**Comment by jvdpas** [comment]
Think you are right. However strange google nest audio is not supported while nest mini is.
I will connect a nest mini to check this.

**Comment by jvdpas** [comment]
Same with a nest mini attached. This is a supported device, so something else is the problem.
![image](https://user-images.githubusercontent.com/47483325/115447308-a4a31c80-a218-11eb-9a6b-309d75c11094.png)

**Comment by geertvercamer** [comment]
I have the same problem
![image](https://user-images.githubusercontent.com/11328101/115504590-79e8b080-a278-11eb-8158-cf0d81b39935.png)

**Comment by andrei-tatar** [comment]
I'll ping the guys over at Google and try to find out what's going on.
Maybe the local execution is rolled out slower...

**Comment by andrei-tatar** [comment]
Maybe it's a security thing and not all users can see/debug the running scripts. Can any of you guys enable logging at trace level in node-red and see if you do get `local-execution` traces in the node-red logs?
https://nodered.org/docs/user-guide/runtime/logging

There should be messages like:
>[nora][local-execution] Received discovery packet, sending reply

**Comment by JaspervanKol** [comment]
I have the same problem as mentioned above.

![image](https://user-images.githubusercontent.com/58696667/115521559-8fb3a100-a28b-11eb-85c6-5704e55b0ce4.png)

I enabled logging at trace level and I get repeatedly the following log:

`21 Apr 10:23:38 - [trace] [nora][local-execution] Received discovery packet, sending reply`
`21 Apr 10:24:10 - [trace] [nora][local-execution] Received discovery packet, sending reply`
`21 Apr 10:24:19 - [trace] [nora][local-execution] Received discovery packet, sending reply`
`21 Apr 10:24:38 - [trace] [nora][local-execution] Received discovery packet, sending reply`
`21 Apr 10:25:10 - [trace] [nora][local-execution] Received discovery packet, sending reply`

I have 3 nora configs in node-red.

**Comment by andrei-tatar** [comment]
Ok, in that case I got it wrong in the FAQ. Probably not all users are able to see/debug the scripts.

@JaspervanKol if you trigger a command (turn on a light or something) from assistant or Google Home, do you also get a log similar to 
`[nora][local-execution] Executing {command} - device: {deviceId}`
?

**Comment by JaspervanKol** [comment]
I triggered a light with my google home device and got this in the logs:

`21 Apr 10:44:53 - [trace] [nora][local-execution] Executing action.devices.commands.OnOff - device: <default>|975f5836:f4d518`
`21 Apr 10:44:53 - [trace] [nora][local-execution][975f5836:f4d518] executed action.devices.commands.OnOff`

Does this mean local execution is working @andrei-tatar?

**Comment by andrei-tatar** [comment]
Yes! :)

**Comment by geertvercamer** [comment]
No luck here, I get about 20 lines like this in the log:

[trace] [nora][local-execution] [object Object], doesn't support local
execution, skipping

I have 1 Google Home, 2 Google Minis and Harmon Kardon speakers with Google
Assistant built in


Met vriendelijke groet,


Geert

**Comment by andrei-tatar** [comment]
@geertvercamer what devices do you have? Not all devices support local execution. (secondary verification devices, garage door, lock).

**Comment by geertvercamer** [comment]
I'm using it for blinds and the garagedoor.

Lights are handled fine by Google, no need for Nora there.

Lights are integrat


Met vriendelijke groet,


Geert

**Comment by andrei-tatar** [comment]
So I changed the code so that devices that receive commands over local execution will have the status color switched to blue.
I'll try to update the FAQ later today and release this new version.
![image](https://user-images.githubusercontent.com/6473183/115554469-29dd0e80-a2b7-11eb-9173-6e97aae76847.png)

**Comment by andrei-tatar** [comment]
I published version 1.0.3 of the package and update the FAQ. Will close this issue for now.

**Comment by geertvercamer** [comment]
It seems all my devices need the pin code: blinds, garage door, even
switches (which are really dummy devices to block or allow some procedures.

Looking forward for the option to skip the pin question


Met vriendelijke groet,


Geert

**Comment by andrei-tatar** [comment]
@geertvercamer you just need to create multiple configurations (using the same credentials). 
One with pin, one without pin and assign each one accordingly to each device.

In a future release, the pin configuration will be moved per device, but that's a big chunk of work.
