### ISSUE TITLE
I have an issue while using NORA

### ISSUE THREAD

**Issue by marmar1968** [andrei-tatar/node-red-contrib-smartnora#165]
Describe the problem here...

Hi,
I updated my NORA to latest version today and all may nodes are now in state "not connected". Is there any issue with last update or the problem is with my node-red instance?
When I start node-red in safe mode, it starts, when I click "deploy", it is succesful, but edition of  nora configuration falls and I get message "loading credentials" and than node-red is responding any more. Looking at  command line under WIndows (Node-red server) there is no typical message  that Nora nodes started and then connected to the cloud as usually.
Please advise.
My user id is: 5kFDFdVxLOMS3SkDfVpcd7mLvX53

**Comment by andrei-tatar** [comment]
Hi @marmar1968 ,
Can you post the logs from node-red?

**Comment by andrei-tatar** [comment]
@marmar1968 It seems your Node-RED instance had some trouble logging into NORA because of local network issues and it only retries 3 times and after that it gives up.
I will add a retry policy to retry network connection issues continuously (with delay).

**Comment by marmar1968** [comment]
Hi Andrei,
Thank you for you sugestion. Everything was perfect so far. Maybe Windows update is the source of my problem. I will investigate the network and let you know.
Regards,

**Comment by andrei-tatar** [comment]
@marmar1968 I just published node-red-contrib-smartnora version 1.11.2 which should fix the issue and retry authentication errors in most cases except 2 specific ones.

Can you please confirm if it fixes your issue?
Thanks for noticing this!

**Comment by marmar1968** [comment]
Hi Andrei,
Outstanding support!  I found my problem and it was not related to Nora but to one of my home  MQTT clients. This device lost input ground connection and  jammed my network with MQTT messages caused by floating digital input...
Again, thank you very much for your support and I recommend Nora to all users for integration of Node-Red with Google Assistant.

**Comment by marmar1968** [comment]
Version 1.11.2 looks to be OK as well.
I'm closing this issue.
