### ISSUE TITLE
I can see only 5 devices

### ISSUE THREAD

**Issue by Barabba11** [andrei-tatar/node-red-contrib-smartnora#166]
Hi, I've updated Nodered (raspberry) with the latest version of module, on the flow I have many devices that seems connected, but on hoogle home I can see only 5 devices.
I've tried unlink and rejoin, I tried all jumped in my mind. How can I solve? Thanks

**Comment by andrei-tatar** [comment]
Hi,
@Barabba11 do you have an active subscription? 
https://github.com/andrei-tatar/node-red-contrib-smartnora#subscription

**Comment by Barabba11** [comment]
Thank you mate for all your work and support, since I'm use it rarely (I'm using more Homekit and Dashboard) I'll look for something free

**Comment by andrei-tatar** [comment]
Cool, no worries.
