### ISSUE TITLE
Turn off warnings

### ISSUE THREAD

**Issue by TonKro** [andrei-tatar/node-red-contrib-smartnora#170]
My Nora switches are on a bus with several json data. Some data is for the nora switches and some not. 

All data which is not for the switches does generate a warning in my debug log.  Like: [switchname] ignoring property msg.payload.name. 

How to disable these warnings?

**Comment by andrei-tatar** [comment]
@TonKro good point. I guess I could add a `Disable warning logs` checkbox option on the nora config entry. does that work for you?

**Comment by andrei-tatar** [comment]
@TonKro It's not there yet :) . Was asking if a new setting in the config node would work for you. 
I can add it next week probably so you can give it a try.

**Comment by TonKro** [comment]
Ah great, looking forward to that.

**Comment by andrei-tatar** [comment]
@TonKro published version `1.12.0` that supports disabling the validation warnings.

**Comment by TonKro** [comment]
Great, next week going to test.

**Comment by TonKro** [comment]
Works very good, it is a relief...

**Comment by andrei-tatar** [comment]
Glad to hear :)
