### ISSUE TITLE
Unsubscribe from notifications

### ISSUE THREAD

**Issue by Toby-Mills** [andrei-tatar/node-red-contrib-smartnora#172]
At https://smart-nora.eu/my-nora/notifications I can subscribe a device to notifications, but I'm struggling to find where I can unsubscribe a device from notifications

**Comment by andrei-tatar** [comment]
There is an option in the browsers usually to unsubscribe. I guess I could add a "clear subscriptions" button to the dashboard.
![image](https://user-images.githubusercontent.com/6473183/163242235-62f29abe-f2fb-48b1-a2e1-fb83f6ca398b.png)

**Comment by Toby-Mills** [comment]
Oh, if all I need to do is block notifications from the site, that's fine - done!

**Comment by andrei-tatar** [comment]
@Toby-Mills also added an option on the dashboard at https://smart-nora.eu/my-nora/notifications
![image](https://user-images.githubusercontent.com/6473183/163397281-2f7082e6-bb82-4878-98e6-e71591f9aa06.png)
