### ISSUE TITLE
I have an issue while using NORA

### ISSUE THREAD

**Issue by Flixm** [andrei-tatar/node-red-contrib-smartnora#176]
Hi Andrei,

often if i'm playin around with Senors or other Smart-Nora nodes and i change something of the settings of the Nodes (e.g.: Sensor change from Temp to open/close) and i say to my Google speaker "sync all devices", then it disconnected **all** SmartNora devices. 
After trying different things (don't ask which one the one successfull) it reconnected, but all items are dislinked to their rooms. There's no chance to save their linked Rooms :( ... any explanation why all Nodes are disconnected if i give the command to sync devices ?

Thanks in advance

My user id is: We7S2Dug7QPbtdk0A57E4mmEwOi2

**Comment by andrei-tatar** [comment]
@Flixm I must admit I never used the "sync all devices" command, via voice. I'll have a look and see if I can reproduce.
