### ISSUE TITLE
I have an issue while using NORA

### ISSUE THREAD

**Issue by MBerantzino** [andrei-tatar/node-red-contrib-smartnora#178]
Every time I deploy in node-red, all configured devices are listed as not belonging to any rooms in Google Home. If I move one manually in Google Home to a given room and deploy in node-red afterwards - then the association with the room is reset (the device is no longer associated with the room in Google Home).

In the webinterface (smart-nora.eu) the device is associated correctly with the room - however, this association is somehow lost in the communication with Google Home.

This appears to be a recent issue, as everything has been working up until lately (can't say exactly when it broke, but I discovered it a few days ago)

My user id is: Sf5LCcJlvsdk5YRLqlPgfzEneDO2

**Comment by andrei-tatar** [comment]
@MBerantzino that is weird. Do you have multiple homes configured in Google Home? Do you use multiple instances of node-red?

**Comment by MBerantzino** [comment]
@andrei-tatar I do have 2 homes configured - one recently created during a holiday.

I deleted this second home - and that fixed the problem.

Thank you for the assistance.
