### ISSUE TITLE
thermostat setpoint with .1 resolution but temperature with .5 resolution

### ISSUE THREAD

**Issue by GravityRZ** [andrei-tatar/node-red-contrib-smartnora#18]
I noticed this for some time now.

i can set the setpoint with a resolution of .1 degrees but the temperature itself is rounded to .5 degrees.

should it not be the other way around
setpoint with .5 degrees like a regular thermostat but the actual temperature with a .1 degree resolution

![image](https://user-images.githubusercontent.com/16853535/115610590-5c076400-a2e9-11eb-9422-29aa05a20e61.png)

**Comment by andrei-tatar** [comment]
The ambient temperature is rounded because Google Home rounds it to .5 so there's no point in having more accuracy.
But you're right, setpoint should also be rounded as well to .5.

**Comment by GravityRZ** [comment]
ok clear. thought it was a nora thing.
thanks
