### ISSUE TITLE
Latest version is crashing

### ISSUE THREAD

**Issue by rgerrans** [andrei-tatar/node-red-contrib-smartnora#181]
@andrei-tatar Just updated to latest and getting major errors

![image](https://user-images.githubusercontent.com/18623772/166568030-42673528-63e1-4e17-ae00-8bc30da34080.png)

**Comment by rgerrans** [comment]
I tried rolling back to an earlier version but keep getting a "waiting for missing types to be registered" no matter which version I use?

**Comment by rgerrans** [comment]
I've tried multiple uninstall/reinstalls of different versions and event tried flushing the npm cache between uninstall/reinstall. No love.....still getting syntax errors on node-red startup

```
3 May 16:53:50 - [warn] [node-red-contrib-smartnora/noraf-ac] SyntaxError: Unexpected token '.'
3 May 16:53:50 - [warn] [node-red-contrib-smartnora/noraf-airpurifier] SyntaxError: Unexpected token '.'
3 May 16:53:50 - [warn] [node-red-contrib-smartnora/noraf-blinds] SyntaxError: Unexpected token '.'
3 May 16:53:50 - [warn] [node-red-contrib-smartnora/noraf-camera] SyntaxError: Unexpected token '.'
3 May 16:53:50 - [warn] [node-red-contrib-smartnora/noraf-charger] SyntaxError: Unexpected token '.'
3 May 16:53:50 - [warn] [node-red-contrib-smartnora/noraf-doorbell] SyntaxError: Unexpected token '.'
3 May 16:53:50 - [warn] [node-red-contrib-smartnora/noraf-fan] SyntaxError: Unexpected token '.'
3 May 16:53:50 - [warn] [node-red-contrib-smartnora/noraf-garage] SyntaxError: Unexpected token '.'
3 May 16:53:50 - [warn] [node-red-contrib-smartnora/noraf-light] SyntaxError: Unexpected token '.'
3 May 16:53:50 - [warn] [node-red-contrib-smartnora/noraf-lock] SyntaxError: Unexpected token '.'
3 May 16:53:50 - [warn] [node-red-contrib-smartnora/noraf-media] SyntaxError: Unexpected token '.'
3 May 16:53:50 - [warn] [node-red-contrib-smartnora/noraf-notify] SyntaxError: Unexpected token '.'
3 May 16:53:50 - [warn] [node-red-contrib-smartnora/noraf-openclose] SyntaxError: Unexpected token '.'
3 May 16:53:50 - [warn] [node-red-contrib-smartnora/noraf-outlet] SyntaxError: Unexpected token '.'
3 May 16:53:50 - [warn] [node-red-contrib-smartnora/noraf-scene] SyntaxError: Unexpected token '.'
3 May 16:53:50 - [warn] [node-red-contrib-smartnora/noraf-security] SyntaxError: Unexpected token '.'
3 May 16:53:50 - [warn] [node-red-contrib-smartnora/noraf-sensor] SyntaxError: Unexpected token '.'
3 May 16:53:50 - [warn] [node-red-contrib-smartnora/noraf-sousvide] SyntaxError: Unexpected token '.'
3 May 16:53:50 - [warn] [node-red-contrib-smartnora/noraf-speaker] SyntaxError: Unexpected token '.'
3 May 16:53:50 - [warn] [node-red-contrib-smartnora/noraf-sprinkler] SyntaxError: Unexpected token '.'
3 May 16:53:50 - [warn] [node-red-contrib-smartnora/noraf-switch] SyntaxError: Unexpected token '.'
3 May 16:53:50 - [warn] [node-red-contrib-smartnora/noraf-thermostat] SyntaxError: Unexpected token '.'
3 May 16:53:50 - [warn] [node-red-contrib-smartnora/noraf-async] SyntaxError: Unexpected token '.'
3 May 16:53:50 - [warn] ------------------------------------------------------

```

**Comment by andrei-tatar** [comment]
@rgerrans can you try using `v1.13.3`? I switched back the target code generation to `ES2017`.

**Comment by rgerrans** [comment]
@andrei-tatar I still get the unexpected token errors on restart. 

I think there is something embedded in my system from v1.13.2. I even tried going back to the last local version I had from the last time I was working on nodes and it also generated that error. I've tried uninstalls w/ restarts w/ reinstalls. I also tried a forced npm cache clean.  I also reran the node-red installation script to see if that would clear it. So far nothing has worked so my entire system is down.

Anything other than a wipe and reinstall you can think of to clear the error?

**Comment by andrei-tatar** [comment]
@rgerrans  if you are running directly on a rpi, you can try:

```
cd ~/.node-red/
rm -rf node_modules/
npm install
```

This will delete and reinstall all the npm modules that you have installed for `node-red`.

**Comment by rgerrans** [comment]
@andrei-tatar Unfortunately still has the error on start?

**Comment by rgerrans** [comment]
hmmmm.....I went back to an old backup of Node-Red from last year, updated it to 2.2.2. Started fine. When I updated to nora v1.13.3 same error showed up?

**Comment by andrei-tatar** [comment]
@rgerrans really weird one. What node.js version are you using? I will try to reproduce

**Comment by rgerrans** [comment]
4 May 06:53:29 - [info] Node-RED version: v2.2.2
4 May 06:53:29 - [info] Node.js  version: v12.22.12
4 May 06:53:29 - [info] Linux 5.10.103-v7l+ arm LE

**Comment by rgerrans** [comment]
Just tried the same thing of going to my old copy, updated to NR2.2.2, rebuilt the node_modules, made sure all the other nodes were updated.  Started fine (I think it was smartnora v1.10.0) Manually updated to v1.12.0. Same issue with the token errors. Seems to be something outside on Node-Red. I've made sure all the other packages are up to date on my pi

**Comment by andrei-tatar** [comment]
@rgerrans found the issue. Forgot to change the common lib to ES2017 as well. Give me a few mins

**Comment by andrei-tatar** [comment]
@rgerrans published `v1.13.5`. There were 2 issues:
1. nora-firebase-common was still using ES2020
2. node-fetch v3 is not supported by node.js 12

Reverted these 2 changes and it works now. Tested with node.js v12.19

**Comment by rgerrans** [comment]
@andrei-tatar That worked, thanks!!! Back up and running.

Appreciate all the short-notice help!!!

**Comment by andrei-tatar** [comment]
Glad it worked! Need to automate the node.js compatibility check. I'm always keen on using the latest and the greatest features :)

**Comment by rgerrans** [comment]
I totally get that....been on the bleeding edge a few too many times over the years....

Unrelated, but last night in trying to get my system back online I checked out the Google Smarthome node. One thing I think it looked like they were doing was allow on a device node by device node basis to allow the node to create a persistent variable to store the state of the device. I'm doing it now as a one off flow, but might be a nice feature to add. Maybe using the Topic name for the variable name....just a thought

**Comment by andrei-tatar** [comment]
@rgerrans nora nodes have the possibility of staring the state in the node context so it persists in memory between redeploys or node changes. Is this what you are looking for?

![image](https://user-images.githubusercontent.com/6473183/166714763-cb60a4a2-c121-45f3-9cb2-d8631ba33c6e.png)

![image](https://user-images.githubusercontent.com/6473183/166715045-47adedc7-24a4-479e-af93-9bff89710b97.png)

**Comment by rgerrans** [comment]
Guess I need to figure out how to access that for other flows. Will do my research and come back with any questions. Thanks

**Comment by rgerrans** [comment]
Looks like Node level context is only visible to the node, not something you can reference outside the node....I want to be able to use it outside the node to check values against in other related flows

**Comment by andrei-tatar** [comment]
@rgerrans ah, got you. I will have a look at adding that, seems useful.

**Comment by andrei-tatar** [comment]
@rgerrans I navigated through the `node-red-contrib-google-smarthome` and it seems that when `Persistent state` is checked, they have a management node that outputs state changes from all nodes if they match some filters... Seems a bit cumbersome to me.

I was thinking of adding a property to each nora node (something similar to the change node) where you can specify where you want to save the state. Or do you think a "State change" node that outputs state changes is more useful?

![image](https://user-images.githubusercontent.com/6473183/166881831-cef92dfe-d94b-4ca1-8a32-40217f051761.png)

**Comment by rgerrans** [comment]
@andrei-tatar Sorry, this got lost in my  inbox. That's along the lines of what I had in mind as well
