### ISSUE TITLE
Sprinkler node

### ISSUE THREAD

**Issue by mvujica** [andrei-tatar/node-red-contrib-smartnora#184]
There is no documentation on sprinkler node, what are the I/O ?

My user id is: lhsnfOkC7JV0W8wJc9u2CcFn0az1

**Comment by andrei-tatar** [comment]
@mvujica Indeed, there is no documentation. Was out on a bit of holiday. Will have a look at adding some doco.

**Comment by mvujica** [comment]
Tnx. 
No hurry, I still haven't planted the grass seeds. 😉

**Comment by andrei-tatar** [comment]
Added documentation for the sprinkler node, will close the issue:
https://github.com/andrei-tatar/node-red-contrib-smartnora/blob/master/doc/nodes/sprinkler/README.md

**Comment by mvujica** [comment]
Thanks for update on docs but can't make sprinkler node to function. State is always "not running".
If I set a payload to true, status is "not running", if I set it to payload.on=true than massage appears:
"[Sprinkler1] ignoring property msg.payload.on"
Also the property "Ignore input messages that don't match the topic value" is always reverted back to false.

Can you please check, it behaves differently than light or outlet node?
