### ISSUE TITLE
Please don't kick me :-)

### ISSUE THREAD

**Issue by drsurfer** [andrei-tatar/node-red-contrib-smartnora#187]
Hi all
I am going mad, may be because I miss some basic info.
I am trying to control a fictional Switch via a simple node red network. 
![image](https://user-images.githubusercontent.com/13066684/173595065-2d8abc33-e8e5-4904-8f91-0badf799305a.png)
I see my "Cosa" device in Google Home app and I can control his state by hitting the button in app and by voice commands. In the debug node I receive the "true" and "false" messages, according to the "on" payload state.
The strange - for me - behaviour is that when I use the "on" and "off" injectors on node red panel, I see the state of device change (I read "on" and "off" changing, near the green square) but there is no output from the "Cosa" node, no debug strings,  and no change of the device status on Google Home App on my phone.
The inject nodes inject boolean values, and I think that the changing states of the Switch node mean that they are injecting correct messages.
What I'm doing wrong?

**Comment by andrei-tatar** [comment]
I also use tasmota and you can also use MQTT to update Google Home. I actually use pulsetime as well to turn on the dog feeder for a few seconds.

I just update the nora node input with the latest value that comes from MQTT.

So the latest state comes from: MQTT -> map -> NORA (without fwding the message to the output)
And the changes from nora go directly to MQTT: NORA -> map -> MQTT 

![image](https://user-images.githubusercontent.com/6473183/173625446-56b769bf-740b-4956-87dc-7ac0d3706724.png)

**Comment by drsurfer** [comment]
Thanks for all your valuable suggestions: in the meantime I have found a solution (very ugly and convoluted) to my problem, but I think I will throw it away soon because yours is simpler and very scalable.
