### ISSUE TITLE
Provide local fulfillment address

### ISSUE THREAD

**Issue by normanr** [andrei-tatar/node-red-contrib-smartnora#188]
There was a request to provide "The ability to identify which Google device has initiated a query so that any responses generated by node-red can be sent back to that specific device", (_Originally posted by @Syridian in https://github.com/andrei-tatar/node-red-contrib-smartnora/discussions/63#discussioncomment-1792295_).

I realized that for actions initiated via local fulfillment that `req.socket.address()` or `socket.remoteAddress` can be extracted and passed along and added to the nodered message (maybe as metadata, not as part of the main payload). The flow can then read it to determine which device the request came from. If needed a static dhcp address can be reserved to make this easier, but that's up to the user.

**Comment by andrei-tatar** [comment]
@normanr I can try to include that. Not sure if it will be as helpful as you think. As far as I can remember, the local commands are not issued from the device that you query.

I remember I had 3 Google Home Minis but only one would issue local commands. Also, the queries don't go via the local path so this would only work for commands.

**Comment by normanr** [comment]
Ahhh, i see what you mean. I ran a tcpdump on port 6987 and no matter which on my home mini's I used the local fulfillment request came from the same IP address 😞 

Oddly I see both devices sending discovery probes, but the Smart Home documentation is very clear that this is not supported:

From https://developers.google.com/assistant/smarthome/concepts/local:
> The Local Home platform is non-deterministic in choosing which Google Home or Google Nest device to trigger the command. The `EXECUTE` and `QUERY` intents may come through any Google Home or Google Nest device defined in the same [Home Graph structure](https://developers.google.com/assistant/smarthome/concepts/homegraph) as the target device.

From https://developers.google.com/assistant/smarthome/develop/local#debugging_tips:
> Do not link multiple Google Home or Google Nest devices to your test account on the same local network. You will not be able to control which Google Home or Google Nest device is targeted with the local fulfillment commands.
