### ISSUE TITLE
I have an issue while using NORA

### ISSUE THREAD

**Issue by rogerroger-coder** [andrei-tatar/node-red-contrib-smartnora#189]
Describe the problem here...
Hi,
the issue startet with a restart of node-red.
Scenes are not working - device is not availible. 
I can control other devices.
The nodes show 'connected' as a status.

Version 1.13.6

Let me know if you need Logs or something.
Thanks

My user id is: HqEvAxSCCxbcv6n3ed5khpyrO7C2

**Comment by andrei-tatar** [comment]
Hi @rogerroger-coder 
Do you have any errors in the node-red logs?

**Comment by rogerroger-coder** [comment]
Hi,
I did cut the integration into Google Home and reconnected it. 
I can't reproduce it anymore - reboots did work fine - all items working.
Will Smart Nora use IPv6 if its configured on the node-red host?
The IPv6 might habe changed when the issue appeard at first - as my hole house was without power.

**Comment by andrei-tatar** [comment]
@rogerroger-coder There are no such details in nora regarding IPv4 or IPv6. The OS decides what to use given a host name...
