### ISSUE TITLE
Failed to install min/max temperature in 'thermostat'.

### ISSUE THREAD

**Issue by Bezborodoff** [andrei-tatar/node-red-contrib-smartnora#19]
![IMG_20210422_152743](https://user-images.githubusercontent.com/2519724/115714058-63794c80-a37f-11eb-8158-614986d10be1.jpg)
Диапазон температур остаётся 20-32 градуса. The temperature range remains 20-32 degrees.

**Comment by andrei-tatar** [comment]
I also noticed the widget doesn't change the UI but the assistant does use the range when sending commands. Meaning Google will not set a higher than max, or lower than min, temperature.
So I think it's up to Google to update the widget UI in the Google Home app.
If you send me the uid I can check if the values (5/85) were sent to Google on sync.

**Comment by Bezborodoff** [comment]
Как это сделать?
How to do it?

**Comment by andrei-tatar** [comment]
Go to https://smart-nora.eu/my-nora and login (if not already)
![image](https://user-images.githubusercontent.com/6473183/115715456-d1724380-a380-11eb-9294-3e1010783ec5.png)

**Comment by Bezborodoff** [comment]
w4uwMFo7NDWcYMob3JjABKJv4kD3

**Comment by andrei-tatar** [comment]
Yup, the values are sent to Google. The issue is in the Google Home app in the widget. Not under my control.

![image](https://user-images.githubusercontent.com/6473183/115716074-7725b280-a381-11eb-80f6-a600aff665c9.png)

**Comment by Bezborodoff** [comment]
Thanks
