### ISSUE TITLE
no devices NORA 

### ISSUE THREAD

**Issue by MasterVigori** [andrei-tatar/node-red-contrib-smartnora#193]
I CANNOT CONNECT ANY MORE.

I paid €20.00 paid on February 23, 2022 for 1 year but it has expired but that is not true

Nodred logs:

30 Jun 02:04:27 - [info] Node-RED Version: v2.1.4
30 Jun 02:04:27 - [info] Node.js  Version: v14.19.0
30 Jun 02:04:27 - [info] Linux 5.10.92-v7l+ arm LE

i instal the new version node-red-contrib-smartnora 1.13.7.
I have no way to select version 1.13.8
![Unbenannt](https://user-images.githubusercontent.com/102611675/176568885-f9443b2b-573a-4b7a-bb1d-f01b32d534a1.JPG)

30 Jun 02:29:15 - [info] nora: authenticated, uid: 5fwXXXXXXXXXX............
30 Jun 02:29:15 - [info] nora: <default> - disconnected
30 Jun 02:29:16 - [info] nora: <default> - connected
30 Jun 02:29:19 - [warn] nora: <default> - unhandled error (trying again in 54.7 sec): (0 , undici_1.fetch) is not a function

You have no devices defined. Head over to your instance of Node-RED to define some devices or read the

30.6.2022, 02:12:05
msg : string[386]
string[386]

nora: <default> - unhandled error (trying again in 32.55 sec): (0 , undici_1.fetch) is not a function
TypeError: (0 , undici_1.fetch) is not a function
    at FirebaseSync.doHttpCall (/home/pi/.node-red/node_modules/node-red-contrib-smartnora/build/nora/sync.js:218:55)
    at FirebaseSync.handleJob (/home/pi/.node-red/node_modules/node-red-contrib-smartnora/build/nora/sync.js:169:21)
![index](https://user-images.githubusercontent.com/102611675/176566439-ed60c4dd-6c50-4287-b217-9a21fc786f09.jpg)

My user id is: qpjYxZxCT3TTsoUaU1ZNYL6kXot1

**Comment by andrei-tatar** [comment]
@MasterVigori Can you please upgrade `node-red-contrib-smartnora` to the latest version (`1.13.8`)?
A bug creeped through that affected setups that were running node.js 12 (https://github.com/andrei-tatar/node-red-contrib-smartnora/issues/191).

Sorry for the inconvenience.

**Comment by MasterVigori** [comment]
@andrei-tatar Can you please check why I only have access until July 30, 2022? There is also an error. I paid for a year in February!

**Comment by andrei-tatar** [comment]
> @andrei-tatar I would like to do the update but as you can see in the picture the update is not displayed and a manual installation is not allowed so how do I get version 1.13. 8 installed.

I updated the [node-red registry](https://flows.nodered.org/node/node-red-contrib-smartnora).
It might need some time for the new version to propagate to node-red. It probably caches the packages the indexes for a few hours (maybe a day). You should be able to manually update with `cd .node-red && npm install node-red-contrib-smartnora@1.13.8`.



> @andrei-tatar Can you please check why I only have access until July 30, 2022? There is also an error. I paid for a year in February!

I see in the node-red log you posted:
`30 Jun 02:29:15 - [info] nora: authenticated, uid: 5fwXXXXXXXXXX............`
but in the issue you opened:
`My user id is: qpjYxZxCT3TTsoUaU1ZNYL6kXot1`

I assume you are using 2 different NORA accounts. The one you opened this issue from (qpj... - using gmail.com), will expire next month.
The one your node-red is using (5fw... - using googleemail.com) has a subscription active for a year.
