### ISSUE TITLE
Slow service!?

### ISSUE THREAD

**Issue by Fragmike** [andrei-tatar/node-red-contrib-smartnora#194]
Hi. Since (some days) service is so slow. Just want to ask if this is caused by NORA or if the Issue is located @google. usually I got response Times <1 Sec. Now ist 4-5 secs.

Kind Regards Michael

**Comment by andrei-tatar** [comment]
Hi. Consistently?
NORA backend has mostly the same latency for the past 7 days. The 99% is ~350msec, not even close to 4-5 sec.
![image](https://user-images.githubusercontent.com/6473183/177173171-120af02b-3995-428b-b533-7513327b630f.png)

**Comment by Fragmike** [comment]
Hi. Ist still so slow. I switched my router to a newer model, but preferences are ok and normal questions to my google home mini are answered real fast. Only commands for my smarthome are processed so slow. 
Will try to figure out if there is any issue in my system....THNX for the fast response.

greetings Michael

**Comment by andrei-tatar** [comment]
@Fragmike might be that local execution fails for some reason and it takes a few seconds until it falls back to the cloud execution path.

You might want to try disabling local execution

**Comment by Fragmike** [comment]
@andrei-tatar OK. will try this. Got to figure out how to do that ;-)... any link to where I can look up how to do that?
Im using IOBROKER in combination with NodeRed. Wondering what happened. Did not really change my system.
Thumbs up for ur supreme support !!!!

**Comment by andrei-tatar** [comment]
@Fragmike should be under the nora config node options:
![image](https://user-images.githubusercontent.com/6473183/177484198-3f733481-06b3-4172-9785-db3752996e46.png)

**Comment by Fragmike** [comment]
Hi. Found the settings, but I cant disable it. As soon as I Press Update window closes. If I reopen it  it is checked again.
![Nora config node](https://user-images.githubusercontent.com/36605949/177501222-3d0be1b5-190e-4195-bd08-80691a1eb761.png)
.

**Comment by andrei-tatar** [comment]
That's weird. Might be a bug. What version of smartnora package are you running?

**Comment by Fragmike** [comment]
oooohhhh...was on 1.1 alpha updated now but issue is still there.
Got an error message in debug window
Maybe thats the reason?
Triggering node in Nodered will cause switching lamps immediatel
![Screenshot 2022-07-06 165313](https://user-images.githubusercontent.com/36605949/177580158-b465483e-90c3-40b1-8f5c-42bd384aec3b.png)
y

**Comment by Fragmike** [comment]
local execution can be disabled now...but does not fix issue

**Comment by Fragmike** [comment]
Hi. After updating I replaced the old nodes with a new one. Now it works like a breeze. Will have to remove now ALL the other nodes

**Comment by Fragmike** [comment]
OK. Deleted old nora config  and replaced just these in the  settings. All Fine now.

**Comment by andrei-tatar** [comment]
> OK. Deleted old nora config and replaced just this with a new one in the settings. All Fine now. Will start tipoc in Q&A for the rest

Nice to hear! So is it working with local execution as well?
