### ISSUE TITLE
I have an issue while using NORA

### ISSUE THREAD

**Issue by bwesemann** [andrei-tatar/node-red-contrib-smartnora#195]
hi,

i've configured 34 devices in node-red. they are all online. but in my google home app there are only 26 devices and all are offline.
i think this happend because my subscription was suspended. 
in google home i've tried to unlink my account and link it again, but still there are only 26 devices. how can i sync it?

br
ben

My user id is: 8SMuRPYTVIX6BdyTkczRee2jJjF3

**Comment by andrei-tatar** [comment]
@bwesemann Any logs from node-red? Are you sure you created your subscription on the same account you are using in node-red? 

> My user id is: 8SMuRPYTVIX6BdyTkczRee2jJjF3

It seems this user just registered, 1 day ago.

**Comment by bwesemann** [comment]
oh damn, you are right.
