### ISSUE TITLE
Media node gives full payload on change

### ISSUE THREAD

**Issue by keepxtreme** [andrei-tatar/node-red-contrib-smartnora#197]
Hi,
I discovered an issue with the media node (in my case configured as TV). On change via Google Assistent the provided payload contains not only the latest set value but also before set values for all configured triggers. Therefore it's hard to detect which value actually has changed and requieres unnecessary extra steps to detect. Maybe there's an option within the node - if not, would be nice to have it

**Comment by andrei-tatar** [comment]
Hi, that's the pattern for pretty much all of the nora nodes.
Some of them do support "async execution" where you receive the commands and implement the handlers yourself. 
Maybe you can give more details on your use case

**Comment by keepxtreme** [comment]
I'll try to explain: I' currently trying to implement an GA-control for my LG-device which support control by an LG-APP (found nodes for that already). When I'm invoking an action via the googe assistant, all values currently stored in the nora-node will be outputtet. Therefore, at this point, I can't tell, which value on the payload actually has changed and need further processing to get this information. If I don't do further processing, all configured options will be triggered in my flow.

> [{"id":"42ea0e51.56a4b","type":"wake on lan","z":"754ba810.54e698","mac":"C8:08:E9:99:97:7A","host":"192.168.178.255","udpport":9,"numpackets":"","interval":"","name":"turnOn","x":1370,"y":400,"wires":[]},{"id":"a3d18e31.58ca6","type":"switch","z":"754ba810.54e698","name":"","property":"payload['on']","propertyType":"msg","rules":[{"t":"true"},{"t":"false"}],"checkall":"false","repair":false,"outputs":2,"x":990,"y":420,"wires":[["42ea0e51.56a4b"],["84affd86.7b246"]]},{"id":"84affd86.7b246","type":"change","z":"754ba810.54e698","name":"turnOff","rules":[{"t":"set","p":"payload","pt":"msg","to":"turnOff","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":1210,"y":460,"wires":[["ef3874d9.bb5268"]]},{"id":"ef3874d9.bb5268","type":"lgtv-control","z":"754ba810.54e698","tv":"bf372906.b5dfd8","name":"TurnOff","x":1380,"y":460,"wires":[[]]},{"id":"fa28cf44.28bfd","type":"ping","z":"754ba810.54e698","protocol":"IPv4","mode":"timed","name":"kx-smartTV","host":"192.168.178.43","timer":"10","inputs":0,"x":90,"y":420,"wires":[["9105f264.2283d8"]]},{"id":"35c43fd7.6d739","type":"change","z":"754ba810.54e698","name":"true","rules":[{"t":"set","p":"payload","pt":"msg","to":"{}","tot":"jsonata"},{"t":"set","p":"payload['on']","pt":"msg","to":"true","tot":"bool"}],"action":"","property":"","from":"","to":"","reg":false,"x":410,"y":460,"wires":[["96f2867f78874c85"]]},{"id":"9105f264.2283d8","type":"switch","z":"754ba810.54e698","name":"","property":"payload","propertyType":"msg","rules":[{"t":"false"},{"t":"else"}],"checkall":"true","repair":false,"outputs":2,"x":290,"y":420,"wires":[["c6a99e10f1d0a015"],["35c43fd7.6d739"]]},{"id":"1da507bad97ea45d","type":"noraf-media","z":"754ba810.54e698","devicename":"TV","roomhint":"Wohnzimmer","name":"","topic":"","passthru":false,"nora":"1f6dd59a.bacffa","twofactor":"off","twofactorpin":"","filter":false,"deviceType":"TV","supportOnOff":true,"supportVolume":false,"volumeCanMuteAndUnmute":true,"volumeLevelStepSize":"","supportMediaState":false,"supportActivityState":false,"supportPlaybackState":true,"supportTransportControl":false,"transportControlCommands":["PAUSE","RESUME","STOP"],"supportInputSelector":false,"language":"en","mediaInputs":[{"n":"hdmi 1,1st hdmi,TV","v":"hdmi-1","d":true},{"n":"hdmi 2,2nd hdmi,PlayStation","v":"hdmi-2","d":false}],"supportAppSelector":true,"appsLanguage":"de","mediaApps":[{"n":"Netflix","v":"netflix","d":false},{"n":"Youtube","v":"youtube","d":false},{"n":"Prime","v":"lovefilm.de","d":false}],"supportChannel":false,"mediaChannels":[{"n":"CNN,channel 1","k":"ch-1","i":"1"},{"n":"Fox,channel 2","k":"ch-2","i":"2"}],"errorifstateunchaged":false,"asyncCmdOnOff":false,"asyncCmdVolume":false,"asyncCmdTransportControl":false,"asyncCmdInputSelector":false,"asyncCmdAppSelector":false,"asyncCmdChannel":false,"outputs":2,"x":690,"y":420,"wires":[["e9a716134a0411b3","491eeffffd2425e4","32f10dabc1a00a23"],[]]},{"id":"b5b4dcaea65cf0cd","type":"switch","z":"754ba810.54e698","name":"","property":"payload['application']","propertyType":"msg","rules":[{"t":"neq","v":"unknown","vt":"str"}],"checkall":"false","repair":false,"outputs":1,"x":990,"y":560,"wires":[["aa764255e1b0bbbe"]]},{"id":"37dbbe08691c07c4","type":"lgtv-app","z":"754ba810.54e698","tv":"bf372906.b5dfd8","name":"Starte App","passthru":false,"x":1390,"y":560,"wires":[[]]},{"id":"aa764255e1b0bbbe","type":"change","z":"754ba810.54e698","name":"","rules":[{"t":"set","p":"payload","pt":"msg","to":"payload['application']","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":1170,"y":560,"wires":[["37dbbe08691c07c4"]]},{"id":"96f2867f78874c85","type":"rbe","z":"754ba810.54e698","name":"","func":"rbe","gap":"","start":"","inout":"out","septopics":false,"property":"payload","topi":"topic","x":530,"y":420,"wires":[["1da507bad97ea45d"]]},{"id":"e9a716134a0411b3","type":"rbe","z":"754ba810.54e698","name":"","func":"rbe","gap":"","start":"","inout":"out","septopics":false,"property":"payload['on']","topi":"topic","x":850,"y":420,"wires":[["a3d18e31.58ca6"]]},{"id":"491eeffffd2425e4","type":"rbe","z":"754ba810.54e698","name":"","func":"rbe","gap":"","start":"","inout":"out","septopics":false,"property":"payload['application']","topi":"topic","x":850,"y":560,"wires":[["b5b4dcaea65cf0cd"]]},{"id":"c6a99e10f1d0a015","type":"change","z":"754ba810.54e698","name":"false","rules":[{"t":"set","p":"payload","pt":"msg","to":"{}","tot":"json"},{"t":"set","p":"payload['off']","pt":"msg","to":"false","tot":"bool"}],"action":"","property":"","from":"","to":"","reg":false,"x":410,"y":380,"wires":[["96f2867f78874c85"]]},{"id":"32f10dabc1a00a23","type":"debug","z":"754ba810.54e698","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":840,"y":360,"wires":[]},{"id":"bf372906.b5dfd8","type":"lgtv-config","host":"lgwebostv"},{"id":"1f6dd59a.bacffa","type":"noraf-config","name":"smartNora","group":"Standard","twofactor":"off","twofactorpin":"","localexecution":true,"structure":"Zuhause"}]

**Comment by andrei-tatar** [comment]
@keepxtreme The media nodes supports `async execution` for almost all of the traits. That means your node-red flow will receive a command and it's responsible for generating/updating the state. That should fit your use case.
