### ISSUE TITLE
cant verify my email 

### ISSUE THREAD

**Issue by ivishaltejwani** [andrei-tatar/node-red-contrib-smartnora#199]
cant verify my email if I create account via sign in w email

cant use smart nora if I login with google 

My user id is: IMFD6eu236SKmw8SyC83I3tDBcp1

**Comment by ivishaltejwani** [comment]
> @ivishaltejwani Can you please post more details? Are you getting an error? Maybe some screenshots?

On node red (logged in via google) says 
"nora: FirebaseError: Firebase: Error (auth/wrong-password)."

Password is correct quadruple checked

on smart nora website , click to get verification email is not working 
after clicking on button on website to get verification email the page doesnt move to verification mail sent , it stays on same page , and I didnt get any verification email

**Comment by andrei-tatar** [comment]
> On node red (logged in via google) says
> "nora: FirebaseError: Firebase: Error (auth/wrong-password)."

What `node-red-contrib-smartnora` version are you using? When logging in via google in node-red it shouldn't use the password since it's SSO (make sure you haven't entered your google password and that you use the latest package version).

> on smart nora website , click to get verification email is not working
> after clicking on button on website to get verification email the page doesnt move to verification mail sent , it stays on same page , and I didnt get any verification email

Also weird, it shouldn't ask you to verify your email when doing "Sign in with Google" 
![image](https://user-images.githubusercontent.com/6473183/178939535-bd990c15-5297-4ff7-bfec-b981af3b8e12.png)

**Comment by ivishaltejwani** [comment]
> > On node red (logged in via google) says
> > "nora: FirebaseError: Firebase: Error (auth/wrong-password)."
> 
> What `node-red-contrib-smartnora` version are you using? When logging in via google in node-red it shouldn't use the password since it's SSO (make sure you haven't entered your google password and that you use the latest package version).
> 
> > on smart nora website , click to get verification email is not working
> > after clicking on button on website to get verification email the page doesnt move to verification mail sent , it stays on same page , and I didnt get any verification email
> 
> Also weird, it shouldn't ask you to verify your email when doing "Sign in with Google" ![image](https://user-images.githubusercontent.com/6473183/178939535-bd990c15-5297-4ff7-bfec-b981af3b8e12.png)

it is not asking to verify when logging in from google. When logged in via google , In Nodered console I am not able to connect to smart nora with the email and password


When I use Sign in via email , I am unable to verify
![image](https://user-images.githubusercontent.com/57434902/178940071-63636129-2169-4aeb-88a8-8e820f176f82.png)
