### ISSUE TITLE
Sprinkler node 

### ISSUE THREAD

**Issue by mvujica** [andrei-tatar/node-red-contrib-smartnora#201]
Thanks for update on docs but i can't make sprinkler node to function. State is always "not running".
If I set a payload to true, status is "not running", if I set it to payload.on=true than massage appears:
"[Sprinkler1] ignoring property msg.payload.on"
Also the property "Ignore input messages that don't match the topic value" is always reverted back to false.
My user id is: lhsnfOkC7JV0W8wJc9u2CcFn0az1

Can you please check, it behaves differently than light or outlet node?

_Originally posted by @mvujica in https://github.com/andrei-tatar/node-red-contrib-smartnora/issues/184#issuecomment-1185819012_

**Comment by andrei-tatar** [comment]
@mvujica Sorry, I think there's a mistake in the doc. There is no `on` property for the sprinkler. You have to use the `Start/Stop` trait.
![image](https://user-images.githubusercontent.com/6473183/180428647-4485febc-b390-4234-affa-7d3635450b1f.png)
