### ISSUE TITLE
I have an issue while using NORA

### ISSUE THREAD

**Issue by mgugu10** [andrei-tatar/node-red-contrib-smartnora#203]
Hi, I have about 70 connected devices, everything workked for many month. Suddenly for some reason  they stopped synchonisation with google home: Devices are shown offline and of course not responding from google. Everything is OK from the Nora dashboard.
I tried to unlink / relink the nora account from google home but this is impossible, when I try to unlink, I receive "could not reach nora server please try again.
Repeated the operation several times without success.
Thanks for your help

My user id is: 5JmuQE0FgeetM3IjGF2erLJFr3i1

**Comment by andrei-tatar** [comment]
@mgugu10 Everything looks good in the logs and in the DB. All devices are online and no errors logged. Are there any errors in the node-red logs?

Is it working properly now?

I also had a few transient issues last night, but I believe they originated at Google. I asked Google Home to execute some commands and it kept repeating `The light was turned off` over and over again. Maybe they had some sort of issue...

**Comment by mgugu10** [comment]
No, still the same, the devices are **off-line** for google and on-line for Smart Nora.
Unlink/relink Smart Nora still not working (could not reach Smart Nora, try again).
From nodered point of view, everything looks fine, no error in the logs.

**Comment by andrei-tatar** [comment]
@mgugu10 is it possible that you are using different Smart Nora accounts when trying to link in the Google Home app?
The link might fail if the account you're trying to link to has no devices.
I tried myself a few times and it's working fine for me. No errors in the Google Home app. 
Can you provide a screenshot with the Google Home app error? Might be a problem over at Google

**Comment by mgugu10** [comment]
Hi Andrei, I have only one Smart Nora account. Here are my screenshots:

Nora dashboard:
![2022-08-11 09_20_56-NORA](https://user-images.githubusercontent.com/83792053/184089895-92ff4ef3-72e9-4c4b-a533-a95d2087befa.png)

Home control;
![Home control](https://user-images.githubusercontent.com/83792053/184093185-c116e024-00d1-4e14-9e84-e0a427ccc1e6.jpg)


Home control shows 77 devices while Nora shows 78 devices. This because I created a new device in noreded for test and it has not been synchronized by google.
Nodered log for new device:
11 Aug 09:39:30 - [info] Stopping modified nodes
11 Aug 09:39:30 - [info] Stopped modified nodes
11 Aug 09:39:30 - [info] Updated flows
11 Aug 09:39:30 - [info] Starting modified nodes
11 Aug 09:39:30 - [info] Started modified nodes
11 Aug 09:39:40 - [info] nora: Maison - synced 78 device(s)

**Please note that among my 77 devices, 5 are still synchronized and working**. These five devices are the last created few month ago.

When I try to unlink Smart Nora (from the Home control screen) I get **"Could not reach Nora, please try again"**
But when I try to relink I get this;

![Screenshot_20220811-090502_Samsung Internet](https://user-images.githubusercontent.com/83792053/184093264-3dbac76c-7eef-419b-80d4-eaf1b266129d.jpg)

Relink process seems to finalize  (without asking me for credentials), but problem remains, **only 5 devices among 78 are synchronized**.

**Comment by mgugu10** [comment]
Hi Andrei, everything worked again this morning.
Did you do something from your side ?
What do you think the reason could be for suspending the service during 3 days?

**Comment by andrei-tatar** [comment]
@mgugu10 I haven't changed anything but that `5 devices` synced seems to indicate that, for some reason, NORA was thinking you don't have an active subscription on your account. I will try to investigate the logs. Might've been something related to the stripe integration.
