### ISSUE TITLE
Constantly getting HTTP 502 after upgrading to 1.15.0

### ISSUE THREAD

**Issue by osvedman** [andrei-tatar/node-red-contrib-smartnora#205]
This started happening after upgrading to Smart NORA 1.15.0. Keeps on happening every minute.

Node-RED 3.0.2
Node 14.18.3
Raspberry Pi 4

My user id is: t7WJolzaFqMUs6VFcvFzRNi2qnF2

`nora: <default> - unhandled error (trying again in 53.65 sec): HTTP response (502)
    at FirebaseSync.doHttpCall (/home/pi/.node-red/node_modules/node-red-contrib-smartnora/build/nora/sync.js:238:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)...`

**Comment by Hjorth-Jensen** [comment]
I have the samme problem

**Comment by andrei-tatar** [comment]
@osvedman / @Hjorth-Jensen  is this still happening? or was it transient? I don't think it's related to the version

**Comment by osvedman** [comment]
Yeah, still happening. All I know is it started happening immediately after a Node-RED restart after upgrading Smart NORA, and I did not have this problem before then.

A 5xx error indicates an issue on your server, so perhaps you'll find more info in your server logs for Smart NORA?

**Comment by andrei-tatar** [comment]
Yup, looking into it.

**Comment by andrei-tatar** [comment]
@osvedman Can you please try again with `v1.15.1`? I think the problem was the lack of compression on the request body.

**Comment by kreiseder** [comment]
Solved the problem for me! Thanks!

**Comment by osvedman** [comment]
Yep, confirmed from me as well. Thank you!
