### ISSUE TITLE
Migration help from Nora to Smart nora?

### ISSUE THREAD

**Issue by ronsmits** [andrei-tatar/node-red-contrib-smartnora#21]
Evening

I have been using Nora for some time and I am generally satisfied. Is there a guide or something to move from Nora to smart nora? I think the following steps need to be done, but I would like some confirmation about that:

1. unlink Nora from google home
2. uninstall the Nora contrib from node-red
3. follow the new guide

Ron

**Comment by andrei-tatar** [comment]
Hi,

Those are the steps. Though the new system has nothing to do with the old one. You can remove the old after you added the new.

Cheers

**Comment by ronsmits** [comment]
thanks for the confirmation. A think to note is that you have to delete all the old nora nodes before you can uninstall the old nora. After that you can use the new setup.
