### ISSUE TITLE
I have an issue while using NORA

### ISSUE THREAD

**Issue by polarix2017** [andrei-tatar/node-red-contrib-smartnora#212]
I'm not able to pay your fee for premium account with my card.
Can you help me ?

My user id is: ZqLukZUqU9hI8xe6bYI2Jg9YP7v1

**Comment by andrei-tatar** [comment]
@polarix2017 sorry for the inconvenience. Stripe says your bank declined the payment and to contact the bank.
Here's all I could find:

![image](https://user-images.githubusercontent.com/6473183/195646565-59f7eca7-aff5-4686-8dd0-852120a3811e.png)

![image](https://user-images.githubusercontent.com/6473183/195646907-b4ead23d-152b-451e-a1d7-3f587b973211.png)
