### ISSUE TITLE
Doorbell

### ISSUE THREAD

**Issue by Jozef73** [andrei-tatar/node-red-contrib-smartnora#214]
Dear Andrei,

I can't trigger Doorbell in my phone to show notifications in Google Home App.
Sending payload from NodeRed (as your example) don't work, successfuly injected.
Voice notification is turned ON and Doorbell assigned in my house/room.
Doorbell presented in GH.

Any advice?

thank you

jozef

**Comment by FireWizard52** [comment]
Hi,

Try to Inject beside the payload a msg.topic = ObjectDetection.

Regards

**Comment by andrei-tatar** [comment]
@Jozef73 I'm not sure if you can get the notifications on your phone. As far as I know if works only on Google Home speakers or smart displays.

If you want to get notifications on the phone, you can use the `notify` node.

![image](https://user-images.githubusercontent.com/6473183/196117149-57f65086-9e5b-4eb3-a11d-a88bfbfcdf70.png)

**Comment by FireWizard52** [comment]
@Jozef73,

I just realized now that your question applies to receiving notifications in your Google Home app on your smartphone.
I thought that it concerned the notification on a Google Home speaker.

Ignore my previous comment.

Regards

**Comment by Jozef73** [comment]
Dear Andrei,

notify node works well, but I need Google Home app (mobile) notifications from Doorbell created by NodeRed.

I tried to inject msg.topic = ObjectDetection, it also not works.

![Picture1](https://user-images.githubusercontent.com/96684879/196237491-a11c081b-4988-4b50-a0b6-00bf4ee1241c.png)

On developer Google home there some description, but I think your node is constructed differently.
{
  "ObjectDetection": {
    "objects": {
      "named": [
        "Alice"
      ]
    },
    "priority": 0,
    "detectionTimestamp": 946684800000
  }
}

I think I should be able to receive notfication from NodeRed/Doorbell.

Thank you
jozef

**Comment by andrei-tatar** [comment]
@Jozef73 as I said, you will not receive doorbell notifications on your phone.

## [Notifications for smart home Actions](https://developers.google.com/assistant/smarthome/develop/notifications)
> Google Assistant provides these notifications to users as announcements on smart speakers and smart displays. Proactive notifications are turned off by default. Users have the ability to turn on or off all proactive notifications from the [Google Home app](https://play.google.com/store/apps/details?id=com.google.android.apps.chromecast.app).

So you will only get announcements on your smart speakers and smart displays. Not phone!
