### ISSUE TITLE
Device not available from google voice command, device offline from nora

### ISSUE THREAD

**Issue by xselvasx** [andrei-tatar/node-red-contrib-smartnora#218]
As required in the discussion i open an issue 
When i deploy the project in node-red i see in smart-nora.eu all device online but after less than 1 minute everithing became offline, sometimes return online for 10-15 seconds but after return offline; but in node-red seems to be connected. when i try to switch on a light from google voice command it said that the light is not available.

My user id is: R7QdJlrhCXTP1yjORl4AxChe85I2

**Comment by andrei-tatar** [comment]
@xselvasx Hey, I had a look through the logs. What system are you running this on?
It seems like the system time on your local instance of node-red is not correct. It seems to be off by about 5 hours, 30 mins.

To explain a bit:
NORA detects if devices are online by checking the heartbeat timestamp sent by your node-red instance.  If that timestamp is not older than a minute, then the devices are online and your node-red instance is communicating with the server correctly.

In your case the difference is way over 1 min.

**Comment by xselvasx** [comment]
i use nodered in a docker container, and the timestamp is correct for my timezone [UTC+1].
i forced the NTP sync with the time server and now seems to be fixed. 
probably there was a clock drift in my device.
thank you very much
