### ISSUE TITLE
I have an issue while using NORA

### ISSUE THREAD

**Issue by FoxConsult** [andrei-tatar/node-red-contrib-smartnora#219]
Hello,

I have 5 devices and my setup has been running for a long time without any problems. I few days ago, my accout at https://smart-nora.eu/my-nora show all devices as "offline".

My user id is: tkKbJxjQtGdEEceZzAuBMVQwRcy2

/Tommie

**Comment by andrei-tatar** [comment]
Hello,

This might be related: #218
@FoxConsult can you if the device you're running on has the correct date/time set?

**Comment by FoxConsult** [comment]
Hi Andrei,

My Raspberry Pi was of by 5 minutes. NTP settings are now corrected and Smart Nora now works fine.

Thank you!

/Tommie
