### ISSUE TITLE
Local execution not working

### ISSUE THREAD

**Issue by nicandris** [andrei-tatar/node-red-contrib-smartnora#220]
Hey, I updated on  the latest version (1.17.1) a couple of days  ago and lost local execution or at  least the status icons  are not turning blue. Anyone else experiencing the same?

**Comment by andrei-tatar** [comment]
@nicandris just checked and it's working fine for me (node status turns blue). 
Is there a s;eck

**Comment by andrei-tatar** [comment]
Do you have secondary verification enabled on any of the devices?
What is your user id?

**Comment by nicandris** [comment]
Looks like I somehow (i dont remember getting in there for ages! 😂 ) enabled two-factor - `acknowledge`.
I've set it back to `Node` but its still not turning blue. I can see this though in the logs now

8 Nov 18:13:17 - [trace] [nora][local-execution] Received discovery packet, sending reply
8 Nov 18:13:23 - [trace] [nora][local-execution] Received discovery packet, sending reply
8 Nov 18:13:30 - [trace] [nora][local-execution] Received discovery packet, sending reply
8 Nov 18:13:43 - [trace] [nora][local-execution] Received discovery packet, sending reply

**Comment by nicandris** [comment]
uid: feBejB5TPddLJU9Sy5YiCFMeHqt1

**Comment by nicandris** [comment]
@andrei-tatar it's working now, not sure what happened or what I did... 🤷 I'll close this, thank you for checking into it 🙇
