### ISSUE TITLE
I have an issue while using NORA

### ISSUE THREAD

**Issue by Geran247** [andrei-tatar/node-red-contrib-smartnora#223]
Describe the problem here...
Mein Nora Account verbindet sich nicht mehr mit meinem neu Aufgesetzten Node Red.
Bitte kannst du mir weiterhelfen.

Grüße Geran

My user id is: IkRJ1sJ0BqMkwqwaJfEwBlArQ8u1

**Comment by andrei-tatar** [comment]
@Geran247 Any relevant messages in the node-red logs?

**Comment by Geran247** [comment]
Vielen Dank für die Rückmeldung.
Ich habe mein Node Red frisch aufgesetzt und habe dann alle Gruppen gelöst und jetzt kann ich es nicht mehr verbinden.
Wie kann ich mich wieder anmelden?

**Comment by andrei-tatar** [comment]
@Geran247 Have you tried following the steps from the guide? Which step doesn't work?
Any error logs in node-red. What device are you running node-red one? Is the time set correctly?

**Comment by Geran247** [comment]
Ja ich habe alle Schritte genau so durchgeführt.
Das einzige was nicht funktioniert ist das ich den E-Mail Link schon benutzt ist.
In Node red sehe ich das ich 35Geräte in gebrauch habe aber auf der Hompage NORA sehe ich keine Verbindung.
Node red läuft auf einem Raspberry Pi4 auf rasbian.

**Comment by andrei-tatar** [comment]
@Geran247 Is it possible that you created different user accounts for different email addresses?
Try logging in again in node-red with the same authentication method you are using on smart-nora.eu
Also, make sure you have the latest version of `node-red-contrib-smartnora` installed in node-red.

**Comment by Geran247** [comment]
Nein ich verwende nur eine E-Mail Adresse.
Habe Node Red contrib smartnora ganz frisch installiert.
ich denke das es keine Verbindung gibt von smartnora zu node red

**Comment by andrei-tatar** [comment]
Is the internet working on the Raspberry Pi?
If you're running node-red as a service, you can try viewing the last 200 lines of the log with `journalctl -u nodered.service -f -n 200` . There might me something relevant in there.
