### ISSUE TITLE
Camera URL

### ISSUE THREAD

**Issue by T1mey** [andrei-tatar/node-red-contrib-smartnora#224]
I got a DLink camera and try to use the camera with Google Assistant and your node...
Not sure if that will work out.

I can only get the stream with those URL / media formats... any change to bring that 2gether with the node ?

JPEG:

http(s)://benutzername:passwort@ip_der_kamera/image/jpeg.cgi
bzw.
http(s)://benutzername:passwort@ip_der_kamera/image/jpeg.cgi?profileid=1

MJPEG:

http(s)://benutzername:passwort@ip_der_kamera/video/mjpg.cgi
bzw.
http(s)://benutzername:passwort@ip_der_kamera/video/mjpg.cgi?profileid=1

RTSP:

rtsp://benutzername:passwort@ip_der_kamera/live1.sdp
bzw.
rtsp://benutzername:passwort@ip_der_kamera/play1.sdp

**Comment by andrei-tatar** [comment]
@T1mey I never got to playing around with the camera streams. Not 100% sure, but I think it needs to be a public ip/host name.

**Comment by andrei-tatar** [comment]
Btw, I do plan to install some cameras for myself in the next few months and I will play around with adding them to Google Home.

**Comment by andrei-tatar** [comment]
@T1mey ah, the question is more about the codecs. No, there's no chance I can change the video codec.
You can use something like this: https://github.com/deepch/RTSPtoWebRTC to transcode to something supported by Google Home.

**Comment by T1mey** [comment]
Which codecs are supported by google ? I can choose between h.264 and mpeg...
Question is if this is working in my local network or if the URL must be accessable over the internet.

If yes maybe it's maybe worth changing the camera to another model which is supported by google out of the box.

**Comment by andrei-tatar** [comment]
These are the supported stream protocols:
https://developers.home.google.com/cloud-to-cloud/traits/camerastream#streaming%20protocols

> Question is if this is working in my local network or if the URL must be accessible over the internet.

No idea. The documentation doesn't specify it explicitly. I personally haven't tried yet.

**Comment by T1mey** [comment]
> These are the supported stream protocols: https://developers.home.google.com/cloud-to-cloud/traits/camerastream#streaming%20protocols
> 
> > Question is if this is working in my local network or if the URL must be accessible over the internet.
> 
> No idea. The documentation doesn't specify it explicitly. I personally haven't tried yet.

Note: CameraStream is not currently supported by [local fulfillment](https://developers.home.google.com/cloud-to-cloud/concepts/local).

Link is not reachable... seems it's called local fullfillment

Would be interested which devices are supporting local fullfillment.... Searching for some power plugs which can do that....

**Comment by andrei-tatar** [comment]
Local fulfilment is related to something else, not the camera stream url.

It's the ability to receive commands/queries from a Google home device directly to the node-red instance, not via the cloud path.

Pretty much all devices support local fulfilment.

**Comment by T1mey** [comment]
> Local fulfilment is related to something else, not the camera stream url.
> 
> It's the ability to receive commands/queries from a Google home device directly to the node-red instance, not via the cloud path.
> 
> Pretty much all devices support local fulfilment.

Is it possible to use that feature in smart nora soehow ?

**Comment by andrei-tatar** [comment]
Yes, it's already supported and enabled by default for the devices that support it.
You can read more about it here:
- https://developers.home.google.com/local-home/overview
- https://github.com/andrei-tatar/node-red-contrib-smartnora/tree/master/doc/faq#how-does-local-execution-work

**Comment by T1mey** [comment]
> Yes, it's already supported and enabled by default for the devices that support it. You can read more about it here:
> 
> * https://developers.home.google.com/local-home/overview
> * https://github.com/andrei-tatar/node-red-contrib-smartnora/tree/master/doc/faq#how-does-local-execution-work

Wow... sounds great... I'm using Homematic (IP) devices .... and the delays between commands are quite huge (2-5 seconds) .

**Comment by andrei-tatar** [comment]
@T1mey please note that the latency between Google and node-red is at a minimum (in my case ~500msec). Not sure how you interface with the Homematic devices from node-red, but it might add up.

**Comment by T1mey** [comment]
> m node-red, but it might add up.

Thanks for the clarification ... the status is blue in my case... so as I understood it right,,,, the call is not leaving my LAN right ?

**Comment by andrei-tatar** [comment]
Yes, it means the devices receives the commands via local fulfilment path.
However there still is a status update send to the cloud since Google Home only supports cloud queries. So when you open Google Home and Google queries what's the status for all the devices, that call goes only to nora, not to your LAN.

**Comment by FireWizard52** [comment]
Hi, @T1mey.

Following your discussions, as I do also own DLink camera's. Unfortunately older model, DCS930L.

What is your intended use, as I only can image that you want to give a voice command and then that your camera stream is displayed on a Google Nest Hub or a Max. 
I have never been able to realize that, but used some work around with CATT (Cast All The Things) and a support program 
mqtt-launcher.  This solution is posted at the Domoticz forum (as I use Domoticz).

You may want to look at that: https://www.domoticz.com/forum/viewtopic.php?f=38&t=30644&p=233183#p233183

At the end this program will run DashCast on the Google Nest Hub and display your video stream (or any other website) to the Nest Hub. Several alternative methods are available, with might be easier, but that will depend on your personal setup.

I would also prefer that a camera stream is played on the Nest hub, without CATT and/or MQTT Launcher.

Regards

**Comment by T1mey** [comment]
> gle Nest Hub and display your video stream (or any other website) to th

@FireWizard52 
Yes, that's what I want to do...
Must your cam be reachable ober the internet?

I think I do not want to have a process running for convserion and I will switch to another cam...

**Comment by FireWizard52** [comment]
Hi @T1mey,

You asked:

> Must your cam be reachable ober the internet?

No, my cams are not reachable from the Internet. I'm able to create a VPN to my local network and it that case I can view the camera stream on my phone, tablet, etc. I do not want that everybody can look into my house.
My camera's and the Google Nest Hub are on the same private LAN, which is not accessible from the Internet.
