### ISSUE TITLE
Which device has been triggered

### ISSUE THREAD

**Issue by BreizhCat** [andrei-tatar/node-red-contrib-smartnora#225]
Hello,

First of all thanks for your work. 
I'm wondering if there is a way to determine which device has been triggered (Google Hub, Nest ...) to be able to return feedback on the correct device ?

Today in my node-red I have put the IP of the main device (in kitchen). But if I ask to google something in another room, the feedback is currently sent to the kitchen. Is it possible?

Thanks

**Comment by andrei-tatar** [comment]
Hello @BreizhCat,
Unfortunately there's no way, right now, to know the device the command came from.
Keep in the mind the command can come from other places as well, not only from a google home device.

Related issue
s: #188

**Comment by BreizhCat** [comment]
Argh yes ! Thanks for your feedback.
