### ISSUE TITLE
I have an issue while using NORA: Installation

### ISSUE THREAD

**Issue by whabby** [andrei-tatar/node-red-contrib-smartnora#226]
Node Red ist running on a Raspberry 4.
My steps:

- Updating Node Red with the command: bash <(curl -sL https://raw.githubusercontent.com/node-red/linux-installers/master/deb/update-nodejs-and-nodered) --node18 
![Screenshot1](https://user-images.githubusercontent.com/30371694/205102111-50a5b4ba-3a60-4f1d-b0f4-3fbe4201bab6.png)
- After reboot I tried to install Smartnora, but installation failed
![Screenshot2](https://user-images.githubusercontent.com/30371694/205102282-9461be6e-77f2-44ff-b332-a0ee4421d54e.png)

What could be the reasons? Thanks for help!

My user id is: age3mXh5h5Yj9J036kHSjYRAK5U2

**Comment by andrei-tatar** [comment]
Hi @whabby,
It seems you are still running node 10. You can verify that by running `node -v` in a shell.
