### ISSUE TITLE
I have an issue while using NORA

### ISSUE THREAD

**Issue by bladebikkel** [andrei-tatar/node-red-contrib-smartnora#227]
Dear,

I have an offline device in Nora which I can not remove.
I can not find it in my node red configuration and I do not know how to remove it.

The device is in the room: Slaapkamer Fabian
and it is named: Rolluik Fabian

Can you please help me with removing this offline device?
Thank you very much!

regards,
Edwin Pastoor

My user id is: EZF5ig1jHAg7BfglMrZbwHt1wMU2

**Comment by andrei-tatar** [comment]
Hello Edwin, 
It seems like you have a group that you are not using.
You should be able to remove it by going to https://smart-nora.eu/my-nora/groups select the one you want to delete `Test92` and click on the red bin icon.
![image](https://user-images.githubusercontent.com/6473183/205592955-51af6b4e-98e3-469a-8504-6fd6659ba891.png)

Let me know if you are having any issues.

Andrei T.

**Comment by bladebikkel** [comment]
Wow! that was a really fast answer and fix! 
I did not know there was a separate group and it worked deleting it! thank you!!

**Comment by andrei-tatar** [comment]
You are welcome!
