### ISSUE TITLE
I have an issue while using NORA

### ISSUE THREAD

**Issue by phguk** [andrei-tatar/node-red-contrib-smartnora#228]
First time user with Nora & Code Red so please bear with me. 

I want to integrate a Sonoff S26R2 socket which I've flashed with Tasmota to Google Home. Nora can successfully see and control the socket. I'm struggling to get Google Home to find the device. With only one device, I don't have an active NORA subscription.

When I try to "set up a new device" using Google Home, I select "Works with Google", search & find "Smart NORA". It takes me to smart-nora.eu and I sign in with my Google credentials. Briefly I see nora-firebase.firebaseapp.com then I'm presented with a blank screen headed smart-nora.eu (see below). 

Any idea what I'm doing wrong ? Thanks Paul 

![Screenshot 2022-12-09 at 09 42 55](https://user-images.githubusercontent.com/104507061/206672878-a916cdaf-3cd3-479d-b818-a020b71b61c1.jpg)

My user id is: dIRSL4WjokcB2WPQocoE4NuFBGD3

**Comment by andrei-tatar** [comment]
@phguk Is that an iPhone? I admit I never tested it with an iPhone personally. 
Have you managed to get it working?

I would try logging in from Safari first (by going to https://smart-nora.eu/my-nora) on that iPhone. I think Safari has a weird security thing where it doesn't store cookies unless a site is first visited or something like that.

Let me know if that does it.
