### ISSUE TITLE
I have an issue while using NORA

### ISSUE THREAD

**Issue by gitk9jm** [andrei-tatar/node-red-contrib-smartnora#229]
Describe the problem here...

My user id is: M1amS0VOlsfF7lsUsLtnx7Jkksu1

Smart-Nora is off line on Android devices, but show up on https://smart-nora.eu/my-nora

**Comment by andrei-tatar** [comment]
@gitk9jm I checked the DB and the logs and everything appears to be working fine for that user id.
Is the issue still present?
