### ISSUE TITLE
Problem with connect account Google Home

### ISSUE THREAD

**Issue by LukaszZdunek** [andrei-tatar/node-red-contrib-smartnora#230]
Hi,

I'm have a problem with link my nora account to google home app.

I have this error:

![Screenshot](https://user-images.githubusercontent.com/53077569/207404046-8b17efc2-bb44-4c95-b229-b0198c4e9151.jpg)

Thanks for help!

My user id is: e3NUO5Vjjuc5Gaa9wrBVqfcu60J3

**Comment by andrei-tatar** [comment]
Hi @LukaszZdunek 
Is this still happening. I'm looking through the logs, but can't find anything relevant.
Are you using the same account when linking in Google Home?
