### ISSUE TITLE
I have an issue while using NORA

### ISSUE THREAD

**Issue by myozone** [andrei-tatar/node-red-contrib-smartnora#231]
Describe the problem here...
Hello, Just starting getting this error rin Node-red
`Error: HTTP response (404 {"description":"device missing","id":"85592c6db0a2bb3d"})`

My user id is: LnZYV6ZBmDZFHoteX8fp5Txns063

**Comment by andrei-tatar** [comment]
@myozone Do you have multiple instances of node-red connecting to the same nora account?

**Comment by myozone** [comment]
I did, now just the one. I was my test VM which I've deleted.

**Comment by myozone** [comment]
Ah ok, thank you, I'll give it go.
