### ISSUE TITLE
Temperature of sensor not showing in Google home app

### ISSUE THREAD

**Issue by FrankX0** [andrei-tatar/node-red-contrib-smartnora#232]
When using the sensor node the temperature is not shown in the Google home app.
When supplying both temperature and humidity data, only the humidity data is shown in the app.
Both the temperature and humidity data are shown in Node-RED below the node.
And they are also shown in https://smart-nora.eu/my-nora.
node-red-contrib-smartnora version 1.17.2

**Comment by FireWizard52** [comment]
This is not supported by Google. You can ask for it and then you will get a voice response.
But is is not displayed in the app

**Comment by FrankX0** [comment]
OK, thanks.
Weird though that the humidity level is supported.

**Comment by andrei-tatar** [comment]
@FrankX0 Humidity showing up in the google home app is pretty recent (I think it was added in the last 6 months or so)
