### ISSUE TITLE
Sensor not showing temperature

### ISSUE THREAD

**Issue by SampusCZE** [andrei-tatar/node-red-contrib-smartnora#233]
Hi,
im using sensor node for my DYI meteo station, it was working fine, but lately im only getting humidity data showing in google home and no temperature. In node info status is temperature showing corectly(T:-11.8C H:84%) but in google home is showing only 84% humidity. Maybe problem with negative values? 

Thanks for any ideas.

**Comment by andrei-tatar** [comment]
Hi @SampusCZE,
It never showed the temperature for me and the humidity is a pretty recent thing (I think at the beginning of the year).
Either way, the way it displays in Google Home is not under our control. It's completely on Google.

**Comment by andrei-tatar** [comment]
Duplicate of #232

**Comment by SampusCZE** [comment]
It's weird, even nest hub is trying to show it. Will see what will Google do with this.

![IMG_20221218_151855](https://user-images.githubusercontent.com/46657128/208303585-3381b2c6-f9cf-45f3-ba73-fb0647beb63e.jpg)

**Comment by andrei-tatar** [comment]
@SampusCZE if you ask it what's the temperature or the humidity, it answers correctly
