### ISSUE TITLE
cant link account in smart nora

### ISSUE THREAD

**Issue by ivishaltejwani** [andrei-tatar/node-red-contrib-smartnora#236]
Getting this error when connecting to  google accounts in nodered

<img width="1117" alt="Screenshot 2022-12-29 at 8 48 35 PM" src="https://user-images.githubusercontent.com/57434902/209974012-d5d1b28a-d71e-4645-bc7c-4500311813ac.png">

**Comment by andrei-tatar** [comment]
Hey @ivishaltejwani 
What was the solution to your problem?
