### ISSUE TITLE
Local fulfillment (local execution) not working

### ISSUE THREAD

**Issue by FireWizard52** [andrei-tatar/node-red-contrib-smartnora#238]
Hello @andrei-tatar 

I tested one Switch but concluded that local-execution does not work.

More messages, e.g. "node-red-contrib-google-smarthome", are reporting the same
See: https://github.com/mikejac/node-red-contrib-google-smarthome/issues/348

Also the guys at Nabu Casa, who are  resposible for the Home Assistant implementation have similar problems.

There are a number of posts, reporting that local-execution stopped working, after the Google devices received a firmware update,

My questions are:

1. Have you got similar messages from SmartNora users?
2. Can you check this in your logs?
3. If so, are there indications of a possible cause.

I hope you can give some answers.

My (old) user id is r53vj694TYgtSWAQKsDVaCZJJgk1.

I wish you a happy New Year and Regards.

**Comment by andrei-tatar** [comment]
Hey @FireWizard52 ,
It seems like it's not working for me as well. It discovers the local devices but no `EXECUTE` intent is sent via local fulfillment. 
I suspect Google disabled it for some reason temporarily (maybe something to do with security) or might be just a bug.

I'll keep an eye out. Maybe they'll update us after the holidays.

Happy new year!

**Comment by FireWizard52** [comment]
Hi, all

According to https://github.com/NabuCasa/home-assistant-google-assistant-local-sdk/issues/28 (latest post) a fix is currently rolled out. We have to have a little more patience, before our devices will get it.

Regards

**Comment by andrei-tatar** [comment]
Thanks for the update, @FireWizard52 !

**Comment by FireWizard52** [comment]
Hello @andrei-tatar,

It looks that local fulfillment is working again. Do not know, exactly, when it recovered, but I see a blue dot again under the SmartNora device. Do not know, if it is stable at the moment, so I keep an eye on it. If you feel that it is working for you as well, the topic can be closed.

**Comment by andrei-tatar** [comment]
@FireWizard52 nice, thanks for the update!
It's still not working for me, so I guess I'll keep waiting for the deployment.

**Comment by FireWizard52** [comment]
@andrei-tatar 

Local fulfillment stopped working again.

**Comment by chicaneau** [comment]
I'm seeing the same problem, i have plenty of REACHABLE_DEVICES messages, all of which contain the devices array with a list of my hass devices including the custom_data>uuid, webhookid and httpport variables.

There doesnt seem to be anything i can do to resolve it. when i make a voice request on a google home it just says sorry that device isnt available. I've checked wireshark and it shows no attempt by the google home to contact hass on the local IP.

Google Home Mini and Google Home Firmware: 1.56.324896
HASS version: 2023.2.1

**Comment by gaaat98** [comment]
> I realise this is a node-red discussion, but im seeing the same problem in Home Assistant still, even though supposedly google resolved the problem. i have plenty of REACHABLE_DEVICES messages, all of which contain the devices array with a list of my hass devices including the custom_data>uuid, webhookid and httpport variables.
> 
> There doesnt seem to be anything i can do to resolve it. when i make a voice request on a google home it just says sorry that device isnt available. I've checked wireshark and it shows no attempt by the google home to contact hass on the local IP.
> 
> Google Home Mini and Google Home Firmware: 1.56.324896 HASS version: 2023.2.1

The issue has been fixed apparently only on Fucsia OS devices (Nest Hub), not Cast OS devices (Home Mini and Nest Mini), I suggest you to +1/comment on this issue directly on Google's issue tracker,: https://issuetracker.google.com/issues/261893570
Maybe more people reporting to be affected could help increasing the priority of the issue...

**Comment by FireWizard52** [comment]
Hi all,

Google reports:

> Please expect the fix to be in the 1.56.5.XXXXX version around mid-May.

I do not repeat the comments of some users in the Google Issue Tracker.
You may guess.

Regards

**Comment by andrei-tatar** [comment]
Hopefully they are not leaving Google Home behind again. After they did quite some nice progress on the UI.

**Comment by FireWizard52** [comment]
Probably there will  be no news before mid May.

**Comment by andrei-tatar** [comment]
@FireWizard52 Local execution started working for me today.

**Comment by gaaat98** [comment]
@andrei-tatar can you please tell me the firmware of your google device(s) and if they are Nest Mini or Home Mini? Thanks a lot!

**Comment by gaaat98** [comment]
According to the issue on google's issue tracker, local fullfillment should have been fixed on the Nest Hub (if running FucsiaOS) in February, while there is no news for the others... If you have time could you please test local fulfillment with only one device on at a time? Just to understand which devices have local fullfillment working and which don't, since apparently google can't be trusted on this

**Comment by FireWizard52** [comment]
Hi all,

According to the Google issue tracker it should be solved in Google Cast version 1.56.5.XXXXX
That version should have been released mid-may, but as expected (sorry for my criticism), it did not happen.

I own a Google Nest Hub with software:  10.20221207.2.109 Firmware Cast: 1.68.353511
And also two google Nest Mini's with software: 1.56.348702
Sometimes, I see that local fulfillment is working, especially when I use the Nest Hub. That make sense, as this device has already the Fuchsia OS. 

I do not see local fulfillment, yet., but noticed that the layout of the Google Home app has changed.

Regards

**Comment by FireWizard52** [comment]
Hi all,

(Finally) I received an update for my Google Nest Mini. They are now on Firmware version 356012 and the firmware of Cast is 1.56.356012. Local fulfillment is not working spontaneously, but after giving the command "force local" I see  that local fulfillment is working again.

The firmware indication does not match with the indications at: https://support.google.com/googlenest/answer/7365257?hl=en#zippy=%2Ccurrent-production-firmware-version
It indicates 1.56.356012 instead of 1.56.5.356012. (The 5 is missing), but I think, that this is the version, we should expect.

Regards.
