### ISSUE TITLE
Smart-Nora making my container running node red crash

### ISSUE THREAD

**Issue by Ivanbk** [andrei-tatar/node-red-contrib-smartnora#24]
I recently tried Smart Nora, added the light node with RGB support(HSV), connected it to a debug node, and the node red server never started again, and says the following error:

![image](https://user-images.githubusercontent.com/33582328/116418103-d401ec80-a809-11eb-83fc-1f75fbf09f7d.png)

**Comment by andrei-tatar** [comment]
Probably a bug. Will have a look.
- What version of `node-red-contrib-smartnora` are you using?
- Which color model are you using `HSV` or `RGB`?

**Comment by Ivanbk** [comment]
I am using HSV, and I don't know how to check the version, i am pretty new in docker.

**Comment by andrei-tatar** [comment]
@Ivanbk  I checked the code and this issue seems to have been fixed a long time ago (over a month).

This is how you check the version Click Menu/Manage Palette/Check package version:
![image](https://user-images.githubusercontent.com/6473183/116606510-82f11600-a939-11eb-8366-679331d14f62.png)

**Comment by Ivanbk** [comment]
I'm so sorry for the inconvenience, thanks for the help. My only issue is a cannot start the node red container, so I can't delete it. I'm stuck in a loop of crashes, I tried deleting the Node with the command line, but the crashing doesn't let me. Is there any way I can get my Node-Red Container back up and running without deleting it completely?

**Comment by andrei-tatar** [comment]
What is your user id? https://smart-nora.eu/my-nora

**Comment by Ivanbk** [comment]
hfZPTEgfigZsrYF1OK5b1d6ftRO2

**Comment by andrei-tatar** [comment]
Try deleting your group: https://github.com/andrei-tatar/node-red-contrib-smartnora/blob/master/doc/faq/README.md#i-have-ghost-devices-in-my-google-home-application

And starting the container again.

**Comment by andrei-tatar** [comment]
@Ivanbk is your problem solved?

**Comment by Ivanbk** [comment]
Yes, thanks a lot for the help and plugin. Keep up the good work Andrei. I want to be as knowledgeable someday.
