### ISSUE TITLE
I have an issue while using NORA

### ISSUE THREAD

**Issue by mattheijer** [andrei-tatar/node-red-contrib-smartnora#241]
Describe the problem here...

My user id is: suMqVf7p00QvPvHEqS4InixIxna2

i get an error:

"nora: Error: certificate is not yet valid"

how can i fix this ?

**Comment by andrei-tatar** [comment]
@mattheijer most likely the system you are running node-red on doesn't have a valid date/time set.

**Comment by andrei-tatar** [comment]
@mattheijer do other internet related things works on the machine? Especially via SSL.
