### ISSUE TITLE
Google home doorbell not working

### ISSUE THREAD

**Issue by RickRiet** [andrei-tatar/node-red-contrib-smartnora#245]
I made a doorbell node and added it to my living room. There is a google mini speaker an a nest hub there. I imported the example and added the objectdetection as described in another issue. I turned on notify in the google doorbell inside google home. I tried multiple inputs but no notification is coming thru. What am i doing wrong?

My user id is: uF4HL9LH7CQVQOnqakf3VAYb65H2

**Comment by andrei-tatar** [comment]
Hi @RickRiet , anything relevant in the node-red logs?
I will try to have a look today or over the weekend.

**Comment by andrei-tatar** [comment]
@RickRiet I just tested it and it works fine for me. 
Are you sure you assigned the Doorbell to your Home, in a room, in Google Home app?

**Comment by andrei-tatar** [comment]
Also, do you have the notifications enabled on your Google Home speaker? 
![Screenshot_2023-02-03-15-18-51-40_2d2bd67b5e15ae98c151ac739cd6881e](https://user-images.githubusercontent.com/6473183/216613483-4d43cafa-d9e6-439c-b4a4-b2281de7d4d2.jpg)

**Comment by RickRiet** [comment]
![image](https://user-images.githubusercontent.com/76628445/216847332-e1dd114a-2121-4989-84da-8a9c19512ac1.png)

**Comment by andrei-tatar** [comment]
@RickRiet I can't find anything wrong. Can you paste the flow you're using, or it's just the sample flow from the docs?

**Comment by andrei-tatar** [comment]
@RickRiet What is the data from the 1st post? cam you post your flow?

**Comment by RickRiet** [comment]
Ok updating fixed the issue i feel really stupid now sorry for the time you put in.

**Comment by andrei-tatar** [comment]
@RickRiet no worries. Glad it's sorted! It was probably a bug in the older versions.
