### ISSUE TITLE
Homeassitant addon nodered cant install smart nora

### ISSUE THREAD

**Issue by nivekamoud** [andrei-tatar/node-red-contrib-smartnora#247]
Cannot install Smart nora in the addon of Homeassitent Nodered. 
See below i dont no what the problem is why i have to use  DEV.
maybe you can help me solve this issue.

_**8:08.819Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-contrib-smartnora@1.18.1
2023-02-24T11:28:35.296Z [err] npm WARN config production Use `--omit=dev` instead._**

gr kevin

**Comment by andrei-tatar** [comment]
@nivekamoud Doesn't seem directly related to NORA.
I found this on stackoverflow, maybe it helps: https://stackoverflow.com/questions/72776325/npm-warning-config-production-use-omit-dev-instead

**Comment by nivekamoud** [comment]
yes thanks already tried it, on domoticz it is working fine but in home assitant not, thanks anyway  i think it is the problem of homeassitents node red.

**Comment by FireWizard52** [comment]
@nivekamoud ,

Do not worry. It is a warning and not an error.
I see this warning for almost every node that I install or upgrade in Node-RED. If you do not want to see it, you can follow Andrei's suggestion.

Node-RED is not a plug-in in Domoticz, like it is an integration in HA. So this a comparisson between  the HA version and the native installation of NR.

**Comment by Gianpaolo-Saracino** [comment]
I have the same problem, but following Andrei's link there are not suggestions about npmrc under linux. I'm using an Home Assistant VM and it seems impossible to access npmrc file or to use npm commands. Node-red addons installation commands are launched by a docker. Help please!!!
