### ISSUE TITLE
Smart NORA web app manifest scope is too restrictive

### ISSUE THREAD

**Issue by normanr** [andrei-tatar/node-red-contrib-smartnora#248]
When opening the Smart NORA web app the Dashboard has a URL bar is rendered at the top (this does not happen for Manage groups or Notifications). This is because the app scope is https://smart-nora.eu/my-nora/, but the Dashboard canonical url is https://smart-nora.eu/my-nora which is outside of the scope (so not seen as part of the app, and URL bar is displayed, ref: https://developer.mozilla.org/en-US/docs/Web/Manifest/scope).

There are a couple of ways that this could be fixed:
- widen the scope to be https://smart-nora.eu/ (probably just `./` in the manifest.webmanifest file), 
- make the canonical dashboard url end with a slash.

The manifest `start_url` could be tweaked too (to match the canonical dashboard url), i.e. just remove the trailing slash, but it wouldn't change any functionaly.

The manifest `id` probably shouldn't be changed, as that will require the app to be reinstalled (and it's also not needed as the `id` is allowed to be out of scope, ref: https://developer.mozilla.org/en-US/docs/Web/Manifest/id)

**Comment by andrei-tatar** [comment]
@normanr thanks for the detailed description.
I do have NORA installed but this behavior is not present on the Chrome + Android, for me. 
It does appear on Chrome + Windows.

I will have a look and fix it.

**Comment by andrei-tatar** [comment]
@normanr I removed the trailing slash in the manifest file. Should work fine now.

**Comment by normanr** [comment]
I had to reinstall the web app, but it works great now. Thanks!

**Comment by andrei-tatar** [comment]
@normanr interesting. I think it detects if an update was made in about 2-5 secs after load and it prompts for a refresh. That might've worked as well.
