### ISSUE TITLE
ignoring inbound msg for device ID ** because msg.payload.name (<undefined>) does not match '**'

### ISSUE THREAD

**Issue by Barabba11** [andrei-tatar/node-red-contrib-smartnora#251]
Hi, maybe my flow was written with an old version of this node, to update icon on my phone I'm sending to the input {payload:true} and actually I have the right rection, but on console I have this unpleasant log, it says is ignoring the message but actually is not ignoring it since I have the right reaction on my phone, so why this log? 
to avoid this log should I change all my function nodes to add the name property? May you please add an option to "don't care" if the name is provided or not? Thank you

**Comment by andrei-tatar** [comment]
Hi @Barabba11, those are validation warnings. Meaning the message has properties that are ignored by NORA. 
You can disable these warnings in the config node:

![image](https://user-images.githubusercontent.com/6473183/224379409-1a73ce5f-ece8-4045-94f6-494269290379.png)

**Comment by Barabba11** [comment]
Thank you!
By the way, to don't have warnings I use {payload:{on:true}};
