### ISSUE TITLE
DNS lookup error in the logs

### ISSUE THREAD

**Issue by mikestepanik** [andrei-tatar/node-red-contrib-smartnora#252]
getting the following error as of 3/14/2023 "nora: while sending heartbeat: getaddrinfo EAI_AGAIN api.smart-nora.eu
Error: getaddrinfo EAI_AGAIN api.smart-nora.eu
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)"

My user id is: CP3uoLEO9PZ9fYlDs8fUKbi3JcE3

**Comment by mikestepanik** [comment]
Is this an issue connecting to the API?

**Comment by andrei-tatar** [comment]
Hi, seems to be a DNS lookup issue.
Do you have internet connectivity issues?
If you open https://api.smart-nora.eu/ in a browser, does it work?
What if you ping it from your machine `ping api.smart-nora.eu`?
Are you running behind a proxy?
