### ISSUE TITLE
I have an issue while using NORA

### ISSUE THREAD

**Issue by gomecin** [andrei-tatar/node-red-contrib-smartnora#255]
Describe the problem here...

My user id is: wHB2TOQkMbQDoVrgD63e2fFkUPt2

Since a few days, Google Home is saying the devices are not connected. The devices are visible at the Nora's page, though.

**Comment by gomecin** [comment]
Hi Andrei,

You must have done something, because now it works without me doing
anything...

Anyhow, thank you, problema solved.

BR,
gomecin

**Comment by andrei-tatar** [comment]
@gomecin well it's good it solved itself, but I haven't touched it.
