### ISSUE TITLE
Updating to version 1.18.1 causes Smart NORA to stop working

### ISSUE THREAD

**Issue by kalya1** [andrei-tatar/node-red-contrib-smartnora#257]
Describe the problem here...

My user id is: KhuF4he6EvYQr7xueLKLXkwBRxh1
I tried to update to version 1.18.1 and none of them work anymore

**Comment by andrei-tatar** [comment]
@kalya1 Can you please provide more details?
What are you running node-red on? 
What node.js version?
What node red version?

**Comment by kalya1** [comment]
I deleted all devices and reinstall node-red-contrib-smartnora
