### ISSUE TITLE
problem update to 1.18.2

### ISSUE THREAD

**Issue by william89731** [andrei-tatar/node-red-contrib-smartnora#258]
hi andrei,

i am trying to update.
log error:

npm WARN config production Use `--omit=dev` instead.
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /data/node_modules/firebase
npm ERR! dest /data/node_modules/.firebase-fnFyHLBA
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/data/node_modules/firebase' -> '/data/node_modules/.firebase-fnFyHLBA'

**Comment by andrei-tatar** [comment]
Hi @william89731 ,
Did you manage to solve this?
Where are you running node-red?

**Comment by FireWizard52** [comment]
Hi @william89731,

See: https://discourse.nodered.org/t/enotempty-when-installing-node-from-palette-since-nodered-3-0-directory-not-empty/65968

Possible solution:  Delete the node_modules directory and do a re-install of the modules.
(In the ,node-red folder, run npm install)

Regards

**Comment by william89731** [comment]
> Hi @william89731 , Did you manage to solve this? Where are you running node-red?

kubernetes cluster baremetal

**Comment by william89731** [comment]
> Hi @william89731,
> 
> See: https://discourse.nodered.org/t/enotempty-when-installing-node-from-palette-since-nodered-3-0-directory-not-empty/65968
> 
> Possible solution: Delete the node_modules directory and do a re-install of the modules. (In the .node-red folder, run npm install)
> 
> Regards

solved!  delete folder an run "npm i node-red-contrib-smartnora@1.18.2"

thanks too much!!
