### ISSUE TITLE
Lost all devices except 1, but have an active subscription

### ISSUE THREAD

**Issue by osvedman** [andrei-tatar/node-red-contrib-smartnora#259]
I lost all my devices in Smart NORA except 1 yesterday, but my subscription is active. Can you please look into it?

My user id is: t7WJolzaFqMUs6VFcvFzRNi2qnF2

**Comment by andrei-tatar** [comment]
Hi @osvedman 
That's weird. I can see only one device is synced.
What version of NORA are you using?
Any logs in node-red?
Are you using multiple node-red instances or subflows?

**Comment by osvedman** [comment]
- I'm using Smart NORA v1.18.2.
- I'm not using multiple Node-RED instances, and I'm not using subflows.
- I didn't see any errors when this occurred, but now I see this:

> nora: <default> - unhandled error (trying again in 36.8 sec): HTTP response (404 {"description":"device missing","id":"409ebfca:1a912"})
> Error: HTTP response (404 {"description":"device missing","id":"409ebfca:1a912"})
>     at FirebaseSync.doHttpCall (/home/pi/.node-red/node_modules/node-red-contrib-smartnora/build/nora/sync.js:229:27)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async FirebaseSync.handleJob (/home/pi/.node-red/node_modules/node-red-contrib-smartnora/build/nora/sync.js:173:21)
> 

I tried simply rebooting the entire Raspberry Pi 4 just now, and it seems to have fixed it...

Weird, indeed.

**Comment by osvedman** [comment]
In the Google Home logs, all the devices were removed at 8:51 PM, May 4th 2023

**Comment by andrei-tatar** [comment]
I can see in the logs there were 2 sync calls with 3 seconds between them for the same group. 
The 1st call had 43 devices and the 2nd call had only 1 device and it override the 1st call. This was reported once, before, but I wasn't able to find the issue or reproduce it.

https://github.com/andrei-tatar/node-red-contrib-smartnora/issues/198

Will look further into it.

**Comment by andrei-tatar** [comment]
@osvedman published version `1.19.0` which fixes the issue.
