### ISSUE TITLE
I have an issue while using NORA - duplicate devices

### ISSUE THREAD

**Issue by Wireheadbe** [andrei-tatar/node-red-contrib-smartnora#264]
Hi,

Somehow all the devices on my account are duplicated. I tried to resync/re-connect on google home, but still all devices are duplicated. (One always showing "online", and another showing "offline")

Is there a way to "flush the cache" on the SmartNora side of things? Running SmartNORA 1.19.0

**Comment by Wireheadbe** [comment]
And just as I clicked on the groups feature, I saw some of them were grouped in an "old" group. Deleted group, fixed.

**Comment by patrik-malina** [comment]
I have same problem, but don't have old group to delete...

**Comment by patrik-malina** [comment]
@andrei-tatar can this be reopened?

**Comment by andrei-tatar** [comment]
@patrik-malina sure, though I'm out for my holiday

**Comment by patrik-malina** [comment]
This is very strange. I cannot figure it out. Node-red says it synced 35 devices:

![image](https://github.com/andrei-tatar/node-red-contrib-smartnora/assets/73561855/4d4dd182-39fe-4ee2-8d5a-3070bea58fee)

Smartnora in Home app shows 72 devices?!?

![image](https://github.com/andrei-tatar/node-red-contrib-smartnora/assets/73561855/5cb80e09-cf31-4801-8a6d-10d7b6389361)

Finally, Home app shows duplicated devices. One with offline status, other working.

![image](https://github.com/andrei-tatar/node-red-contrib-smartnora/assets/73561855/1490a2c5-d8ab-4c84-b83f-a05915e58523)

What i did so far:
1. Redeploy devices.
2. unlink, relink smartnora
3. delete cache in home app
4. reinstall home app.

**Comment by andrei-tatar** [comment]
@patrik-malina Have you checked the groups in NORA?
https://smart-nora.eu/my-nora/groups

**Comment by patrik-malina** [comment]
Yeah, that groups :)
I didn't know of this, sorry.

SOLVED!!!
