### ISSUE TITLE
I have an issue while using NORA

### ISSUE THREAD

**Issue by amel2001** [andrei-tatar/node-red-contrib-smartnora#265]
Describe the problem here...
i can't write email and password in edit nora config node

My user id is: lsDxwH25XLbdIa64IL9w6VgpA343

**Comment by andrei-tatar** [comment]
@amel2001 you shouldn't need to write email/password. Just click the `Login` button:
![image](https://github.com/andrei-tatar/node-red-contrib-smartnora/assets/6473183/56e8f6c6-dd9c-4245-a827-15333fb3f867)
