### ISSUE TITLE
Devices duplicated after recent update of Node-red components 

### ISSUE THREAD

**Issue by RichardLaxton** [andrei-tatar/node-red-contrib-smartnora#271]
I recently updated the SmartNORA components in my NodeRed setup and now every device is duplicated, with one being active and the other offline. 

![Screenshot_20230718-114512](https://github.com/andrei-tatar/node-red-contrib-smartnora/assets/21622875/2fa87024-e9a2-47e9-8732-a81e12679787)

I can't see any way to delete these extra devices. Any advice?

My user id is: s0peYLjMsLN4GFHS0PThy4x9SZI2

**Comment by andrei-tatar** [comment]
@RichardLaxton you can delete the old group here:
https://smart-nora.eu/my-nora/groups

**Comment by RichardLaxton** [comment]
Ah, that worked. Any idea why this problem might have happened in the first place? Why would the whole group set just reset after an upgrade?

**Comment by andrei-tatar** [comment]
@RichardLaxton I did change the default naming convention of groups (when not having a defined name) to use the group id but the backend should handle the next sync. However your group id doesn't follow the node-red convention... What node-red version are you using?

**Comment by RichardLaxton** [comment]
I started in Node red 2.x and then shifted to Node-red 3.x about 9 months ago I think. Currently running the latest in the 3.x branch. It had been a while since I updated the components though since I have been away for a couple of months.
