### ISSUE TITLE
I have an issue while using NORA

### ISSUE THREAD

**Issue by ianm500** [andrei-tatar/node-red-contrib-smartnora#274]
Describe the problem here...
Since yesterday, whenever I use a voice command to control a device Google does the command correctly but then follows it with "The XXX isn't available you might want to try setting it up again".  Yesterday I updated the Smartnora components to the latest.  I've since tried rebooting the Nodered server.  I noticed in my Smartnora account and within the Google Home app some devices are showing as offline yet they are showing as online within Nodered and they seem to work okay apart from the annoying "The XXX isn't available you might want to try setting it up again" message each time I use it.

My user id is: Fs6ZwWouFYSsrNHiLsVNrq1oZJD2

**Comment by andrei-tatar** [comment]
@ianm500 Seems to be the exact same issue from as #271 
Can you please try to delete the offline group from https://smart-nora.eu/my-nora/groups

**Comment by ianm500** [comment]
That fixed it, thank-you
