### ISSUE TITLE
I have an issue while using NORA- Subscription Related

### ISSUE THREAD

**Issue by ivishaltejwani** [andrei-tatar/node-red-contrib-smartnora#275]
Renewed subcription using email , paid the amount money got deducted but the service is still inactive kindly help
Steps to reproduce:
1 -
<img width="520" alt="image" src="https://github.com/andrei-tatar/node-red-contrib-smartnora/assets/57434902/a1493c39-4d40-445d-b63f-18c4001d1a9c">

2-
<img width="481" alt="image" src="https://github.com/andrei-tatar/node-red-contrib-smartnora/assets/57434902/611d69f1-f250-40f5-82de-4bcd85f7cc91">
3-
<img width="954" alt="image" src="https://github.com/andrei-tatar/node-red-contrib-smartnora/assets/57434902/c8060de4-0f7a-40c2-a6ce-c918ef8807df">

double checked the email id its the same account
My user id is: IMFD6eu236SKmw8SyC83I3tDBcp1

**Comment by andrei-tatar** [comment]
@ivishaltejwani Looking into it.
