### ISSUE TITLE
I have an issue while using NORA

### ISSUE THREAD

**Issue by alexbn71** [andrei-tatar/node-red-contrib-smartnora#279]
Hi, 

Allways worked well but since few month a strange issue with my Google Mini. 

After a voice command to turn on/off a device the command is correctly executed and Google Mini reply "Ok I turned on <device>" but after two seconds it always say "Sorry, <device> is not available now". This issue happen on each command.

Thanks
Alex

**Comment by andrei-tatar** [comment]
Hi @alexbn71,

Not sure what your user id is. You might have duplicated groups since updating to a new version.
Also what version of the package are you using?

If you have a duplicated offline group, you can remove it from here:
https://smart-nora.eu/my-nora/groups

Andrei T.

**Comment by alexbn71** [comment]
You are right. This is probably a duplicated groups issue since before my post I discovered this situation on my account and removed all duplicated groups but checking on my goole mini just after this action nothing changed. A few hours later I noticed that the problem had disappeared.

Thank you

**Comment by andrei-tatar** [comment]
@alexbn71 Yeah, it probably took a bit of time until the devices were resynced on all the Google Home devices.
