### ISSUE TITLE
HTTP response (429 Rate exceeded.)

### ISSUE THREAD

**Issue by seocube** [andrei-tatar/node-red-contrib-smartnora#28]
Hi, after succesful using smartnora for some days now i'm receiving constantly this error in console:

unhandled error (trying again in 67 sec): HTTP response (429 Rate exceeded.)
Error: HTTP response (429 Rate exceeded.)
    at FirebaseSync.doHttpCall (/home/pi/.node-red/node_modules/node-red-contrib-smartnora/build/firebase/sync.js:192:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)

Any suggestion?

**Comment by andrei-tatar** [comment]
Might be related to #26 
What version of the package are you using?

**Comment by seocube** [comment]
1.0.2

**Comment by seocube** [comment]
updated to 1.0.5, now it works.
