### ISSUE TITLE
Not able to connect smart nore with google home

### ISSUE THREAD

**Issue by MartinPietka** [andrei-tatar/node-red-contrib-smartnora#283]
Hi,
I am trying co connect my google home with smart nora, but I get this result:
![Vybraná fotografia (2)](https://github.com/andrei-tatar/node-red-contrib-smartnora/assets/150230118/97f01a41-79fa-424e-9bed-cba9c1716812)
Please help.

Thank you
Best regards
Martin

My user id is: dpodyH2U6IO7WvzJw1qefOADkNi2

**Comment by andrei-tatar** [comment]
@MartinPietka Hi Martin, can you provide more info about the device you're using? I haven't seen this error before

**Comment by MartinPietka** [comment]
Hello,
I am using Samsung Galaxy A22, Android 13

st 8. 11. 2023 o 10:06 Andrei Tatar ***@***.***> napísal(a):

**Comment by andrei-tatar** [comment]
@MartinPietka Are you using `github` authentication?

**Comment by andrei-tatar** [comment]
@MartinPietka  - I updated the login flow to use redirects instead of popup. Can you check if it's working fine for you now?

**Comment by MartinPietka** [comment]
Hi Andrei,
it is working now!
Thank you so much for your help!

Best regards
Martin

st 8. 11. 2023 o 12:09 Andrei Tatar ***@***.***> napísal(a):
