### ISSUE TITLE
I have an issue while using NORA

### ISSUE THREAD

**Issue by MastegaDragons** [andrei-tatar/node-red-contrib-smartnora#284]
Is not working, is the second time in few weeks

My user id is: SbRb1bxNSva2tYiqQ0yh6I6MDKc2

**Comment by andrei-tatar** [comment]
@MastegaDragons can you please provide more details? What is not working?

**Comment by MastegaDragons** [comment]
Hello,

Now is working, but I want to uninstall, and install.

El dg., 12 de nov. 2023, 6:46, Andrei Tatar ***@***.***> va
escriure:

**Comment by andrei-tatar** [comment]
@MastegaDragons I can see you're using one of the earlier versions of nora `1.0.2`. A lot of things were improved since then, especially related to stability.
Try upgrading to `1.20.0`.

**Comment by MastegaDragons** [comment]
I know, bit after updated, nothing is working. And I decided to return at
the previous version.

El dl., 13 de nov. 2023, 9:37, Andrei Tatar ***@***.***> va
escriure:

**Comment by andrei-tatar** [comment]
@MastegaDragons Latest version requires at least node.js 12. (Btw, latest stable version of node.js is 20!)

**Comment by MastegaDragons** [comment]
Thanks, I'll check it out.

El dl., 13 de nov. 2023, 17:46, Andrei Tatar ***@***.***> va
escriure:
