### ISSUE TITLE
I have an issue while using NORA

### ISSUE THREAD

**Issue by soovui** [andrei-tatar/node-red-contrib-smartnora#285]
Describe the problem here...

My user id is: tFdjrSc59dX1JqWKVkUDZ1KpN8U2

I did not receive any notification after so many attempts and I already subscribe enable notification. Even try to disable and enable notification subcription again.

Hope to hear from you asap

**Comment by andrei-tatar** [comment]
@soovui What flow are you using? Have you tried the example flow?

**Comment by soovui** [comment]
hi andrei, 

yes i tried example flow, it does not work.  i am using samsung mobile fold 5 and huawei mate 9 and mate 20 pro and all support google home. I am able to control light 1 and light 2 without any problem but when I click the timestamp, it show sent but nothing receiving on my mobile phone.  I am in Malaysia and time zone GMT +8.

**Comment by andrei-tatar** [comment]
@soovui The `notify` node is not related to Google Home. It's a web based notification that you should receive from the web site (https://smart-nora.eu).

I suspect the problem you're facing is that you have browser notifications disabled for `smart-nora.eu` or all sites together. Maybe check your browser/device permissions and try again.

Also, not all browsers support web push notifications: https://caniuse.com/push-api

**Comment by soovui** [comment]
> @soovui The `notify` node is not related to Google Home. It's a web based notification that you should receive from the web site (https://smart-nora.eu).
> 
> I suspect the problem you're facing is that you have browser notifications disabled for `smart-nora.eu` or all sites together. Maybe check your browser/device permissions and try again.
> 
> Also, not all browsers support web push notifications: https://caniuse.com/push-api

fantastic, now I understood.  it works perfectly.  one more question, 20 euro per year, unlimited devices allow?

**Comment by andrei-tatar** [comment]
@soovui yes:
- free version: 5 devices limit
- paid version: unlimited devices.
