### ISSUE TITLE
All my SMART Nora devices keep showing up in offline status

### ISSUE THREAD

**Issue by rvdnieuw** [andrei-tatar/node-red-contrib-smartnora#292]
My devices work using nodered but using google home with a google home mini I always get the "Device if not available" message. Also devices are not showing up in my Google Home App. I have tried to unlink and link again in Google Home App but without luck. Also the SmartNora WebUI shows all devices grayed out and not switchable. I have a subscription.

**Comment by andrei-tatar** [comment]
@rvdnieuw Can you provide your user id?
Have you checked your node-red instance. Any errors in the logs?
What version of `node-red-contrib-smartnora` are you using?
What version of `node.js` and `node-red` are you using?

**Comment by rvdnieuw** [comment]
I am using:
`node-red-contrib-smartnora`  v1.21.4
`node.js` v18.19.0
`node-red` v3.1.3

(but the problem occurred for some time now and was also the case on previous versions of node-red and node.js)
No errors in the node-red logs. The switches in Node-Red do activate on voice commands using Google Mini speaker.

The problem is:
1.  In the Smart-Nora Web UI (https://smart-nora.eu/my-nora) all my devices are disabled / grayed out
![image](https://github.com/andrei-tatar/node-red-contrib-smartnora/assets/21461062/d0e0c12d-a0f3-4c1e-b357-0192342d2302)

3. The Google Home App does not show my devices even after unlinking and linking Smart Nora again
4. The Google Home Mini speaker is responding to voice commands and turns on/off Smart Nora switches but right after performing the actions speaks out "Sorry it seems that [device XYZ] is not reachable at the moment"

UserID: mail4rembrand@gmail.com

**Comment by andrei-tatar** [comment]
It seems like you have the devices duplicated in 2 groups. Can you please delete the unused group from https://smart-nora.eu/my-nora/groups

I think the one called '<default>' is the unused one.

**Comment by rvdnieuw** [comment]
That did the job ! Thanks for your support Andrei.
