### ISSUE TITLE
I have an issue while using NORA

### ISSUE THREAD

**Issue by Marvin-VW** [andrei-tatar/node-red-contrib-smartnora#294]
Hey, i updated my devices in node-red but the old devices are still in my dashboard and wont delete (but they show up as offline).

My user id is: btJu6kVbw9Q1C4iOP7FY0tueXQm2

**Comment by andrei-tatar** [comment]
@Marvin-VW you should be able to delete the old group from:
https://smart-nora.eu/my-nora/groups

Let me know if you experience any issues.
