### ISSUE TITLE
Doorbell does not work

### ISSUE THREAD

**Issue by WoodyLetsCode** [andrei-tatar/node-red-contrib-smartnora#299]
Since a few days the doorbell is not working anymore.
I didn't change anything and from one day to the next it stopped working.
I can see the device in Google Home, but my Google Nest Minis are not ringing.
Notifications are enabled.

| ![Screenshot_2024-02-24-23-40-20-23_2d2bd67b5e15ae98c151ac739cd6881e](https://github.com/andrei-tatar/node-red-contrib-smartnora/assets/27882680/3cbce5fe-4068-4749-b8c8-dd4c314b25e4) | ![Screenshot_2024-02-24-23-40-25-00_2d2bd67b5e15ae98c151ac739cd6881e](https://github.com/andrei-tatar/node-red-contrib-smartnora/assets/27882680/9d7ebb4e-d451-413b-8746-9b5f0aafef4f) |
|--------|--------|

I also added a new device using your test flow and it did not work either.

**Comment by andrei-tatar** [comment]
Hi @WoodyLetsCode ,
Thanks for reaching out.
Well, I haven't changed anything recently. I'll do some investigation.

**Comment by andrei-tatar** [comment]
@WoodyLetsCode I tried the [example flow from the readme](https://github.com/andrei-tatar/node-red-contrib-smartnora/blob/master/doc/nodes/doorbell/README.md) and it works ok for my setup.
Did something change in your setup locally or in the runtime (packages/versions/network related things/etc.)?

**Comment by WoodyLetsCode** [comment]
I didn't change anything.
The weird thing is that all the other nodes (like switches or lights) do work.

**Comment by andrei-tatar** [comment]
@WoodyLetsCode can you paste your user id? I can't check any logs without it.

**Comment by WoodyLetsCode** [comment]
Alright, it seems there might have been a problem with Google. I didn't make any changes, but now it’s working again. Thank you for your assistance! 😄
