### ISSUE TITLE
In Node-Red pallete, can not find "node-red-contrib-smartnora"

### ISSUE THREAD

**Issue by FamiliaDomsa** [andrei-tatar/node-red-contrib-smartnora#30]
Hello,

I have this config.:
Add-on version: 9.0.1
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.13  (armv7 / raspberrypi3)
 Home Assistant Core: 2021.4.6
 Home Assistant Supervisor: 2021.04.3

This is my user id: vA2v8f4c9sP2XgAo0CDDtEvobiC2 on NORA

In Node-Red pallete, can not find "node-red-contrib-smartnora"

**Comment by andrei-tatar** [comment]
Hmm, that's weird. 
Can you post a screenshot? What node-red version are you using? I'm not really sure what could be causing this. Maybe it's a question for the general node-red forum.

![image](https://user-images.githubusercontent.com/6473183/117283783-c9c99900-ae6e-11eb-891d-6650e7c784ef.png)

**Comment by andrei-tatar** [comment]
@FamiliaDomsa was the issue solved for you?
