### ISSUE TITLE
I have an issue while using NORA

### ISSUE THREAD

**Issue by ctreischman** [andrei-tatar/node-red-contrib-smartnora#300]
Describe the problem here...
My devices can be controlled through the website.  And my scenes used to be controllable through google home.  Now my existing scenes still work, but when I change the names they do not update in the google home app.  When I try to re-login through the "works with google", it says that "No compatable devices were found in your smart nora account."

The scene names update, but the room names do not.

Any suggestions?

My user id is: uneMLxzDk2MS8dDbTbxr9xM9Cup1

**Comment by andrei-tatar** [comment]
Hi @ctreischman,
As far as I know, Google only updates the names on the 1st sync. So any subsequent name changes will not reflect in the Google Home app (you can however change them from the Google Home app). It's the same for the room names.

> When I try to re-login through the "works with google", it says that "No compatable devices were found in your smart nora account."

Is it possible that you are using 2 different user accounts? (two different google accounts, or something similar).
