### ISSUE TITLE
I have an issue while using NORA

### ISSUE THREAD

**Issue by Jos-77** [andrei-tatar/node-red-contrib-smartnora#303]
I have a subscription an Nora Smart, it is paid but login says no active subscription.

Payment is done at 24 may, 

Please PM 

My user id is: F9J19JTpZVbBAqXyxifVVTLR2Kq1

**Comment by andrei-tatar** [comment]
Hi @Jos-77
Please send me an email on the support email address with the email address you used to subscribe.
I checked the user id you linked here `F9J19JTpZVbBAqXyxifVVTLR2Kq1` and stripe says there is no payment related to it. You might have created/paid for a different account (with a different email address).

**Comment by Jos-77** [comment]
Account for smart Nora

***@***.***

Attachment payment

Greatings Jos


Op ma 10 jun 2024 12:34 schreef Andrei Tatar ***@***.***>:

**Comment by andrei-tatar** [comment]
@Jos-77 I've sent you an email to the account associated with user id `F9J19JTpZVbBAqXyxifVVTLR2Kq1`.
