### ISSUE TITLE
Migración de node-red de Windows a raspberry pi 

### ISSUE THREAD

**Issue by Gus514** [andrei-tatar/node-red-contrib-smartnora#304]
Migre node-red de Windows a Raspberry pi con raspbian, google assistant no me reconoce el dispositivo nodo smart nora  ya no me pide correo y contraseña en el nodo me pide un token? con mi id no funciona donde obtengo el token? .
En Windows todo funcionó perfecto.  
Desde ya gracias

**Comment by andrei-tatar** [comment]
@Gus514 you might have installed the wrong package in node-red. Can you post a screenshot?

**Comment by Gus514** [comment]
(https://github.com/andrei-tatar/node-red-contrib-smartnora/assets/62228484/51c3822a-f281-46ef-89fb-b4e7de889f49)

**Comment by andrei-tatar** [comment]
@Gus514 those are the old NORA nodes. The new package is called `node-red-contrib-smartnora` and the nodes have a different color:
![image](https://github.com/andrei-tatar/node-red-contrib-smartnora/assets/6473183/c21e6f35-67d8-470b-b363-e3826c2f8e79)

**Comment by Gus514** [comment]
Gracias por su ayuda. Solucionado
