### ISSUE TITLE
I have an issue while using NORA

### ISSUE THREAD

**Issue by MHagreis** [andrei-tatar/node-red-contrib-smartnora#306]
PM2.5 message is not processing correctly from of node red, 
example value is not processing into google home 

message in is: {"PM2.5": 24}
![image](https://github.com/user-attachments/assets/59d6614c-1a3e-4bac-9e41-789c2b862af4)

error
![image](https://github.com/user-attachments/assets/6e5fbce4-9471-4ba3-ba78-71004423a32b)

what is my stupid mistake
My user id is: EllxzomrJzQfibfyyuSavy9EjQz2

**Comment by andrei-tatar** [comment]
Hi @MHagreis 
Can you please provide an example flow?

**Comment by MHagreis** [comment]
updated the problem see information

**Comment by andrei-tatar** [comment]
@MHagreis it needs to follow the google home trait schema (https://developers.home.google.com/cloud-to-cloud/traits/sensorstate#examples_1).

Try with the following payload:
```json
{
  "currentSensorStateData": [{
    "name":"PM2.5",
    "rawValue":24
  }]
}
```

**Comment by MHagreis** [comment]
this works thanks i will adjust my code accordingly, sorry for the stupid question thank you for the quick and great support
