### ISSUE TITLE
I have an issue while using NORA

### ISSUE THREAD

**Issue by pdufrenne** [andrei-tatar/node-red-contrib-smartnora#307]
Describe the problem here...

I have a language problem.
After returning home from holiday, I need to use the English command to switch "ON" the air-conditioning unit, or to set it to cooling. Other commands are accepted when spoken in "Dutch" like before.

When using the “Dutch” command, Google responds with: “It looks like the device hasn’t been setup yet”. 

Is this problem related to smart-nora?

My user id is: SQpdWJDV5eciFlRNyRaLKLUV5Ux1

**Comment by andrei-tatar** [comment]
Hi @pdufrenne ,

Unfortunately this is not a problem with smart-nora but with how Google does natural language processing. Nora only exposes the devices to google and google decides which devices and how they are controlled.

I've read on reddit and a lot of people are not happy with the changes in the assistant related to device control, but it seems most of the issues come from the recent Gemini integration and rollout.

https://www.reddit.com/r/googlehome/
