### ISSUE TITLE
Issue with update

### ISSUE THREAD

**Issue by EivindTjessem** [andrei-tatar/node-red-contrib-smartnora#308]
After update of Node RED to 4.0.2 smartnora stopped working.

Current version is 1.22.0

Have tried to uninstall but get error:
- Failed to remove: node-red-contrib-smartnora
- Module not found
- Check the log for more information

Upgrade to 1.23.0 also gives error:
2024-08-27T13:25:31.943Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --omit=dev --engine-strict node-red-contrib-smartnora@1.23.0
2024-08-27T13:26:06.248Z [err] npm error code ENOTEMPTY
2024-08-27T13:26:06.248Z [err] npm error syscall rename
2024-08-27T13:26:06.249Z [err] npm error path /root/.node-red/node_modules/firebase
2024-08-27T13:26:06.249Z [err] npm error dest /root/.node-red/node_modules/.firebase-eRlD64Qj
2024-08-27T13:26:06.249Z [err] npm error errno -39
2024-08-27T13:26:06.252Z [err] npm error ENOTEMPTY: directory not empty, rename '/root/.node-red/node_modules/firebase' -> '/root/.node-red/node_modules/.firebase-eRlD64Qj'
2024-08-27T13:26:06.259Z [err] 
2024-08-27T13:26:06.259Z [err] npm error A complete log of this run can be found in: /root/.npm/_logs/2024-08-27T13_25_32_144Z-debug-0.log
2024-08-27T13:26:06.373Z rc=217

Have tried to rename, but it just give new folder to rename:

![image](https://github.com/user-attachments/assets/4abb0492-769c-467c-a399-da03a8fb7860)

Have renamed 1++ folders, restarted Node RED. Then it started over on the same folders.

**Comment by andrei-tatar** [comment]
@EivindTjessem how did you upgrade node-red?
I see you're running as root. Is this running inside a container?

**Comment by EivindTjessem** [comment]
Node RED is running om LXC in Proxmox
Upgraded with this command: 
![image](https://github.com/user-attachments/assets/471a4709-5d1d-46a3-84b2-deee8997293d)

I have tried to remove the folders from now on:
![image](https://github.com/user-attachments/assets/b9b8fc68-94b5-4f0f-8787-084aaf1f4ec4)

![image](https://github.com/user-attachments/assets/4090b99c-8cee-4f0b-8bbc-e00788b1de8e)

after reboot of node red, I need to delete again.

**Comment by andrei-tatar** [comment]
Can you paste here your `~/.node-red/packages.json` file?
Might be easier to do a `rm -r ~/.node-red/node_modules` and do an `npm install` inside `.node-red` folder.

**Comment by EivindTjessem** [comment]
"name": "node-red-project",
    "description": "A Node-RED Project",
    "version": "0.0.1",
    "private": true,
    "dependencies": {
        "@flowforge/node-red-dashboard": "~0.7.0",
        "node-red-contrib-cx-alarm-log": "~1.1.2",
        "node-red-contrib-ftp": "~0.0.8",
        "node-red-contrib-home-assistant-websocket": "~0.68.1",
        "node-red-contrib-machine-learning-v2": "~1.0.9",
        "node-red-contrib-mikrotik": "~0.7.0",
        "node-red-contrib-millheat": "~0.0.4",
        "node-red-contrib-mqtt-dynamicsub": "~0.0.9",
        "node-red-contrib-nordpool-api-plus": "~4.5.2",
        "node-red-contrib-smartnora": "~1.22.0",
        "node-red-contrib-time-range-switch": "~1.2.0",
        "node-red-contrib-yr": "~0.1.16",
        "node-red-dashboard": "~3.6.5",
        "node-red-node-ui-table": "~0.4.3",
        "thingzi-logic-timers": "~1.4.5"
    }

**Comment by andrei-tatar** [comment]
I would try:

```bash
cd ~/.node-red
rm -r node_modules 
npm install
```

**Comment by EivindTjessem** [comment]
Thanks for help, i just run in to new issues.
I will restore backup before Node Red upgrade.

And do the upgrade of smart NORA First
