### ISSUE TITLE
Sensor node?

### ISSUE THREAD

**Issue by dmutpuul** [andrei-tatar/node-red-contrib-smartnora#31]
Hello, thank you for the job) Is there any plan to add sensor support ? At the moment i add thermostat that show me actual temperature at home) But as i understand there is a sensor in device types...

**Comment by andrei-tatar** [comment]
@dmutpuul btw, the sensor trait doesn't support temperature yet... 
https://developers.google.com/assistant/smarthome/traits/sensorstate#supported-sensors

**Comment by patrik-malina** [comment]
![image](https://user-images.githubusercontent.com/73561855/123478107-4707c380-d5ff-11eb-8da4-bea61515f707.png)

I'm using Tuya Temp and Humidity sensor. It is shown on Google Home with tuya/smart life plugin.
I can ask what humidity and temperature in room is, and GA answer as well

**Comment by andrei-tatar** [comment]
Interesting. I had another look and sensors do support temperature control trait in order to report temperature. Same for humidity.

I'll add a sensor node when I get a chance.

**Comment by andrei-tatar** [comment]
v1.0.10 adds support for temperature/humidity sensor to smart nora
