### ISSUE TITLE
I have an issue while using NORA

### ISSUE THREAD

**Issue by asadih** [andrei-tatar/node-red-contrib-smartnora#311]
Hi there, 
All Nora nodes in nodered are disconnected and no matter what I do don't connect. 

My user id is: #######

**Comment by andrei-tatar** [comment]
@asadih Hi,
Can you provide more details? Any node-red logs?

**Comment by andrei-tatar** [comment]
@asadih The server was not down, so not sure what might have been the cause. I'm also using the service and didn't get any offline devices or commands not executing in the past days.

Nothing interesting in the node-red logs in those 3 days?

**Comment by asadih** [comment]
Thanks, I only can have the recent logs, as it is attached;
is there any way to get access to the older logs or logs for the actual
Nora nodes?
Cheers,
Hamed

[image: image.png]

**Comment by andrei-tatar** [comment]
@asadih no, NORA doesn't have it's own logging system. It just uses the Node-RED one. It also doesn't have any telemetry system other than the actual functional requests it does to the API.

**Comment by asadih** [comment]
Thank you.
Everything is working now; and I'll let you know if any issues arise.
