### ISSUE TITLE
Can't see the scene icon on app

### ISSUE THREAD

**Issue by Barabba11** [andrei-tatar/node-red-contrib-smartnora#34]
Hi, this is the problem so I can't test it. Any way to solve it?
I woud report 2 other problems:
when autentication fails (password wrong) on the second time it quits form node red. It would be better to report it only and stop attempting to don't create the need for password resetting.
When 2 factor is enabled it never asked me the pin (for lock node), and other nodes stop working properly, I've disabled it and won't use lock

**Comment by rgerrans** [comment]
For 2FA, are you using the more recent version where you configure in the device node and not the config node? If  done in the config node, non-2FA don't work when associated with a 2FA setup

**Comment by Barabba11** [comment]
thanks for reply, thats' very strange.. I have version 1.0.1 in palette, I can see 1.0.5 online but no "update" button, I've then tried forcely install with npm install node-red-contrib-smartnora, it downoaded a lot and installed, but still see 1.0.1, and 2 factor is only on config node. Maybe under Windows still 1.0.1? How can I update?
What about scenes? Why can't see it? 
Thanks

**Comment by Barabba11** [comment]
Hope to have an answer.. thank you

**Comment by andrei-tatar** [comment]
@Barabba11 

> Can't see the scene icon on app

In the Google Home app? There is no widget for a scene.

**Comment by andrei-tatar** [comment]
> when autentication fails (password wrong) on the second time it quits form node red. It would be better to report it only and stop attempting to don't create the need for password resetting.

Good suggestion, though I don't think this is something that happens too often.

**Comment by Barabba11** [comment]
Thank you for your support, how then I can use the scene node? In the guide (really short) it's defined as device, so I suppose to find it like other devices. Can you please describe me better how it works? Thanks :)
https://github.com/andrei-tatar/node-red-contrib-smartnora/tree/master/doc/nodes/scene

I've placed my pc on st-by, today when I woke it up the node red stopped I think because of smart nora. It's not a big probem for me because I use windows only for testing, but I think it's not normal.
10 May 11:48:06 - [t [Error]: A network error (such as timeout, interrupted connection or unreachable host) has occurred.] {
  code: 'auth/network-request-failed',
  a: null
}

**Comment by andrei-tatar** [comment]
> Can you please describe me better how it works?

It only works via voice: "Hey google, activate scene [Name]".

> I've placed my pc on st-by, today when I woke it up the node red stopped I think because of smart nora.

Not sure. Do you have any other plugins installed?

**Comment by Barabba11** [comment]
So as I understand there is no icon on the Home app, no way to be sure it is installed until we give vocal command, right?
I told the Home app to activate that shenario and nothin happens, honestly also other devices with vocal don't work, I don't know why google assistence doesn't work. I mind much more to use touch, I want to put a tablet near the exit door and manage my devices from there, any way to activate a scene by touch? 
Thank you

**Comment by andrei-tatar** [comment]
> So as I understand there is no icon on the Home app, no way to be sure it is installed until we give vocal command, right?

No icon. There is a place in Google Home where you setup a "Routine" and you can specify an action to activate a scene.

> I told the Home app to activate that shenario and nothin happens, honestly also other devices with vocal don't work, I don't know why google assistence doesn't work.

For me it responds with "ok, activating [Scene Name]". I have no idea what your setup is.

>  I mind much more to use touch, I want to put a tablet near the exit door and manage my devices from there, any way to activate a scene by touch?

Maybe Google Home is not the right choice for you. As far as I know there is no way to activate a scene by touch in the Google Home application.

**Comment by Barabba11** [comment]
thanks for video, really helps to understand, I suggest you to include it on guide. I did all but unfortunately assistant doesn't understand nothing, it thiks and propose me default stupid suggestions. I've to work on it when I have time
Thank you )))
