### ISSUE TITLE
support for more device types ?

### ISSUE THREAD

**Issue by sharathbk1912** [andrei-tatar/node-red-contrib-smartnora#35]
Firstly thank you for this integration!

I Would like to know if there would be support for more devices like television . 
also is there a place where we can follow the development/upcoming features?

Thanks and Regards
Sharath B K

**Comment by andrei-tatar** [comment]
There will be support for more devices. The biggest part of adding new devices is the node-red node (the html and js files). 
Any help is greatly appreciated.

(Support for FAN is already added it will be included in the next release).

**Comment by sharathbk1912** [comment]
Yes i see that there is a lot of things in those 2 files for each type. 
I would be willing to help however i dont follow them as such :( 

Thank you!
