### ISSUE TITLE
Ambient temperature 

### ISSUE THREAD

**Issue by geotibi** [andrei-tatar/node-red-contrib-smartnora#36]
I'm trying to get the ambient temperature from Domoticz using Nora to Google assistant but I cannot get the accurate value. I mean the value is rounded without decimals. Instead to show me 21.8 it's showing 22. Is it any configuration that need to be done to display the value with decimals? I have it in this format in payload but the nora node is rounded it.

**Comment by andrei-tatar** [comment]
Yes, Google Home rounds to .5 deg so NORA also rounds. No point in keeping more accuracy than it's used.
