### ISSUE TITLE
Why no HEX Value for Light Node ?

### ISSUE THREAD

**Issue by Chris-The-Tuner** [andrei-tatar/node-red-contrib-smartnora#37]
Hey there,
i'm working on a small project with a Light node and Tasmota Firmware.
I have big problems with the Light node not being able to give me the values i need for tasmota. (NORA= HSV, Tasmota=hsb)
I've seen that the Light node already does show a Hex (#00ff00) value in it's stat string, would it be possible to have that as a payload color in a upcomming version ?
Would ease mutch work.

**Comment by andrei-tatar** [comment]
A hex string as a payload is not enough to describe the state of the light. There still the on/off flag and the brightness (if used).
I guess it might work on the input payload but not on the output.
