### ISSUE TITLE
Stopped using multiple blinds

### ISSUE THREAD

**Issue by nygma2004** [andrei-tatar/node-red-contrib-smartnora#38]
I have 7 blinds at home. I used to control them together by "open the blinds", "close the blinds" voice command. All was fine. Since 2 days ago, my Nest Hub responds "opening/closing xxx blind". It picks one of my blinds (always the same) and controls only that. Even though it shows all 7 devices on the screen. Even if I say "open all the blinds", it still only controls that one.

I checked my flow, maybe the other blinds are in a different position, but no. If all my blinds are 100% and ask to "open the blinds", it will still say "OK, opening xxx blind".

**Comment by andrei-tatar** [comment]
This issue was also reported on slack. Nothing to do with NORA. No changes have been done in over a week.
Most probably changes over at Google...

**Comment by andrei-tatar** [comment]
@nygma2004 Is this still happening? (I don't have any blinds setup)

**Comment by andrei-tatar** [comment]
No, wondering if they fixed something over at Google. I also have a switch with ACK setup that went crazy for a day but it got fixed, so I assumed Google did some fixes over at their side.

**Comment by andrei-tatar** [comment]
I managed to investigate this issue and it seems something changed over at google for the local execution path.
So before it was sending one open/close command for multiple devices, now it seems it sends multiple commands for each device and the local execution script doesn't like that.  

I will create a fix but it will take some time to be deployed.

Until then, you can try to disable local execution (create a separate config without local execution and use it for the blinds you want).

**Comment by nygma2004** [comment]
Thanks a lot. I am fine, I also have some touch screens at home which move all the blinds at the same time, so we just use that for the time being. But good catch.

**Comment by Flixm** [comment]
is ther any workaround to deactivate the local execution till it solved ?

**Comment by nygma2004** [comment]
It is resolved for me. It did not happen automatically, I noticed a new version, so I upgraded from 1.0.3 to 1.0.6 and restarted Node-Red, but the "open the blinds" request comes back with "opening 7 blinds" as expected. Interesting, on the UI one shows as blue and all the other still green:
![image](https://user-images.githubusercontent.com/16757620/120148959-4db23f00-c1e9-11eb-9996-4afa638fd6f1.png)

**Comment by Flixm** [comment]
I got the same two weeks ago. I changed the status Intervall of the incoming status. Therefore the status will only come into the blind node when the status is changed. Now I got a report every time something is done in my blind/light controlling PLC.
Now all are blue ... After I look at it 2-3 days later.
But only the blinds not the lights.

**Comment by nygma2004** [comment]
It looks like it is broken again. I am getting the same response as before.

**Comment by andrei-tatar** [comment]
@nygma2004 I just got back, so what is not working more specifically?

**Comment by nygma2004** [comment]
We are back to the same state as before. If I ask to "open the blinds", GH response "OK, opening xxxx blind", so it picks one from the lot and that is all. When you said it is fixed, I updated the node, restarted node-red (for other reasons) and it was working. And after a few days now, it is broken again.

**Comment by andrei-tatar** [comment]
@nygma2004 It seems it's working fine for me. Just tried it and all blinds were closed. Not sure if there's an issue with the local execution script deployment on Google's side of things.

**Comment by nygma2004** [comment]
@andrei-tatar and now it works for me too. Maybe there was a glitch at Google. Also I was setting up a new device at home, and shut down power completely. Maybe the restart to Node-Red and also to all Goolge devices helped.

**Comment by andrei-tatar** [comment]
Ok, I'll close this issue for now
