### ISSUE TITLE
Feature request - Open/Close node with input status managed control

### ISSUE THREAD

**Issue by xury77** [andrei-tatar/node-red-contrib-smartnora#39]
Would it be possible to add a new feature to the "open/close" node so that when the gate is  already open, the payload would not be sent when you tried to open it again? My idea is tu use input status to check when is really opened or closed and depending on the state and it would not pass the payload with the same command as it is currently in the status of the node.
It would be nice if the speaker also informed that the device is already open or close depending current state.

**Comment by rgerrans** [comment]
You can do that in Node-Red independent of the Nora node. Just use a switch node to check against the current status of the gate. As far as the speaker response that's a Google item. Though you could use a cast-node in Node-Red and build a flow to do that triggered off that same Switch node.

**Comment by andrei-tatar** [comment]
I asked to open this issue. As far as I know, it's possible to give back an error code so google will respond with "already opened/closed". I'll investigate when I get a chance

**Comment by xury77** [comment]
Yes I managed it using function node. But still the speaker says that  opening. It will be nice to hear "already opened" and get another property. It should by an option  for those willing.

**Comment by FireWizard52** [comment]
Did you already consider to use a "status" node and configure this node exclusive for the Smart-Nora Switch node?
See below:

file:///home/herman/Pictures/Screenshot_Nora_Switch_Status.png

**Comment by rgerrans** [comment]
> I asked to open this issue. As far as I know, it's possible to give back an error code so google will respond with "already opened/closed". I'll investigate when I get a chance

Looks like I shouldn't have assumed. Looks pretty straight forward -https://developers.google.com/assistant/smarthome/reference/errors-exceptions

**Comment by andrei-tatar** [comment]
I managed to update the backend and the nodes. The only things remaining are to update the node docs and confirm with Google the release of the new version (there are some changes in the local execution scripts).

**Comment by andrei-tatar** [comment]
Release 1.0.6 added support for this
