### ISSUE TITLE
Google home device "not responding"

### ISSUE THREAD

**Issue by stanzlavos** [andrei-tatar/node-red-contrib-smartnora#41]
My flow :

`[{"id":"b3ad0218.d5d6a","type":"noraf-switch","z":"ba5120f4.37e69","devicename":"Bedroom Fan","roomhint":"Bedroom","name":"Bedroom Fan","passthru":true,"nora":"fc25969c.703568","topic":"","onvalue":"1 bed fan one","onvalueType":"str","offvalue":"0 bed fan one","offvalueType":"str","twofactor":"off","twofactorpin":"","x":400,"y":120,"wires":[["9884da1b.87a088","cc6e2855.de4ff8"]]},{"id":"9884da1b.87a088","type":"mqtt out","z":"ba5120f4.37e69","name":"Local MQTT","topic":"home/broadcast","qos":"2","retain":"","respTopic":"","contentType":"","userProps":"","correl":"","expiry":"","broker":"d74e097c.3f2408","x":630,"y":120,"wires":[]},{"id":"cc6e2855.de4ff8","type":"ui_switch","z":"ba5120f4.37e69","name":"Bedroom Fan","label":"One","tooltip":"","group":"e4a283a2.ac928","order":0,"width":"0","height":"0","passthru":false,"decouple":"true","topic":"topic","topicType":"msg","style":"","onvalue":"1 bed fan one","onvalueType":"str","onicon":"","oncolor":"","offvalue":"0 bed fan one","offvalueType":"str","officon":"","offcolor":"","animate":true,"x":400,"y":240,"wires":[["b3ad0218.d5d6a"]]},{"id":"fc25969c.703568","type":"noraf-config","name":"nora config","group":"","twofactor":"off","twofactorpin":"","localexecution":true,"structure":"Home"},{"id":"d74e097c.3f2408","type":"mqtt-broker","name":"Local MQTT Broker","broker":"10.0.0.102","port":"1883","clientid":"","usetls":false,"protocolVersion":"4","keepalive":"60","cleansession":true,"birthTopic":"","birthQos":"0","birthPayload":"","birthMsg":{},"closeTopic":"","closeQos":"0","closePayload":"","closeMsg":{},"willTopic":"","willQos":"0","willPayload":"","willMsg":{},"sessionExpiry":""},{"id":"e4a283a2.ac928","type":"ui_group","name":"Fans","tab":"defe0d87.a4cc6","order":1,"disp":true,"width":"6","collapse":false},{"id":"defe0d87.a4cc6","type":"ui_tab","name":"Bedroom","icon":"label","order":1,"disabled":false,"hidden":false}]`

The device appears in my Google Home app. It works intermittently and sometimes it is shown as "Not responding". Any suggestions ?

**Comment by stanzlavos** [comment]
I figured out the problem : the port used for communicating were being blocked by my Raspberry Pi firewall. :) 

A few observations : 

1) After I fixed the port issue, everything started to work fine. I could see the states changing in the flow tab. But after a few minutes of testing, the flows tab stop updating the ON/OFF status. 

2) Sometimes, the google home app on my phone shows the device as "offline"/"not repsponding", but the device itself can be turned off/on using voice commands. Why is this ?

**Comment by stanzlavos** [comment]
A few more observations : 

1. The switch NORA node outputs the payload twice occasionally. That is, when turning device the ON/OFF, the ON/OFF payload are pushed out 2 times occasionally. 

2. Sometimes everything works perfectly. If I click from the UI (dashboard), my google home app also updates the state and vice versa. Other times, the behavior is as in observation 2 mentioned in previous comment.

**Comment by andrei-tatar** [comment]
All the symptoms indicate that node-red looses connection to firebase (this is when the devices are marked as offline). Maybe your firewall settings...

> Sometimes, the google home app on my phone shows the device as "offline"/"not responding", but the device itself can be turned on/off using voice commands. Why is this ?

Because local execution still works (meaning your google home devices are connected and can talk with your local node-red instance).

**Comment by stanzlavos** [comment]
> All the symptoms indicate that node-red looses connection to firebase (this is when the devices are marked as offline). Maybe your firewall settings...
> 
> > Sometimes, the google home app on my phone shows the device as "offline"/"not responding", but the device itself can be turned on/off using voice commands. Why is this ?
> 
> Because local execution still works (meaning your google home devices are connected and can talk with your local node-red instance).

Thank you for the input, and sorry for the delay in responding. :)

The connectivity was the problem. I was, in general, facing some random connectivity issues (packets being dropped by the EPON unit in my home). Everything seems to be working fine now.

Thanks once again. :)

**Comment by stanzlavos** [comment]
I am still getting the "Not Responding" problem occasionally. :( I don't have any network problems as of now, so I can't think of any reason for node-red to loose connection with firebase. Once I deploy the nodes once more, usually the problem goes away. In this state, voice commands still works : flows are triggered but my google assistant itself announces that the device is not available. And, the device is shown as "Not Responding" in the Home app. Any suggestions ?

And, IIRC, I have not seen this problem in quite a few days, but seems it has started again. I get multiple triggers when turning the switch on/off via google. Is this expected ?

As per the FAQ, I have opened the following ports on my Raspberry Pi (default is to allow outgoing and drop incoming): 

6988 - used to broadcast the discovery packet from Google Home
6987 - used to send commands from Google Home to Smart NORA

Are there any more ports that needs to be opened ?

**Comment by andrei-tatar** [comment]
Do you have firewall rules on the outgoing traffic from node-red?
The online state is set to `false` automatically by the database. Node-red stays connected to the database and it has a last will that tells the database to set `online` to `false` when the client is disconnected. Not sure how firebase detects if a connection is lost but I assume they use a periodic `ping-pong` mechanism with a timeout. This entire logic and the reconnect part is abstracted away. 
I can add more logs to show when the connection is made/lost, maybe it will help you debug.
Also the DB location is in Belgium.

**Comment by stanzlavos** [comment]
The firewall on my RPi4 is set to allow all outgoing traffic. For incoming messages I have explicitly added rules to accept traffic towards the ports I mentioned in my previous post (among others). Are there any more ports that needs to be opened ?

Regarding the state : who maintains the actual state of the switch? Is it maintained by the switch instance in node-red or in the DB (in Belgium)? Either way, its the sync to Google that is failing I suppose. Does this sync then happen between the Google framework and node-red directly or is the implementation such that this sync happens between google and smart nora DB in Belgium?

And about the logging part : Thank you for the offer and I'd be happy to accept it. :D How do we go about this though? Is there something I can do myself to enable more logs or add more logs?

**Comment by andrei-tatar** [comment]
> Are there any more ports that needs to be opened ?

Not as far as I know. :)

> who maintains the actual state of the switch? Is it maintained by the switch instance in node-red or in the DB (in Belgium)

It's in both places. Each time a change happens in the local node, an update is pushed to the db. When you open the Google Home app, google sends a query intent to the cloud service and the state is resolved from the db. 

> And about the logging part : Thank you for the offer and I'd gladly accept. :D How do we go about this though? Is there something I can do myself to enable more logs or add more logs?

I'll create a new branch and send you the details but it will probably be in > 7 days. I'm out with personal stuff until then.

**Comment by stanzlavos** [comment]
> It's in both places. Each time a change happens in the local node, an update is pushed to the db. When you open the Google Home app, google sends a query intent to the cloud service and the state is resolved from the db.

So, if we assume that my internet connection is working properly (:D), if Google is not able to get the device status, it has to be due to an issue in connectivity between Google and the DB ?

> I'll create a new branch and send you the details but it will probably be in > 7 days. I'm out with personal stuff until then.

I am glad that you even offered to help. :P Anyhow, please do not do anything as of now. Let me monitor things for a few more days. We will keep this as a last resort. :)

**Comment by andrei-tatar** [comment]
> So, if we assume that my internet connection is working properly (:D), if Google is not able to get the device status, it has to be due to an issue in connectivity between Google and the DB ?

No, it must be an issue in the connectivity between your node-red and nora cloud service. The connection between google and the db is more than 99.9% of the time up and running.

> I am glad that you even offered to help. :P Anyhow, please do not do anything as of now. Let me monitor things for a few more days. We will keep this as a last resort. :)

Any news?

**Comment by stanzlavos** [comment]
I haven't seen the issue in quite some time. Will close the issue for the time being. Thanks for the support. :)
