### ISSUE TITLE
Feature Request: Media Players

### ISSUE THREAD

**Issue by garv3** [andrei-tatar/node-red-contrib-smartnora#44]
It would be awesome to have media player nodes for things like TVs and Receivers.
This would be necessary to use commands like "Pause TV".

**Comment by KSumwalt** [comment]
I take it this would be a Media Remote?  I am looking to control my Squeezebox Server/Logitech Media Server with voice and believe the Media Remote Device Type is what would be needed to do this.

**Comment by andrei-tatar** [comment]
I was actually thinking of adding an option in the configuration to pick one of these device types:
    'action.devices.types.SPEAKER' |
    'action.devices.types.AUDIO_VIDEO_RECEIVER' |
    'action.devices.types.REMOTECONTROL' |
    'action.devices.types.SETTOP' |
    'action.devices.types.SOUNDBAR' |
    'action.devices.types.STREAMING_BOX' |
    'action.devices.types.STREAMING_SOUNDBAR' |
    'action.devices.types.STREAMING_STICK' |
    'action.devices.types.TV'

and the supported traits:
    'action.devices.traits.OnOff' |
    'action.devices.traits.MediaState' |
    'action.devices.traits.TransportControl' |
    'action.devices.traits.InputSelector' |
    'action.devices.traits.Volume' |

**Comment by andrei-tatar** [comment]
Released a RC version that includes the new media node: node-red-contrib-smartnora@1.1.0-0
Still need to update the docs.

**Comment by andrei-tatar** [comment]
Doc updated, v1.1.0 released. I will close this feature request. If there are any bugs, feel free to open new issues.
