### ISSUE TITLE
Nodes do not connect locally

### ISSUE THREAD

**Issue by garv3** [andrei-tatar/node-red-contrib-smartnora#45]
I am using a Google Home device to control the Smart Nora nodes. Unfortunately the nodes all show a green status icon so they are obviously using a cloud connection.
The Google Home is connected by wifi, the Home Assistant by LAN but they are on the same network.
How can I identify the reason for this behavior. 

Thank you!

**Comment by andrei-tatar** [comment]
@garv3 Are you asking about local execution?
It takes a few hours for google to pick up the local execution scripts and detect the devices.
They turn blue only as they receive local execution commands.
What devices do you have? Not all of them support local execution.

**Comment by garv3** [comment]
Yes, the issue was about local execution.
I have unlinked my instance and created a new one in the meantime. Now it seems to work for most of the nodes.
Scenes still don't seem to execute locally but I'm not sure if they even can.

**Comment by andrei-tatar** [comment]
I think you're right, I don't think scenes support local execution. 
There's not a clear list of devices that support local execution.
