### ISSUE TITLE
Switch and Outlet don't respond to online:false

### ISSUE THREAD

**Issue by rastitalabani** [andrei-tatar/node-red-contrib-smartnora#46]
Hello,

I'm trying to set online:false for switch/outlet doesn't seem to work, works fine with light. I have even used the flow json example still no dice

**Comment by andrei-tatar** [comment]
What version of the package are you using?

**Comment by andrei-tatar** [comment]
It seems there's a small bug in the switch/outlet nodes. I'll push a fix and publish a new version

**Comment by andrei-tatar** [comment]
Released v1.0.7 that should fix this issue.
