### ISSUE TITLE
Enhancement: add support for AC

### ISSUE THREAD

**Issue by andrei-tatar** [andrei-tatar/node-red-contrib-smartnora#48]
Add support for AC device type.
https://developers.google.com/assistant/smarthome/guides/acunit

All the required traits are already supported by the backend, only node-red node code is needed.

**Comment by patrik-malina** [comment]
What kind of help you are asking?

**Comment by andrei-tatar** [comment]
@patrik-malina A contribution for the node-red node would be great :)
Otherwise, I'll get to it when I have some time.

**Comment by patrik-malina** [comment]
I could help with testing if needed :)

**Comment by andrei-tatar** [comment]
@patrik-malina v1.0.12 was released with support for AC

**Comment by patrik-malina** [comment]
Nice. Will try and let you know. Thx
