### ISSUE TITLE
Speed modes not working in fan node

### ISSUE THREAD

**Issue by JaspervanKol** [andrei-tatar/node-red-contrib-smartnora#49]
Hi, I have a problem with the fan node when I am not using the percentage to control it.
There are 3 speeds defined: `low, medium & high` but when I change any of them or add / delete one it doesn't work.
When I click on `Done` in Node-RED it will not save any of the configured custom speeds.
So I am only able to use the `low, medium & high` speeds with Google Assistant.

**Comment by andrei-tatar** [comment]
Hi @JaspervanKol, 
Thanks for pointing this out. It seems there's a bug in the fan config editor. I'll push a fix shortly.

**Comment by andrei-tatar** [comment]
Published `v1.0.11`. Let me know if it's fine now so I can close the issue.
