### ISSUE TITLE
Created account

### ISSUE THREAD

**Issue by RickRiet** [andrei-tatar/node-red-contrib-smartnora#5]
He Andrei,

Added the node-red nodes and made a account. 
I see you are in alpha testing you need any help with that? 
I see that there are no possibilities to link to google home so far.

Rick

**Comment by andrei-tatar** [comment]
Only one way of linking it:

- Join the slack channel: https://join.slack.com/t/smart-nora/shared_invite/zt-m1vy0jfq-j7JrN85waaqw~l8LY5naSg
- send me a DM with the email address you are using with google home so I can add you to the project
- enable testing in Google Actions.

**Comment by kalimucho** [comment]
Hi Andrei,
Is it still possible to get invited into slack channel ?
Link provided is down.

Thanks

**Comment by labodj** [comment]
Hi @andrei-tatar I'm interested in testing this new project, I already made an account and I have more than 60 devices to test.
I don't know how to DM you here.

Thanks

**Comment by nicandris** [comment]
https://join.slack.com/t/smart-nora/shared_invite/zt-nn2w4efp-AXE5jUimp8gzqFI9NK62Ng

**Comment by kalimucho** [comment]
> https://join.slack.com/t/smart-nora/shared_invite/zt-nn2w4efp-AXE5jUimp8gzqFI9NK62Ng

thanks

**Comment by Medve01** [comment]
Hey guys,
I also would like to test the project if you accept me :)
Thank you

**Comment by andrei-tatar** [comment]
`Smart NORA` action should now be public in Google Home.
No more special things that need to happen in order to have access!
