### ISSUE TITLE
Google Assistant response of sensor node

### ISSUE THREAD

**Issue by JaspervanKol** [andrei-tatar/node-red-contrib-smartnora#50]
Hi, I have a problem with the response of Google Assistant when using the Sensor node.
When I ask what the temperature or humidity is, it will respond like this: 
`The Temperature is set to 21 degrees and is now 10 degrees`
`The Humidity is set to 40 percent, and the current humidity value is 60 percent`
Why is Google Assistant saying that the temperature / humidity is set to something while it is not possible to do that?

**Comment by andrei-tatar** [comment]
It does use the [TemperatureControl](https://developers.google.com/assistant/smarthome/traits/temperaturecontrol) trait behind the scenes, but it has a `queryOnlyTemperatureControl` that is set to true. So the Assistant behavior should be to only tell you about the temperature... (as far as I know).

Can you provide more details (not sure if it matters, but so I can try to reproduce it)?

- is this happening when asking a Google Home device (what device)?
- is this happening when asking Google Assistant on your phone?
- what is the exact phrase you are using to query the sensor?
- what if you use the sensor name "hey google, what is the <sensor name> temperature"?

**Comment by JaspervanKol** [comment]
Is this happening when asking a Google Home device (what device)?
- Yes, on a Google Nest Mini

Is this happening when asking Google Assistant on your phone?
- Yes

What is the exact phrase you are using to query the sensor?
- What is the humidity / temperature inside

What if you use the sensor name "hey google, what is the temperature"?

**Comment by JaspervanKol** [comment]
•	Is this happening when asking a Google Home device (what device)?
Yes, on a Google Nest Mini

•	Is this happening when asking Google Assistant on your phone?
Yes, this is also happening on a phone

•	What is the exact phrase you are using to query the sensor?
“Hey Google, what is the temperature / humidity inside”

•	What if you use the sensor name "hey google, what is the temperature"?
“The temperature is set to 21 degrees, and the current temperature is 16 degrees”
This also happens with humidity

Note: I am asking this to Google Assistant in dutch I don’t know if that matters?

**Comment by andrei-tatar** [comment]
I published `v1.0.11` with a change in the sensor state (removing the setpoint values). Let me know if it fixes it... Because I'm not able to reproduce your issue (using english, not dutch).

**Comment by JaspervanKol** [comment]
Thank you, it is working now. It will now only say what the current temperature / humidity is. You can close this issue.
