### ISSUE TITLE
can't install the plugin

### ISSUE THREAD

**Issue by Ahmed-farag36** [andrei-tatar/node-red-contrib-smartnora#53]
hello
I can't install the module throw node red palette or CLI, I got this error:
npm ERR! Unexpected end of JSON input while parsing near '...age":"2.1.0","xmlhttp'

**Comment by andrei-tatar** [comment]
@Ahmed-farag36  are you trying to do this on a Raspberry Pi? Which model?
I had similar issues and the card was corrupted. I ended up replacing it.

**Comment by Ahmed-farag36** [comment]
I am using node-red docker image

**Comment by andrei-tatar** [comment]
The installation is handled by `npm` so it's not really related to NORA. You could try `npm cache clean --force` to invalidate the cache (in case it's corrupt).

**Comment by Ahmed-farag36** [comment]
*FIXED* For future users,
Update npm to latest version and clean install node-red works for me
