### ISSUE TITLE
Changelog, does it exist?

### ISSUE THREAD

**Issue by Barabba11** [andrei-tatar/node-red-contrib-smartnora#54]
Hi mate, sorry to create a bug for this request, 
I've serached around and can't find a changelog, does it exist and where it is? It will help us followin the progress and probably avoiding useless posts like this. Thank you for understanding.
If it exist, can you please put it on more evidence on readme page? Thank you

**Comment by andrei-tatar** [comment]
It's here, on Github:
https://github.com/andrei-tatar/node-red-contrib-smartnora/releases

**Comment by Barabba11** [comment]
Thank you, great!
n this way I adviced for some reasons on my paette I couldn't see the latest 1.0.11, but it displayed me the 1.0.5 was up to date.. 
I've foced installing 1.0.11 with npm i node-red-contrib-smartnora

**Comment by Barabba11** [comment]
Just to ask you, is it normal to don't see temperature in google home? 
They are developing app incredibily bad..  we're waiting years for a serious support

![immagine](https://user-images.githubusercontent.com/13357642/125157840-df608500-e175-11eb-8202-b342ab176b5d.png)

**Comment by andrei-tatar** [comment]
Yes, unfortunately Google Home app for mobile devices doesn't support all the device types/traits/etc.

**Comment by Barabba11** [comment]
Ok, there are maybe other apps, with better visual interface than Google home, which can connect to it and get values?

**Comment by Barabba11** [comment]
Do you read me here? PLease reply, so I don't need to open a new issue for comunicating :)
Google is not supporting enough the app, I've noticed problem with blinds touch control and temperature sensor, the support told me the only way is to leave a feedback inside the Home app. I believe if all the Smartnora users can write there a couple of lines, we can push them solve them. I'm waiitng almost 2 years, unbelievable.
WHa t do you think about? Can you put this request on your readme page? Thank you a lot!

**Comment by andrei-tatar** [comment]
> Ok, there are maybe other apps, with better visual interface than Google home, which can connect to it and get values?

Not as far as I know. You can create your own dashboard in node-red or any other similar app so you can always view/control your home automation stuff from over there. Maybe that would be a "nice to have" feature in smart nora. Touch widgets for all the supported devices (including sensors).

> Do you read me here? PLease reply, so I don't need to open a new issue for comunicating :)

There is a "discussions" place over here on github. Feel free to start a new discussion and try to get more people involved: https://github.com/andrei-tatar/node-red-contrib-smartnora/discussions

> Google is not supporting enough the app, I've noticed problem with blinds touch control and temperature sensor, the support told me the only way is to leave a feedback inside the Home app. I believe if all the Smartnora users can write there a couple of lines, we can push them solve them. I'm waiitng almost 2 years, unbelievable.

I agree, they are moving slowly in regards to the android app. I already gave them feedback some time ago. It's pretty clear it's not a priority for them right now. I think all of the stuff supported by google home is meant to work with the assistant via voice, touch control is less of a priority.

> WHa t do you think about? Can you put this request on your readme page? Thank you a lot!

I won't put it on the readme page as I don't think NORA is the right place for this and the number of NORA users is under 2k anyways. But feel free to open a new topic in the discussion section. Maybe more users will get involved and report the same things.

**Comment by Barabba11** [comment]
thank you, I did open a new discussion. Thanks for your answers.
Please consider to add only one line on your readme, maybe like "some devices aren't displaying/controlling properly on Google Home app, this is not up to this module but for lack of support from Google, you can help us to solve this reading this discussion: https://github.com/andrei-tatar/node-red-contrib-smartnora/discussions/56
Thank you a lot!

**Comment by andrei-tatar** [comment]
It is in the FAQ:

https://github.com/andrei-tatar/node-red-contrib-smartnora/blob/master/doc/faq/README.md#some-devices-show-no-status-in-google-home-app-and-can-only-be-controlled-using-voice

**Comment by Barabba11** [comment]
I've checked it, but there you not mention about the discussion, so I guess no one can understand that his feedback on google will be precious for fixing problems. Can you kindly add this info? Thank you
