### ISSUE TITLE
Request: Filter on topic

### ISSUE THREAD

**Issue by Barabba11** [andrei-tatar/node-red-contrib-smartnora#58]
Hi, I've developed a standard function to manage all blinds, there is a particular output directed to all SmartNora nodes to acquire changes (coming from other control-devices through that function node), unfortunately I can't filter by topic so all will get the change in all Smartnora modules, can you please introduce it? Thank you a lot! :)
Virtual Smart Skill for Alexa and Komekit already have this useful feature

**Comment by andrei-tatar** [comment]
Yes, I think this would be useful. Probably in the next release.

**Comment by andrei-tatar** [comment]
@Barabba11 v1.0.12 was released with support for "filter by topic"

![image](https://user-images.githubusercontent.com/6473183/127019829-7a6078e7-6bb1-44b8-a808-1fda01fd9795.png)

**Comment by Barabba11** [comment]
thank you, I'm really glad :)
