### ISSUE TITLE
Request: Increased consistency in output format

### ISSUE THREAD

**Issue by tmichaeltx** [andrei-tatar/node-red-contrib-smartnora#59]
I love what is available within this palate. That said, I would love if the output would be more consistent. Here is an example that I have come across that I can work around, but that would be much easier if there was consistency of how power state is communicated:
Outlet (used to control a dumb table lamp) state output is **msg.payload = on or off**
Smart bulb without color or brightness control **msg.payload = on or off**
Smart bulb with brightness, but not color control **msg.payload = 0 is off** while **msg.payload = 1-100 is on at brightness**
Smart bulb with brightness and color control **msg.payload.on = false is off** while **msg.payload.on = true is on**

I would love for all 4 situations to have the same key for power state. I imagine that there are also variations across other node types, but these are the 2 that I am using immediately.

**Comment by andrei-tatar** [comment]
For the discrete (on/off) light/outlet/switch you can manually describe the on/off payload to match `msg.payload.on` = true/false.
For the brightness controllable light, you can also check `Send receive complete state as payload` so you will get the same `msg.payload.on` format.
![image](https://user-images.githubusercontent.com/6473183/126062785-32fa699d-1810-45a4-b5b5-142a533ce4d8.png)


It probably would've been better to just use the state from the google home as input/output payload, I imagined defining custom on/off payloads would be more useful.

**Comment by tmichaeltx** [comment]
I guess my preference since it is optional under those circumstances would be for it to be optional when there is no brightness control either. And to also be an option for any node where on/off is an option. That said, I have built a function node that does what I want, so easy enough to feed the output from the smartnora light node to it and then take the output from there.

You have done the hard work in building these nodes and like most of my Node Red work, I am benefitting from the great work of others.

**Comment by andrei-tatar** [comment]
Since the on/off inputs already accept messages in format `{payload:{on:boolean}}` format, I guess I can change the output defaults to a json `{on: true}`/`{on:false}` instead of just booleans.
