### ISSUE TITLE
SENSOR device

### ISSUE THREAD

**Issue by Paul-Reed** [andrei-tatar/node-red-contrib-smartnora#6]
Is there any chance that you could add the [SENSOR device](https://developers.google.com/assistant/smarthome/guides/sensor). 
It would provide a great deal of flexibility for node-RED IoT users, who are using local sensors.
For example; a lot of users use DS18B20 temperature modules, but using the existing THERMOSTAT device, google insists on announcing the heating set point, so cannot be used.
With the SENSOR device, just temperature could be selected as a trait.

**Comment by andrei-tatar** [comment]
It's on the TODO list.
