### ISSUE TITLE
Suggested Documentation clarification

### ISSUE THREAD

**Issue by tmichaeltx** [andrei-tatar/node-red-contrib-smartnora#60]
Looking at [https://github.com/andrei-tatar/node-red-contrib-smartnora/blob/master/doc/nodes/light/README.md](url) I see that for inputs msg.payload.on = true/false is accepted to turn the light on and off. Experimentation has shown me that this is true regardless of whether the brightness or color or neither box is checked, but it is in the output only if brightness or color is checked.

I actually find it convenient on the input side, but didn't expect it to be accepted until I read the existing documentation.

**Comment by andrei-tatar** [comment]
Can you also suggest how to edit it to make it more clear?

**Comment by tmichaeltx** [comment]
I will get back to you with a suggestion. It is hard to say without getting very very wordy and I have to travel some of the next few days, but appreciate your responsiveness. Hopefully I can come up with a good suggestion.
