### ISSUE TITLE
Thermostat range not updating/ correct

### ISSUE THREAD

**Issue by RGarrett93** [andrei-tatar/node-red-contrib-smartnora#61]
The thermostat range doesn't work, eg I've set the thermostat range of a min 20C and max 40C but unfortunately this does not reflect on google home, the thermostat range can only be set min 9C degrees and a max 32C degrees on google home.
I can set the temperature to go above 32C with google assistant and see the target on Node Red updating along with my device but moments later it will revert back to a default 20C (I assume because it is out of range that is why it always reverts back to 20C) - if I set the temperature between 9C & 32C via google assistant it doesn't revert back.
Thanks
Ryan

**Comment by andrei-tatar** [comment]
Nora does the range to google home but it seems the google home app doesn't use that in the UI.

It has been raised before:
https://github.com/andrei-tatar/node-red-contrib-smartnora/issues/19

**Comment by RGarrett93** [comment]
I also realised I made a slight mistake in my assignments which was why it kept reverting back to 20C.
Its just the UI that's slightly out but besides that it is working great.
Thanks for getting back to me so quick.
