### ISSUE TITLE
Install Smartnora in node-red addon for Home-Assistant

### ISSUE THREAD

**Issue by Nik19792000** [andrei-tatar/node-red-contrib-smartnora#62]
I tried installing Smartnora to the node-red add of Home-Assistant. I used the general instructions using "Manage Palette" -> Install, but the installation always failed.
The node-red add on of Home-Assistant has a startup configuration (under Supervisor -> Node-Red -> Configuration Tab). This allows to specify NPM packages to install. I modified as follows:
npm_packages:
  - node-red-contrib-smartnora@1.0.11

This will install Smartnora nodes when starting Node-Red addon. Maybe this can be added to the documentation.

**Comment by FireWizard52** [comment]
Hi, @Nik19792000 ,

I don't think, this should be added to the documentation of SmartNora, as this is typical related to the Node RED addon for Home Assistant. SmartNora is een collection of nodes for Node RED and this can be used for any Home Automation System. This might cause confusion for users, installing SmartNora the default way.

So this should documented in the Home Assistant documentation and more specific in the Node RED addon section, if that exists.

**Comment by Nik19792000** [comment]
I believe many Node-Red users use the Home-Assistant add-on, but hopefully this issue description will help others facing the same issue.
