### ISSUE TITLE
New function "Ignore input messages that don't match the topic value" is not working, if external input is received. 

### ISSUE THREAD

**Issue by FireWizard52** [andrei-tatar/node-red-contrib-smartnora#64]
Hello Andrei,

Yesterday I updated SmartNora from version 1.0.11 to 1.0.12 (Node Red, version 1.3.5 and did some testing.
I tested only the noraf-light node, but I assume, it is applicable to the other nodes as well.

Discovered the following:

If "Ignore input messages that don't match the topic value:" is unticked, the node functions as before.
If "Ignore input messages that don't match the topic value:" is ticked and if you send an "On" command (true) to the Input both the indication under the node and the indication in the Google Home app, do not indicate that the node has been switched "ON".
If I switch the light in the Google Home app, everything is working fine.

If I switch the light in the Google Home app to "ON", it is correctly indicated in both the Google Home app and under the
noraf-light node. However sending afterwards an "Off" command (false) to the input, doesn't change the indication in the Google Home app and under the noraf-light node.

So it looks that the external input is completely ignored, regarding indication under the node and the Google Home app.
So no synchronization, if the box is ticked.

Regards.
Herman.

**Comment by andrei-tatar** [comment]
That is the expected behavior. It basically ignores any input message that has a topic that doesn't match the "Topic" value of the node.

For example:
```
[{"id":"43e4d3e7.b408bc","type":"noraf-light","z":"b9a14f5917f73660","devicename":"Light","lightcolor":false,"brightnesscontrol":false,"commandonlycolor":false,"turnonwhenbrightnesschanges":false,"passthru":false,"errorifstateunchaged":false,"statepayload":false,"brightnessoverride":"","roomhint":"","name":"","colortype":"rgb","nora":"f1e538c1.0315f8","topic":"topic/is/important","onvalue":"true","onvalueType":"bool","offvalue":"false","offvalueType":"bool","temperaturemin":"2700","temperaturemax":"5500","twofactor":"off","twofactorpin":"","filter":true,"x":390,"y":300,"wires":[["cfca929e.e531"]]},{"id":"3fc16ca9.e4f834","type":"inject","z":"b9a14f5917f73660","name":"On (this will be ignored)","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"true","payloadType":"bool","x":180,"y":240,"wires":[["43e4d3e7.b408bc"]]},{"id":"cfca929e.e531","type":"debug","z":"b9a14f5917f73660","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":570,"y":300,"wires":[]},{"id":"31b3b56cf228b100","type":"inject","z":"b9a14f5917f73660","name":"On (this will work)","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"topic/is/important","payload":"true","payloadType":"bool","x":160,"y":300,"wires":[["43e4d3e7.b408bc"]]},{"id":"f1e538c1.0315f8","type":"noraf-config","name":"NORA","group":"","twofactor":"off","twofactorpin":"","localexecution":true,"structure":""}]
```

It allows you to do things like this:
![image](https://user-images.githubusercontent.com/6473183/127376941-ca486a09-1b15-457a-9979-f4fbebb6404b.png)

**Comment by FireWizard52** [comment]
Hello Andrei,

You said:

> That is the expected behavior.

Is it? I didn't say it in my previous post, but I send a message with a topic, identical to what is in the "Topic" setting,
As far as I understand the functionality. this message, and only this message, should pass and should activate both the correct indication in the Google Home app and the  correct indication under the node.

Please see below, the message, that has been sent to the SmartNora node:

![Screenshot_smartnora-light1](https://user-images.githubusercontent.com/46283323/127386736-5d8678e0-5800-47d3-bbf8-b16c472f7719.png)

See, the configuration of the node below:

![Screenshot_smartnora-light2](https://user-images.githubusercontent.com/46283323/127386835-d88f4a09-b4c2-4fef-8805-c1d17408af0b.png)

Regards,

Herman

**Comment by FireWizard52** [comment]
Dear Andrei,

Issue is solved. Suddenly I got a brainwave.

The topic, I use, is taken from a payload and that payload is a number. You can see that above.
So the topic was a number instead of a string.
Actually it is an index from a switch, as it is used with Domoticz. (That is the way to do it with Domoticz).

Due to the type checking in SmartNora it does not accept a number as topic. Quite sensible.
Changing the number to a string solved it.

Sorry for my mistake and the time you used to answer this issue.
Thank you for a great SmartNora product.

Regards

Herman

**Comment by andrei-tatar** [comment]
> Due to the type checking in SmartNora it does not accept a number as topic. Quite sensible.

I could update the comparison to be more forgiving. Convert to strings, trim them, ignore case. What do you think?

> Sorry for my mistake and the time you used to answer this issue.

No worries. There are no mistakes here.

> Thank you for a great SmartNora product.

You're welcome :)

**Comment by FireWizard52** [comment]
Hello @andrei-tatar,

> I could update the comparison to be more forgiving. Convert to strings, trim them, ignore case. What do you think?

What do I think?

There is no specification that defines that "msg.topic" has to be a string, as far as I know. It has become more or less a habit.
However in my opinion it is the "responsibility" of the previous node that the msg is sent in the correct format.
It should be clearly documented in the node what is expected on the input of the node.

On the other hand, as I was unable to see, whether the topic was a number or a string, it might be an idea to be more forgiving if you receive a number instead of a string. However for me, as soon as I knew what the root cause was, it was easy to fix. (Just added toString())
But to trim or to ignore case is very tolerant and may not match the idea behind that new function, filter on topic.

But in the meantime you changed already the functionality. (https://github.com/andrei-tatar/node-red-contrib-smartnora/commit/52259e8b0a9b7ea347c998e6353cee89db86a056)

Regards

**Comment by andrei-tatar** [comment]
> But to trim or to ignore case is very tolerant and may not match the idea behind that new function, filter on topic.

True, I also checked MQTT spec and it's case sensitive and it does accept spaces in the topic, though I honestly don't think anyone is using different topics with same name but different casing.

I will only convert to string and remove the string/case insensitive comparison.

**Comment by FireWizard52** [comment]
@andrei-tatar ,

I agree with you and think this is probably a good compromise.
I think most users can live with the proposed solution.

So, I think we can close this issue.

Regards
