### ISSUE TITLE
why does the widget in Google home not have the ability to adjust the fan speed, but only the ability to turn on/off? By the way, the same thing is in the AC unit module, there is no possibility to change the speed in the widget in Google Home, thanks.

### ISSUE THREAD

**Issue by iljinmihail** [andrei-tatar/node-red-contrib-smartnora#66]

**Comment by andrei-tatar** [comment]
Check out the FAQ: 

### [Some devices show no status in Google Home app and can only be controlled using voice](https://github.com/andrei-tatar/node-red-contrib-smartnora/blob/master/doc/faq/README.md#some-devices-show-no-status-in-google-home-app-and-can-only-be-controlled-using-voice)

In short, these are the only things you can change via the Google Home phone app:
https://developers.google.com/assistant/smarthome/develop/touch-controls#supported_traits_3
- Brightness
- CameraStream
- ColorSetting
- Dock
- OnOff
- RunCycle
- StartStop
- TemperatureSetting
