### ISSUE TITLE
How to send notify

### ISSUE THREAD

**Issue by natandiasm** [andrei-tatar/node-red-contrib-smartnora#7]
Hello, You would have some sample code to send a notification, I already activated it on the Smart NORA site, and I already made the node, but I get an error message.

Not a valid notification object: [{"keyword":"additionalProperties","dataPath":"","schemaPath":"#/additionalProperties","params":{"additionalProperty":"0"},"message":"should NOT have additional properties"}]

**Comment by andrei-tatar** [comment]
This works:

```
[{"id":"4e86eff8.dff37","type":"noraf-notify","z":"c230ee07.476c7","tag":"","title":"Hello","body":"It works!","icon":"","name":"","nora":"7342540d.39289c","topic":"","actions":[],"x":410,"y":160,"wires":[["87a4f5c1.1ebba8"]]},{"id":"9c71c421.f29558","type":"inject","z":"c230ee07.476c7","name":"","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":170,"y":140,"wires":[["4e86eff8.dff37"]]},{"id":"87a4f5c1.1ebba8","type":"debug","z":"c230ee07.476c7","name":"","active":true,"tosidebar":true,"console":true,"tostatus":true,"complete":"true","targetType":"full","statusVal":"payload","statusType":"auto","x":700,"y":140,"wires":[]},{"id":"7342540d.39289c","type":"noraf-config","name":"nora config","group":"test","twofactor":"off","twofactorpin":"","structure":"Test"}]
```

What version of the package do you have?

**Comment by natandiasm** [comment]
**Smart NORA** 1.0.0-alpha-6 
**node red** 1.2.2
Host on **ibm cloud**

**Comment by andrei-tatar** [comment]
Post a minimal flow that fails for you.

**Comment by natandiasm** [comment]
![Captura de Tela 2021-02-25 às 11 13 47](https://user-images.githubusercontent.com/5016971/109195199-fbd8c380-7778-11eb-80a5-bfc929720387.png)

just receive some message via Matt and should notify

**Comment by andrei-tatar** [comment]
Might be a bug. Try converting the payload to an empty object with a function node.

**Comment by natandiasm** [comment]
Ok, it work, tnks :)
