### ISSUE TITLE
AC node code

### ISSUE THREAD

**Issue by patrik-malina** [andrei-tatar/node-red-contrib-smartnora#72]
@andrei-tatar I'm looking to your code and noticed that in https://github.com/andrei-tatar/node-red-contrib-smartnora/blob/1afc05af26e1a6cf0205f25dec6d30e3885fb809/src/nodes/nora-ac.ts#L18 shouldn't state action.devices.types.AC_UNIT as per documentation on https://developers.google.com/assistant/smarthome/guides/acunit? I could try it, but don't know (yet) how to write node-red...

**Comment by andrei-tatar** [comment]
Ah, you're right. I did copy most of the configuration code from the thermostat node. I'll fix it shortly.

**Comment by andrei-tatar** [comment]
should be fixed now in `v1.1.3`

**Comment by patrik-malina** [comment]
Yeah, this is right icon of AC...

![Screenshot_20210810-113310_Home](https://user-images.githubusercontent.com/73561855/128844467-79d4d328-c441-4aac-8362-275bee7c6200.jpg)

**Comment by normanr** [comment]
I can't get Google Home to do anything useful with the AC_UNIT. Am I missing something, or does Google Home just not actually support it properly yet?

**Comment by normanr** [comment]
Ahh, there are no touch controls, but voice control does work.

**Comment by andrei-tatar** [comment]
@normanr Unfortunately only a few traits can be controlled from Google Home app (https://github.com/andrei-tatar/node-red-contrib-smartnora/tree/master/doc/faq#some-devices-show-no-status-in-google-home-app-and-can-only-be-controlled-using-voice).

**Comment by patrik-malina** [comment]
Its working good with me.
Can change mode, fan speed, temperature, on/off with voice.
