### ISSUE TITLE
Scalability of Smart NORA

### ISSUE THREAD

**Issue by hitenlulla** [andrei-tatar/node-red-contrib-smartnora#73]
What if I want to sign up different users from a single smart Nora Account. Example: I signed up on Smart Nora using my Gmail ID. Now I want to enable smart appliances of my friends on their Google Home app. But I don't want to create tokens for everyone's Gmail Account, instead I want to use my token and give their Gmail Accounts permission to use the token. Is it possible?

**Comment by andrei-tatar** [comment]
Hi,

Smart NORA doesn't have tokens like the old NORA. You need to create user accounts. 
If your friend has his own devices, he should have a different (his own) Smart NORA account.
If you want to share your devices with your friend, you can do that from the Google Home app.

Right now it's not possible to link different Google Home accounts to the same Smart NORA account and I don't really see a reason to support this. Creating multiple accounts is free/fast/easy.

If you have a different use case and would like to discuss it, feel free to open a discussion topic here: https://github.com/andrei-tatar/node-red-contrib-smartnora/discussions
