### ISSUE TITLE
Updating status of manual switches

### ISSUE THREAD

**Issue by hitenlulla** [andrei-tatar/node-red-contrib-smartnora#75]
Hello, I had a query. If I use manual switches to turn on/off the appliance. How can I update the state of the appliance in google home app using Smart NORA ? For example I turn on a bulb using the switch, It doesn't show 'on' status on google home app.

**Comment by andrei-tatar** [comment]
It's not really clear what the problem is. Do you have an example flow? 

Google Home app doesn't do real-time updates when a widget is open. But it does update the state of the widgets on the main screen. So it's unreliable.

**Comment by FireWizard52** [comment]
HI, @hitenlulla,

You wrote:

> If I use manual switches to turn on/off the appliance.

What kind of switches do you use, traditional or smart devices?

> How can I update the state of the appliance in google home app using Smart NORA ?

If it are smart devices, how do they interact with Node Red?
Or can you make it, that they have communication with Node Red.

> For example I turn on a bulb using the switch, It doesn't show 'on' status on google home app.

If they do not send their status to Node Red, it is impossible that SmartNora knows the status and so consequently can update the status in the Google Home app.

Regards

**Comment by hitenlulla** [comment]
I managed to work it out. Looks like google home's interface takes some time to update the changes. I had to wait for a couple of seconds to see the status of the switch. Basically I published a MQTT message for manual switches and sent it to Smart Nora using Node red. Thanks for your reply.♥️

**Comment by FireWizard52** [comment]
That's indeed a way to do it.
So the issue is solved.

Regards

**Comment by hitenlulla** [comment]
Hey @andrei-tatar @FireWizard52 When I am using the 'Fan' Node, I'm not able to see the slider to change the percentage. I checked the 'Control speed using percentage'.

**Comment by FireWizard52** [comment]
I do not use the 'Fan' node and so I'm not able to help you.
Sorry.o

**Comment by andrei-tatar** [comment]
@hitenlulla what slider?

**Comment by hitenlulla** [comment]
Slider to change the fan speed. Like the one we have to change the brightness of light.

**Comment by andrei-tatar** [comment]
Not all traits are supported in the Google Home app. `FanSpeed` is one of them:
https://github.com/andrei-tatar/node-red-contrib-smartnora/blob/master/doc/faq/README.md#some-devices-show-no-status-in-google-home-app-and-can-only-be-controlled-using-voice

**Comment by andrei-tatar** [comment]
@hitenlulla  Is your issue resolved?

**Comment by hitenlulla** [comment]
Yes sir, that issue was solved. One more question,  I want to send the brightness value from node red dashboard to smart nora light node. What is the format of payload we need to send? I read the documentation but it wasn't clear.

This is a function node I've attached from node red dashboard to smart nora node:
msg.payload = {
    "brightness":75,
    "on": true,
    "online": true,
}
return msg;

**Comment by andrei-tatar** [comment]
This should work to update the brightness:
```
msg.payload = {brightness: 50};
```

Make sure you check the [Light node documentation](https://github.com/andrei-tatar/node-red-contrib-smartnora/tree/master/doc/nodes/light).

**Comment by hitenlulla** [comment]
This issue has been resolved. Thank you @andrei-tatar @FireWizard52 You can close the issue.
