### ISSUE TITLE
unable to install node red pallets on IBM cloud : qIXfdQPInJadIOqRr3ZTF86pfKE2

### ISSUE THREAD

**Issue by gauravmyid** [andrei-tatar/node-red-contrib-smartnora#77]

**Comment by gauravmyid** [comment]
i have been trying to install smart-nora pallets on node red running on IBM Cloud server but unable to do so. please help. i was previously successfully using the same on google cloud server.

**Comment by andrei-tatar** [comment]
I never used IBM cloud. Is there a more detailed log or something?
From the screenshot you added, it doesn't look like something went wrong. It might just take longer.

**Comment by gauravmyid** [comment]
I have tried installing multiple  times but still doesn't work

**Comment by andrei-tatar** [comment]
I would try asking for help on the node-red forum. Maybe someone is using IBM cloud over there.
`node-red-contrib-smartnora` is just an npm package that gets installed using `npm`. It should be as platform independent as possible.
