### ISSUE TITLE
If state doesn't change via voice, warn user not implemeted for Media and Security

### ISSUE THREAD

**Issue by FireWizard52** [andrei-tatar/node-red-contrib-smartnora#81]
Hello,

This is just a question regarding the "Media" device and "Security".

Many devices, like lights have the option to set: "If state doesn't change via voice, warn user", while others, such as the garage door has the option to set: "Warn user if already open/closed".

However, if I look to the new media device, e.g. a TV, I do not see a similar option, if the On/Off trait is enabled.
The same with the security device.

Is this something that has not been implemented by Google, or is it left out by purpose or just an omission?

Regards

**Comment by andrei-tatar** [comment]
It can be added. Just an omission. Feel free to create a PR or we can leave it on the backlog...

**Comment by FireWizard52** [comment]
I suggest we leave it for the backlog, as I'm not that familiar with the structure of SmartNora, so that I can make a complete PR for both the "Media" device and the "Security" device. I would be a blind, untested guess, copied from another file.
Not a good idea.

I also saw another issue, regarding the "Security" node, which is probably also an issue for the backlog.

By default the status under the node indicate: disarmed, L1 (unless you changed that, like I did. I changed that to "armed_home")

See screenshot below

![image](https://user-images.githubusercontent.com/46283323/130236844-e9f038b6-4445-4629-b950-5196fe0a9fb0.png)

This is quite confusing, to see both disarmed and armed_home.
The documentation indicate that, "isArmed - boolean, default: false. Indicates if the device is currently armed." "false" is the default value and so in my opinion the text "disarmed" should be sufficient.

See:

![image](https://user-images.githubusercontent.com/46283323/130239228-a43a8486-05a4-462f-809b-0f68d5604400.png)


Also it is unsure how "exitAllowance - number, default: undefined. Indicates the time, in seconds, the user has to leave before currentArmLevel takes effect." has to be handled. What does it and how to use it?

Regards

**Comment by andrei-tatar** [comment]
Yup, I will make the status text a bit more clear.

> Also it is unsure how "exitAllowance - number, default: undefined. Indicates the time, in seconds, the user has to leave before currentArmLevel takes effect." has to be handled. What does it and how to use it?

That's all the information I have as well: https://developers.google.com/assistant/smarthome/traits/armdisarm#device-states

**Comment by FireWizard52** [comment]
In that link, I see only: "exitAllowance | Integer | Indicates the time, in seconds, the user has to leave before currentArmLevel takes effect.", so that is not of much help. I don't think it should be combined with "isArmed: false|true".

However, in this link "https://github.com/actions-on-google/smart-home-nodejs/issues/253", I found: "exitAllowance (Will announce how much time you have left)"

This is really the only thing, I can find on the Internet.

Regards

**Comment by andrei-tatar** [comment]
I think `exitAllowance` is meant to provide info to google assistant how much time (in seconds) the user has before the security system is armed. I don't think it uses it for now since it doesn't say "security system is armed, you have 30 seconds to leave" :)

The other small issues should be fixed in v1.3.1
