### ISSUE TITLE
AppSelector Trait

### ISSUE THREAD

**Issue by pschucker** [andrei-tatar/node-red-contrib-smartnora#83]
Feature Request

Add support for  [AppSelector Trait](https://developers.google.com/assistant/smarthome/traits/appselector) for Media Devices like TV, Streaming Stick

**Comment by andrei-tatar** [comment]
@pschucker thanks for the AppSelector contribution to `nora-firebase-common`. It's integrated in the API and the database rules have been updated!

**Comment by andrei-tatar** [comment]
@pschucker Do you have time to look into adding the trait to the media node as well?

**Comment by pschucker** [comment]
I don't have a lot of experience with Node-RED. However, the code doesn't look that complicated. So I can try it. 

But I wonder whats the best way for testing the code?

**Comment by andrei-tatar** [comment]
@pschucker Testing the code can be done locally. The new trait is already integrated in the service, so only the node-red plugin needs to be updated.

The way I do it is using `npm link` to link a local build of smartnora into a local instance of node-red.
It's a bit more involving if you also need to debug the code.
