### ISSUE TITLE
Forward all media commands to output 2 (Media node)

### ISSUE THREAD

**Issue by pschucker** [andrei-tatar/node-red-contrib-smartnora#84]
Currently only the commands for Transport Control Trait and the Channel Trait can be retrieved through output 2. Other commands like on/off, volume change, mute, input change are only reflected by state change in output 1.

That makes it hard for me to react to these changes. Because in my setup the state is never up to date and so I have no way to determine which value is just outdated and can be ignored, and which value was recently changed by a command and have to behandled. (The device can also be controlled by a remote control and it is not possible to reflect these changes back to state).

Having all commands on output 2 allows me to correctly control my device.

Missing commands:

OnOff
mute
setVolume
volumeRelative
SetInput
PreviousInput
NextInput

**Comment by andrei-tatar** [comment]
This will come with async command execution, where you can write your own handlers for all commands: https://github.com/andrei-tatar/node-red-contrib-smartnora/blob/master/doc/nodes/async.md

Right now it's experimental and only enabled for a few nodes.

**Comment by andrei-tatar** [comment]
@pschucker This should work now with the release of `1.5.0`.
