### ISSUE TITLE
Support Door/Window Senor

### ISSUE THREAD

**Issue by bluenazgul** [andrei-tatar/node-red-contrib-smartnora#86]
Iam using Home Assistent in combo with Node Red

I allready have exposed my Windows Contact to Google Home using Home Assistent, but I have to ask for every Single Sensor.

I would like to have a Sensor called Windows that include all my HA Window Sensors

So i could be able to ask Google "Hey Google, are the Windows closed" and answer could be "all Windows are close" or "1/2/3..... Windows are open"

And with the question "wich Windows are open" i would receive the answer eg " Kitchen and Living Room are open"

**Comment by andrei-tatar** [comment]
@bluenazgul:

1. This is not a HA plugin. I personally don't use HA, but as far as I know there's no direct way for NORA to get a list of all the windows from your HA Window Sensors. You can manually define each one of them in node-red and create the flow to sync the state.

2. I'm not sure if Google Assistant supports these kind of queries if you have multiple windows or not, but I am sure we can not extend that. NORA is bound to the SmartHome actions of the Google Assistant. Meaning, NORA is responsible to provide the devices/types/states/etc. to Google but the voice interaction part is all on the Google side.
