### ISSUE TITLE
noraf-light node produces no output

### ISSUE THREAD

**Issue by murjam** [andrei-tatar/node-red-contrib-smartnora#87]
Just set up Smart NORA for my Node-RED, but unfortunately the simplest node (light) produces no output when the state is changed from Google Home.

Overall, my setup works because other nodes work, also when I change the state of the light in Node-RED, the state changes in Google Home.

`node-red-contrib-smartnora` version `1.4.1`

**Comment by andrei-tatar** [comment]
@murjam can you share the flow that is not working for you? I use the light nodes on a daily basis and I'm as well on the latest version and didn't notice an issue.

**Comment by murjam** [comment]
Sorry for the delay, here it is
```json
[
    {
        "id": "168bb8c230fa5dc9",
        "type": "noraf-light",
        "z": "c28fa621.5fc2a8",
        "devicename": "test light",
        "lightcolor": false,
        "brightnesscontrol": true,
        "commandonlycolor": false,
        "turnonwhenbrightnesschanges": true,
        "passthru": false,
        "errorifstateunchaged": false,
        "statepayload": true,
        "brightnessoverride": "",
        "roomhint": "Living room",
        "name": "test light",
        "colortype": "rgb",
        "nora": "3a4a1f2e962375cc",
        "topic": "",
        "onvalue": "true",
        "onvalueType": "bool",
        "offvalue": "false",
        "offvalueType": "bool",
        "temperaturemin": "2700",
        "temperaturemax": "5500",
        "twofactor": "off",
        "twofactorpin": "",
        "filter": false,
        "x": 920,
        "y": 320,
        "wires": [
            [
                "26127f7bdfcf0493"
            ]
        ]
    },
    {
        "id": "26127f7bdfcf0493",
        "type": "debug",
        "z": "c28fa621.5fc2a8",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": true,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 1090,
        "y": 320,
        "wires": []
    },
    {
        "id": "4a7f25c4becfd0bc",
        "type": "inject",
        "z": "c28fa621.5fc2a8",
        "name": "",
        "props": [
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "{\"on\": false}",
        "payloadType": "json",
        "x": 750,
        "y": 320,
        "wires": [
            [
                "168bb8c230fa5dc9"
            ]
        ]
    },
    {
        "id": "3a4a1f2e962375cc",
        "type": "noraf-config",
        "name": "Home",
        "group": "",
        "twofactor": "ack",
        "twofactorpin": "",
        "localexecution": true,
        "structure": "Home"
    }
]
```

So, injecting it "OFF" will turn it off in Google Home, but changing the state in Google home does not change the state in Node-RED nor does produce an output message.

**Comment by FireWizard52** [comment]
Hello @murjam 

I loaded your flow and it functions as expected.

The only thing I did was:

1. Added another "Inject" node, in order to be able to inject a JSON with  boolean "true".
2. Changed the nora-config node to my node, in order to test it.
3. In the "Debug" node I ticked "off" the "Debug to the console", but ticked it later to "on".

In my opinion this should not have impact on the functioning of the flow

I operated the test light from my Google Home app.

It works normal, so I'm afraid you have to test once more or the problem is related to your config node.
In your nora-config node, I did see that you have "Two Factor" set as "Acknowledge".

Might this be an issue? Try to set this to "Node".

Regards

**Comment by murjam** [comment]
The "two factor" setting of the configuration does not have the option "None", but it does have "Node". Maybe it is a typo :shrug: 

Anyways, setting it to "Node" did the trick :partying_face: 
Thank you for the hints!
