### ISSUE TITLE
Any better app than Google Home?

### ISSUE THREAD

**Issue by Barabba11** [andrei-tatar/node-red-contrib-smartnora#88]
Hi mates, sorry to open an issue to ask thei question, I hope it will be useful to everybody to know if there is an app, based on Google Home services, that will show us better layout for our devices. I mean, as it is available for Homekit, if Google Home leaves other apps accessing its data, and create a better dashboard.
Thank you for your kind answers

**Comment by andrei-tatar** [comment]
As far as I know, there is no other app. 😞

**Comment by Barabba11** [comment]
I got it, thanks.
I was thinking, like Homekit, it gives the chance for other apps to onterface and get datas, it seams not.. unique app with unique connection

**Comment by andrei-tatar** [comment]
I was thinking of adding a simple widget interface to https://smart-nora.eu/my-nora to allow to view state and send commands. But I guess there's not much benefit since you can always use node-red dashboard...

**Comment by Barabba11** [comment]
Yes, no benefits, thanks for idea :)
I just would know if Google Home is a service which can be used by other apps (like Homekit does) or it's a simple standalone app that has the only opportunity to connect to google home servers.
Thanks
