### ISSUE TITLE
New SmartNora version 1.4.2 not available in Manage palette

### ISSUE THREAD

**Issue by FireWizard52** [andrei-tatar/node-red-contrib-smartnora#95]
Hello @andrei-tatar,

Not a real issue, but I noticed that the latest version 1.4.2 could not be installed, if you use "Manage palette".

I did not try to update, using the cli, as the change is not that important for me.

Regards

**Comment by andrei-tatar** [comment]
Hey @FireWizard52 
I probably forgot about it. It's a manual process now, it would be cool to automate it with an API call on each release (I'll have a look if possible).

It's been fixed now 🙂
