### ISSUE TITLE
No device in my account

### ISSUE THREAD

**Issue by geotibi** [andrei-tatar/node-red-contrib-smartnora#99]
I've created some flows in node-red but when I deploy them I have nothing in myaccount for NORA. It worked in the past but now stopped.

![image](https://user-images.githubusercontent.com/18015446/133610762-588732a0-9e1d-4736-af10-acc2ac9f8e27.png)

![image](https://user-images.githubusercontent.com/18015446/133610921-a2aad1d9-a234-4017-9689-cad55fa6cbb4.png)

I'm using node-red-contrib-smartnora  1.5.0

**Comment by andrei-tatar** [comment]
Any logs in node-red?

**Comment by geotibi** [comment]
I have some errors related to some other nodes. Can be this an issue?
![image](https://user-images.githubusercontent.com/18015446/133612385-d887246e-90c3-4c9d-88d1-a7f9e82495c5.png)

**Comment by andrei-tatar** [comment]
Most probable since it says the flows are stopped.

**Comment by geotibi** [comment]
That was the issue. I removed the nodes with problems and now it's working

**Comment by geotibi** [comment]
Now I have a question about sensor that I added in nodered. This one it's showed in Home app like a shield and it's not showing the data. Look like it's not recognized.

![image](https://user-images.githubusercontent.com/18015446/133622460-36bfffc4-db32-4032-accd-b092d6588c79.png)
